### ISSUE TITLE
prepatch full GKI fail.

### ISSUE THREAD

**Issue by Aarqw12** [chenxiaolong/avbroot#102]
hi, so lets explain my problems I have build full gki witch kernelsu (and other mod) its result 4 img generated : boot.img , vendor_boot.img , vendor_dlkm.img , dtbo.img . flashing only boot.img will no boot regarding to change I made.

I see avbroot support only --prepatched for boot. could you look into it ?

**Comment by chenxiaolong** [comment]
Sorry, I don't quite understand what you are asking for. Could you explain a bit more?

Are you asking for a new option in avbroot that allows any partition to be replaced?

**Comment by Aarqw12** [comment]
> Sorry, I don't quite understand what you are asking for. Could you explain a bit more?
> 
> Are you asking for a new option in avbroot that allows any partition to be replaced?

yes replace vendor_boot , vendor_dlkm , dtbo , boot

also I have followed all step in my pixel 6  for flash stock rom using patched magisk boot for test I have do :  
-- preparation , key created ex ...

I flash : 
# Flash the boot images that were extracted
for image in extracted/*.img; do
    partition=$(basename "${image}")
    partition=${partition%.img}

    fastboot flash "${partition}" "${image}"
done

# Flash the AVB signing public key
fastboot erase avb_custom_key
fastboot flash avb_custom_key /path/to/avb_pkmd.bin

reboot , rom boot properly but its impossible to relock bootloader I get error 
FAILED (remote: 'invalid android images, skip locking')

I have go in recovery and doing adb sideload patched rom , its boot again but still impossible to lock bootloader

**Comment by chenxiaolong** [comment]
> yes replace vendor_boot , vendor_dlkm , dtbo , boot

OK, got it. I think that should be pretty simple to implement. I'll look into it soon.

> reboot , rom boot properly but its impossible to relock bootloader I get error
> FAILED (remote: 'invalid android images, skip locking')

Hmm, I have no idea what would cause this. I searched around for the `invalid android images, skip locking` error and it seems that some people run into that even with the unmodified factory image.

I did see someone mention that restoring to stock with https://flash.android.com/ once resolved the issue (instead of factory image + `flash_all.sh`). Maybe that's worth a try?

**Comment by Aarqw12** [comment]
> > yes replace vendor_boot , vendor_dlkm , dtbo , boot
> 
> OK, got it. I think that should be pretty simple to implement. I'll look into it soon.
> 
> > reboot , rom boot properly but its impossible to relock bootloader I get error
> > FAILED (remote: 'invalid android images, skip locking')
> 
> Hmm, I have no idea what would cause this. I searched around for the `invalid android images, skip locking` error and it seems that some people run into that even with the unmodified factory image.
> 
> I did see someone mention that restoring to stock with https://flash.android.com/ once resolved the issue (instead of factory image + `flash_all.sh`). Maybe that's worth a try?

I have doing search its mean bootloader detect not all partition is in "stock state" for avoid brick its abort by this error I need relook what is wrong in payload.bin patching maybe for pixel 6 something is missing in avb patch

**Comment by Aarqw12** [comment]
> 
 https://flash.android.com/  just not work in my devices ) error detection device ...

but I have find solution : - download factory rom - change slot of bootloader  & flash_all.sh

flash avbroot patch : flash boot.img , vendor_boot.img , vbmeta.img & avb custom key , now its work !

thanks for avbroot project !

**Comment by chenxiaolong** [comment]
Great, glad you got it working!

**Comment by Aarqw12** [comment]
> > yes replace vendor_boot , vendor_dlkm , dtbo , boot
> 
> OK, got it. I think that should be pretty simple to implement. I'll look into it soon.
> 
> > reboot , rom boot properly but its impossible to relock bootloader I get error
> > FAILED (remote: 'invalid android images, skip locking')
> 
> Hmm, I have no idea what would cause this. I searched around for the `invalid android images, skip locking` error and it seems that some people run into that even with the unmodified factory image.
> 
> I did see someone mention that restoring to stock with https://flash.android.com/ once resolved the issue (instead of factory image + `flash_all.sh`). Maybe that's worth a try?

Hi I have created simple script for wait its replace in payload.bin boot.img,vendor_boot.img,vendor_dlkm,dtbo.img I need. its only simple script I patch payload.bin before using avbroot I guess --argument prepatch can be modified in avbroot for allow that .

`import os
import shutil

def replace_files(payload_bin, boot_img, vendor_boot_img, vendor_dlkm_img, dtbo_img):
  """Replaces the boot.img, vendor_boot.img, vendor_dlkm.img, and dtbo.img files in the payload.bin file with the specified files.

  Args:
    payload_bin: The path to the payload.bin file.
    boot_img: The name of the boot.img file.
    vendor_boot_img: The name of the vendor_boot.img file.
    vendor_dlkm_img: The name of the vendor_dlkm.img file.
    dtbo_img: The name of the dtbo.img file.

  Raises:
    FileNotFoundError: If any of the specified files do not exist.
  """

  if not os.path.exists(payload_bin):
    raise FileNotFoundError("The payload.bin file does not exist.")

  with open(payload_bin, "rb") as payload_bin_file:
    contents = payload_bin_file.read()

  with open(boot_img, "rb") as boot_img_file:
    boot_img_data = boot_img_file.read()

  with open(vendor_boot_img, "rb") as vendor_boot_img_file:
    vendor_boot_img_data = vendor_boot_img_file.read()

  with open(vendor_dlkm_img, "rb") as vendor_dlkm_img_file:
    vendor_dlkm_img_data = vendor_dlkm_img_file.read()

  with open(dtbo_img, "rb") as dtbo_img_file:
    dtbo_img_data = dtbo_img_file.read()

  new_contents = contents[:]
  new_contents = new_contents.replace(boot_img_data, boot_img_data)
  new_contents = new_contents.replace(vendor_boot_img_data, vendor_boot_img_data)
  new_contents = new_contents.replace(vendor_dlkm_img_data, vendor_dlkm_img_data)
  new_contents = new_contents.replace(dtbo_img_data, dtbo_img_data)

  with open(payload_bin, "wb") as payload_bin_file:
    payload_bin_file.write(new_contents)

if __name__ == "__main__":
  payload_bin = os.path.join(os.getcwd(), "payload.bin")
  boot_img = "boot.img"
  vendor_boot_img = "vendor_boot.img"
  vendor_dlkm_img = "vendor_dlkm.img"
  dtbo_img = "dtbo.img"

  replace_files(payload_bin, boot_img, vendor_boot_img, vendor_dlkm_img, dtbo_img)

  print("The files have been replaced successfully.")`

**Comment by chenxiaolong** [comment]
Could you give #103 a try? With the new changes, you should be able to do this:

```bash
avbroot \
    --prepatched boot.img \
    --boot-partition @gki_kernel \
    --replace dtbo dtbo.img \
    --replace vendor_boot vendor_boot.img \
    --replace vendor_dlkm vendor_dlkm.img \
    # Remaining args...
```

`--rootless --replace boot boot.img` also works, but using `--prepatched` for the boot image is better because it verifies that the kernel version is compatible.

**Comment by Aarqw12** [comment]
> ```shell
> avbroot \
>     --prepatched boot.img \
>     --boot-partition @gki_kernel \
>     --replace dtbo dtbo.img \
>     --replace vendor_boot vendor_boot.img \
>     --replace vendor_dlkm vendor_dlkm.img \
> ```

Sure I have tested here the log error : Passphrase for avb.key: 
Passphrase for avb.key: 
***** Copying apex_info.pb *****
***** Copying care_map.pb *****
***** Patching payload.bin *****
***** Extracting boot, vbmeta, vbmeta_system, vbmeta_vendor from the payload *****
***** Patching boot, vendor_boot *****
Traceback (most recent call last):
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot.py", line 6, in <module>
    main.main()
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot/main.py", line 693, in main
    patch_subcommand(args)
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot/main.py", line 454, in patch_subcommand
    metadata = patch_ota_zip(args.input, temp, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot/main.py", line 360, in patch_ota_zip
    properties = patch_ota_payload(
                 ^^^^^^^^^^^^^^^^^^
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot/main.py", line 214, in patch_ota_payload
    future.result()
  File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot/main.py", line 198, in apply_patches
    boot.patch_boot(
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot/boot.py", line 376, in patch_boot
    footer, header, descriptors, image_size = avb._parse_image(image)
                                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot/../external/avb/avbtool.py", line 2775, in _parse_image
    h = AvbVBMetaHeader(image.read(AvbVBMetaHeader.SIZE))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/ada12/BUILD/avb/avbroot/avbroot/../external/avb/avbtool.py", line 2116, in __init__
    raise AvbError('Given image does not look like a vbmeta image.')
avbtool.AvbError: Given image does not look like a vbmeta image.

**Comment by Aarqw12** [comment]
> Could you give #103 a try? With the new changes, you should be able to do this:
> 
> ```shell
> avbroot \
>     --prepatched boot.img \
>     --boot-partition @gki_kernel \
>     --replace dtbo dtbo.img \
>     --replace vendor_boot vendor_boot.img \
>     --replace vendor_dlkm vendor_dlkm.img \
>     # Remaining args...
> ```
> 
> `--rootless --replace boot boot.img` also works, but using `--prepatched` for the boot image is better because it verifies that the kernel version is compatible.

seem my image dtbo,vendor_boot , vendor_dlkm is not a valid vbmeta image.

so  I have tried to add from avbtool.py the add_hash_footer but its return error in process avbroot patching : 
Traceback (most recent call last):
  File "/run/media/lcockx/BUILD/avb/avbroot/avbroot.py", line 6, in <module>
    main.main()
  File "/run/media/lcockx/BUILD/avb/avbroot/avbroot/main.py", line 693, in main
    patch_subcommand(args)
  File "/run/media/lcockx/BUILD/avb/avbroot/avbroot/main.py", line 454, in patch_subcommand
    metadata = patch_ota_zip(args.input, temp, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/lcockx/BUILD/avb/avbroot/avbroot/main.py", line 360, in patch_ota_zip
    properties = patch_ota_payload(
                 ^^^^^^^^^^^^^^^^^^
  File "/run/media/lcockx/BUILD/avb/avbroot/avbroot/main.py", line 223, in patch_ota_payload
    vbmeta.patch_vbmeta_image(
  File "/run/media/lcockx/BUILD/avb/avbroot/avbroot/vbmeta.py", line 158, in patch_vbmeta_image
    raise Exception(f'Unused public key overrides: {override_public_keys}')

**Comment by Aarqw12** [comment]
> Could you give #103 a try? With the new changes, you should be able to do this:
> 
> ```shell
> avbroot \
>     --prepatched boot.img \
>     --boot-partition @gki_kernel \
>     --replace dtbo dtbo.img \
>     --replace vendor_boot vendor_boot.img \
>     --replace vendor_dlkm vendor_dlkm.img \
>     # Remaining args...
> ```
> 
> `--rootless --replace boot boot.img` also works, but using `--prepatched` for the boot image is better because it verifies that the kernel version is compatible.

its working ! 

for documentation you should add in case image is not a vbmeta valid ( compiled from kernel source for ex only boot is vbmeta image ) its require for other image :

avb/avbroot/external/avb/avbtool.py add_hash_footer --image <image>.img --partition_name <name> --partition_size <size>

**Comment by Aarqw12** [comment]
ok its have created vbmeta corruption something is no patched properly in 

--replace dtbo dtbo.img
--replace vendor_boot vendor_boot.img
--replace vendor_dlkm vendor_dlkm.img 

* I have unlocked bootloader and reset vbmeta ...

**Comment by chenxiaolong** [comment]
> ok its have created vbmeta corruption something is no patched properly in
> 
> --replace dtbo dtbo.img --replace vendor_boot vendor_boot.img --replace vendor_dlkm vendor_dlkm.img
> 
>     * I have unlocked bootloader and reset vbmeta ...

I just pushed a change that might fix this. I accidentally messed up the dependency solver, so it might have patched `vbmeta_vendor` after `vbmeta` (instead of before).

**Comment by Aarqw12** [comment]
> > ok its have created vbmeta corruption something is no patched properly in
> > --replace dtbo dtbo.img --replace vendor_boot vendor_boot.img --replace vendor_dlkm vendor_dlkm.img
> > ```
> > * I have unlocked bootloader and reset vbmeta ...
> > ```
> 
> I just pushed a change that might fix this. I accidentally messed up the dependency solver, so it might have patched `vbmeta_vendor` after `vbmeta` (instead of before).

ok thanks I will re-test

**Comment by chenxiaolong** [comment]
> seem my image dtbo,vendor_boot , vendor_dlkm is not a valid vbmeta image.
>
> so I have tried to add from avbtool.py the add_hash_footer but its return error in process avbroot patching :

Oh, by the way, vendor_dlkm must use `add_hashtree_footer` instead of `add_hash_footer` because it's an ext4 filesystem (uses dm-verity).

I've never built a GKI before. Does the GKI build system have a way to automatically add the vbmeta footers?

**Comment by Aarqw12** [comment]
> > seem my image dtbo,vendor_boot , vendor_dlkm is not a valid vbmeta image.
> > so I have tried to add from avbtool.py the add_hash_footer but its return error in process avbroot patching :
> 
> Oh, by the way, vendor_dlkm must use `add_hashtree_footer` instead of `add_hash_footer` because it's an ext4 filesystem (uses dm-verity).
> 
> I've never built a GKI before. Does the GKI build system have a way to automatically add the vbmeta footers?

no in AOSP build environment its only for boot.img https://android.googlesource.com/kernel/gs/+/refs/heads/android-gs-pantah-5.10-t-qpr3-beta-3/build.config.gs101#72

google assume you use only in prebuild for build rom for AVB ...
