### ISSUE TITLE
Problem with signing OTA.zip

### ISSUE THREAD

**Issue by robinistkase** [chenxiaolong/avbroot#11]
Hello! I came here because I have a problem with signing the OTA image. I have tried using Ubuntu 22.04 and macOS Monterey but they either spit out an error or seem to work but also fail. I am using the December 2022 OTA zip directly from Google. 

Ubuntu shows: 
```
***** Skipping META-INF/com/android/metadata *****
***** Skipping META-INF/com/android/metadata.pb *****
***** Copying apex_info.pb *****
***** Copying care_map.pb *****
***** Patching payload.bin *****
Traceback (most recent call last):
  File "/media/COMPUTERNAME/USB/avbroot/avbroot.py", line 308, in <module>
    main()
  File "/media/COMPUTERNAME/USB/avbroot/avbroot.py", line 300, in main
    patch_subcommand(args)
  File "/media/COMPUTERNAME/USB/avbroot/avbroot.py", line 234, in patch_subcommand
    metadata = patch_ota_zip(
  File "/media/COMPUTERNAME/USB/avbroot/avbroot.py", line 181, in patch_ota_zip
    properties = patch_ota_payload(
  File "/media/COMPUTERNAME/USB/avbroot/avbroot.py", line 63, in patch_ota_payload
    version, manifest, blob_offset = ota.parse_payload(f_in)
  File "/media/COMPUTERNAME/USB/avbroot/avbroot/ota.py", line 50, in parse_payload
    manifest = update_metadata_pb2.DeltaArchiveManifest()
AttributeError: module 'update_metadata_pb2' has no attribute 'DeltaArchiveManifest'

```
macOS simply shows:
```
File "avbroot.py", line 128
zipfile.ZipFile(f_zip_in, 'r') as z_in
                                         ^
SyntaxError: invalid syntax
```
I have no idea if this script works between operating systems or if I was supposed to use the factory image instead of the OTA zip. Both have java, python3, and all of the other dependencies that are required to run this script. Both the keys and the Magisk APK were both placed inside the avbroot folder and I have also made sure to download the repo through git.

**Comment by chenxiaolong** [comment]
Hello! Hmm, the Ubuntu error seems like Python is using a different `update_metadata_pb2.py` file than expected. Can you post the output of this?
```bash
python3 -c 'import avbroot.external; import update_metadata_pb2; print(update_metadata_pb2.__file__)'
```
It should point to a file inside the git repo, like:
```
<path to git repo>/avbroot/../external/update_engine/scripts/update_payload/update_metadata_pb2.py
```

As for the macOS error, I think the python3 version might be too old. Installing the latest python3 from homebrew should resolve that. (I haven't personally tested on macOS because I don't have a Mac, but avbroot shouldn't have any Linux'ism in it.)

>  if I was supposed to use the factory image instead of the OTA zip

Using the OTA was correct.

**Comment by robinistkase** [comment]
Got the log right here, unfortunately brew didn't work :( 

**inside of repo folder**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/COMPUTERNAME/Desktop/avbroot/avbroot/../external/update_engine/scripts/update_payload/update_metadata_pb2.py", line 10, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name 'symbol_database' from 'google.protobuf' (/home/mofobitc/.local/lib/python3.10/site-packages/google/protobuf/__init__.py)

```

**Comment by chenxiaolong** [comment]
Hmm, if I had to guess, there's probably something in `~/.local/lib/python3.10` that's conflicting. Can you try temporarily moving/renaming that folder?

I tried setting up an Ubuntu 22.04 VM and running:
```bash
sudo apt install python3-protobuf openssl openjdk-17-jdk-headless
```
I was able to patch the Pixel 7 Pro OTA with:
```bash
python3 avbroot.py patch --input ~/Downloads/Pixel7Pro/cheetah-ota-tq1a.230105.002-0c8fdd0d.zip --privkey-avb avb.key --privkey-ota ota.key --cert-ota ota.crt --magisk ~/git/Magisk/out/app-debug.apk
```

**Comment by robinistkase** [comment]
Ended up doing a full reinstall of Ubuntu. Fixed the problem and is now working perfectly. Thanks for your help!
