### ISSUE TITLE
Magisk asks for Additional setup after fresh patched OTA sideload

### ISSUE THREAD

**Issue by archandanime** [chenxiaolong/avbroot#116]
Device: Pixel 4 XL(coral)
Magisk version: v26.1
LineageOS build: lineage-20.0-20230709-nightly-coral-signed.zip
avbroot version: lastest

I installed patched LineageOS OTA on both A and B slots with these steps:

1. Unlock bootloader

```bash
> fastboot flashing unlock
```

2. Flash factory image

```bash
> ./flash-all.sh
```

3. Erase userdata partition

```bash
> fastboot -w
```

4. Flash avb_custom_key partition with my custom avb key

```bash
> fastboot erase avb_custom_key
> fastboot flash avb_custom_key signing-keys/avb_pkmd.bin
```

5. Flash boot partition with extracted boot image from extracted patched OTA

```bash
> fastboot flash boot_a lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.extracted/boot.img
> fastboot --set-active=a
```

6. Reboot to recovery from bootloader

7. Sideload patched OTA(Current boot slot:a)

```bash
> adb sideload output/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.zip
```

8. Reboot to recovery from recovery

Sideload patched OTA on the other slot(Current boot slot:b)

```bash
> adb sideload output/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.zip
```

9. Reboot to system from recovery

Using both methods: patching with --magisk-preinit-device metadata(which is what Magisk uses when I patch stock LineageOS boot image using Magisk app) and --prepatched(with patch LineageOS boot image)
After doing all these step Magisk still asks for Additional setup. Root works fine with apps but Magisk modules can't be installed(results in errors) without Additional setup. If I let Magisk patch boot partition, it would break verified boot.
I speculate it's avbroot's issue. If any additional log is needed, please let me know.

**Comment by archandanime** [comment]
Actually doesn't re-patch boot image during "Additional setup", it was my bad. Everything works flawlessly! Closing the issue.

**Comment by chenxiaolong** [comment]
No worries! Yep, the additional setup isn't related to the boot image at all. It's checking whether there are missing Magisk files in `/data/adb/magisk` or if they have the wrong/old versions (https://github.com/topjohnwu/Magisk/blob/4caed73fe0e9f68f500f76015b99f614109412d6/app/src/main/res/raw/manager.sh#L9-L22). When you click OK for the additional setup, it cleans out `/data/adb/magisk` and copies the new Magisk files into it (https://github.com/topjohnwu/Magisk/blob/4caed73fe0e9f68f500f76015b99f614109412d6/app/src/main/res/raw/manager.sh#L42-L50).
