### ISSUE TITLE
Magisk patched LineageOS OTA sideload failed

### ISSUE THREAD

**Issue by archandanime** [chenxiaolong/avbroot#117]
Device: Pixel 4 XL(coral)
Magisk version: v26.1
LineageOS build: lineage-20.0-20230709-nightly-coral-signed.zip
avbroot version: lastest

Yesterday again I decided to flash LineageOS patched OTA again and went over these steps:

1. Flash factory image and avb_custom_key
```bash
> fastboot flashing unlock
> ./flash-all.sh
> fastboot erase avb_custom_key
> fastboot flash avb_custom_key signing-keys/avb_pkmd.bin
```

2. Flash boot_a with extracted boot image from patched OTA:
```
> fastboot flash boot_a lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.extracted/boot.img
> fastboot --set-active=a
```

3. Reboot to recovery and sideload patched LineageOS OTA:

```bash
adb sideload output/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.zip
```

It resulted in the error:

```
Finding update package...
Verifying update package...
Update package package verification took 22.4 s (result 0).
Installing update...
Step 1/2
Error applying update: 15 (ErrorCode:kNewRootfsVerificationError)
ERROR: recovery: Error in /sideload/package.zip (status 1)

Install completed with status 1.
Installation aborted.
```

I took a look at /tmp/recovery.log
```
[   28.382733] update_engine_sideload I 06-13 11:07:39   586   586] [INFO:delta_performer.cc(269)] PartitionInfo new product sha256: 4848E11EBA711E3B154412D610B0C247309F9B0C83C12596DEF48049C9710F19 size: 1275256832
...
[  160.442450] Partition: product
[  160.442451]   source_size: 0
[  160.442451]   source_path: 
[  160.442452]   source_hash: 
[  160.442453]   target_size: 1275256832
[  160.442454]   target_path: /dev/block/dm-2
[  160.442455]   target_hash: 4848E11EBA711E3B154412D610B0C247309F9B0C83C12596DEF48049C9710F19
[  160.442456]   run_postinstall: false
[  160.442457]   postinstall_path: 
[  160.442458]   readonly_target_path: /dev/block/dm-2
[  160.442458]   filesystem_type: 
...
[  160.769303] update_engine_sideload I 06-13 11:09:51   586   586] [INFO:filesystem_verifier_action.cc(329)] Hashing partition 8 (product) on device /dev/block/dm-2
[  160.769671] update_engine_sideload I 06-13 11:09:51   586   586] [INFO:filesystem_verifier_action.cc(380)] Verity writes disabled on partition product
[  162.963519] update_engine_sideload I 06-13 11:09:53   586   586] [INFO:filesystem_verifier_action.cc(435)] Hash of product: A3D476FB10BA9AF94DB28622956A0CA229BFD68A157842A4D761FD158E26E04B
[  162.963550] update_engine_sideload E 06-13 11:09:53   586   586] [ERROR:filesystem_verifier_action.cc(441)] New 'product' partition verification failed.
[  163.028101] update_engine_sideload I 06-13 11:09:53   586   586] [INFO:action_processor.cc(116)] ActionProcessor: finished FilesystemVerifierAction with code ErrorCode::kNewRootfsVerificationError
```

I checked product image from extracted patched OTA sha256:
```bash
[squid@arch ~/avbroot-Pixel4XL/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.extracted-all/extracted_20230714_093029]
> sha256sum product.img 
4848e11eba711e3b154412d610b0c247309f9b0c83c12596def48049c9710f19  product.img
```

I'm not sure this is because the product image was written incorrectly into the phone that caused the issue. This sometimes happened in the past few days when I sideloaded but it worked after I tried re-sideloading several times it worked, the results were inconsistent.
Strangely, sideloading in recovery from boot image with KernelSU never ever failed. But LineageOS recovery now keeps showing this error even I sideloaded a dozen of times.
Because KernelSU boot image is quite buggy, I finally ended up with sideloading Magisk patched LineageOS from KernelSU patched recovery mode. However, if I lock bootloader now I can't sideload again because sideload failed as I mentioned above.
Do you have any suggestion?

**Comment by chenxiaolong** [comment]
Hmm, interesting. I've never seen `kNewRootfsVerificationError` before. I'll take a look at the LineageOS code and see if I can any clues.

**Comment by chenxiaolong** [comment]
It looks like LineageOS is using the exact same code as AOSP for the checksum verification. There's nothing fancy about it--it is indeed just checking a simple sha256sum on the partition.

I did a quick check to make sure nothing is wrong in the patching process. `product` is not touched and has the same checksum as in your output:

```
$ avbroot patch <...> --input lineage-20.0-20230709-nightly-coral-signed.zip --magisk ~/git/github/Magisk/out/app-debug.apk --magisk-preinit-device metadata --clear-vbmeta-flags
$ avbroot extract --input lineage-20.0-20230709-nightly-coral-signed.zip --directory original --all
$ avbroot extract --input lineage-20.0-20230709-nightly-coral-signed.zip.patched --directory patched --all
$ sha256sum original/product.img patched/product.img
4848e11eba711e3b154412d610b0c247309f9b0c83c12596def48049c9710f19  original/product.img
4848e11eba711e3b154412d610b0c247309f9b0c83c12596def48049c9710f19  patched/product.img
```

This seems suspiciously like the flash storage hardware is failing to me. On one of my old Nexus devices, failing storage caused writes to succeed, but reads would return random/corrupted data. But if that's the case, I can't explain why KernelSU's boot image would prevent the issue from happening.

Does `/tmp/recovery.log` show the same bad checksum (`A3D476FB10BA9AF94DB28622956A0CA229BFD68A157842A4D761FD158E26E04B`) every time it fails?

---

On the Pixel 4 series, I believe `product` is one of the "dynamic partitions" inside the "real" `super` partition. To rule out the issue being caused by a corrupted `super`, can you unlock the bootloader and try:

```
fastboot wipe-super
```

and then try flashing again?

**Comment by archandanime** [comment]
I tried sideloading 5 times without rebooting in patched LineageOS recovery:
```
> adb shell cat /tmp/recovery.log | grep "Hash of product"
[  162.107864] update_engine_sideload I 06-14 12:46:00   585   585] [INFO:filesystem_verifier_action.cc(435)] Hash of product: 659C1CE3AEBDCC1FEBC1442AA5463F6B97CCCC185926BAD12EF65EB1EF4B19A2
[  329.408773] update_engine_sideload I 06-14 12:48:48   661   661] [INFO:filesystem_verifier_action.cc(435)] Hash of product: 4848E11EBA711E3B154412D610B0C247309F9B0C83C12596DEF48049C9710F19
[  520.847943] update_engine_sideload I 06-14 12:51:59   753   753] [INFO:filesystem_verifier_action.cc(435)] Hash of product: FB9D7D2719604B2DD12EB193F2984264259A1971909899AB73027E133278322F
[  708.800607] update_engine_sideload I 06-14 12:55:07   829   829] [INFO:filesystem_verifier_action.cc(435)] Hash of product: 4848E11EBA711E3B154412D610B0C247309F9B0C83C12596DEF48049C9710F19
[  888.776508] update_engine_sideload I 06-14 12:58:07   904   904] [INFO:filesystem_verifier_action.cc(435)] Hash of product: 4848E11EBA711E3B154412D610B0C247309F9B0C83C12596DEF48049C9710F19
```

Every sideload, if the checksum was `4848e11eba711e3b154412d610b0c247309f9b0c83c12596def48049c9710f19`, my phone showed the installation succeeded.
The last sideload was succeeded, I rebooted to recovery and it booted up on the opposite slot!


-------------------

Then I unlocked the bootloader and flashed super:
```
> fastboot flashing unlock
OKAY [  0.095s]
> fastboot wipe-super super_empty.img 
Sending 'super' (392 KB)                           OKAY [  0.140s]
Writing 'super'                                    OKAY [  0.121s]
Finished. Total time: 0.566s

```
Then I flashed boot_a with patched LineageOS boot image, changed slot:
```
> fastboot flash boot_a lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.extracted/boot.img
> fastboot --set-active=a
```
Then I rebooted to recovery(slot a) and tried sideloading 5 times:
- 1st sideload: it rebooted to recovery(to same slot) mid-sideloading last message on phone screen was: Step 1/2, I wasn't able to grab any recovery log.
```
> adb sideload output/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.zip
serving: 'output/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.zip'  (~47%)    adb: failed to read command: Success
```
- 2nd-5th sideload: same results and behaviors

The phone is 128GB Pixel 4 XL model and I it was not written often before I tried avbroot. I don't know much how wear out the memory chip was.

**Comment by archandanime** [comment]
When I sideloaded from kernelSU recovery mode:
Wiped `super` and flashed boot with KernelSU boot image:
```
> fastboot wipe-super super_empty.img 
> fastboot flash boot_a lineage-20.0-20230709-nightly-coral-signed_coral_kernelsu_0.6.2_PATCHED.extracted/boot.img 
> fastboot --set-active=a
```
Rebooted to recovery(KernelSU recovery mode) and sideloaded 5 times, they all succeeded:
```
> adb sideload output/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.zip
Total xfer: 2.00x
```

During sideloading, the percentage went up gradually to and ended at 94% as it finished, sometimes it got stuck at some percentages for a few seconds, unlike going up gradually then stuck at 47% in LineageOS recovery.
Mid-sideloading looks like this:

```
serving: 'output/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.zip'  (~72%)
```
What the screen showed was the same as when I successfully sidedloaded with LineageOS recovery.
I did all the flashing/patching from Arch Linux if it's relevant.
```
> adb --version
Android Debug Bridge version 1.0.41
Version 34.0.1-android-tools
Installed as /usr/bin/adb
```
KernelSU boot.img image is from here: https://github.com/creamlike1024/android-msm-coral-4.14-android13/releases/tag/0.6.2

**Comment by archandanime** [comment]
I also made an attempt with stock OTA(from Google) for test if stock recovery succeeds sideloading patched LineageOS OTA.
Patched stock OTA with avbroot rootless:
```
> python avbroot/avbroot.py patch \
--input input/coral-ota-tp1a.221005.002.b2-9e04f1c9.zip \
--privkey-avb signing-keys/avb.key \
--privkey-ota signing-keys/ota.key \
--cert-ota signing-keys/ota.crt \
--clear-vbmeta-flags \
--rootless \
--output output/coral-ota-tp1a.221005.002.b2-9e04f1c9_rootless_PATCHED.zip
```
Extracted patch stock OTA:
```
> mkdir coral-ota-tp1a.221005.002.b2-9e04f1c9_rootless_PATCHED.extracted
> python avbroot/avbroot.py extract \
--input output/coral-ota-tp1a.221005.002.b2-9e04f1c9_rootless_PATCHED.zip \
--directory coral-ota-tp1a.221005.002.b2-9e04f1c9_rootless_PATCHED.extracted
```
Flashed boot partition with extracted boot image from patched stock OTA:
```
> fastboot flash boot_a coral-ota-tp1a.221005.002.b2-9e04f1c9_rootless_PATCHED.extracted/boot.img 
> fastboot --set-active=a
```
Rebooted to recovery and sideloaded 5 times:
```
> adb sideload output/lineage-20.0-20230709-nightly-coral-signed_Magisk-v26.1_PATCHED.zip
```
The phone screen messages are the same as in KernelSU boot recovery: all succeed, the percentage went up gradually to and ended at 94% as it finished,

**Comment by archandanime** [comment]
Then I made another a attempt to sideload vanilla LineageOS OTA from vanilla boot image recovery:
```
> fastboot flash boot_a boot_vanilla-LineageOS.img
> fastboot --set-active=a
```
```
> adb sideload input/lineage-20.0-20230709-nightly-coral-signed.zip
```
Sideloading failed with the same error on my phone screen, but recovery.log showed the difference:
```
> adb shell cat /tmp/recovery.log | grep -e "partition verification failed"
[  180.208910] update_engine_sideload E 06-14 15:01:35   588   588] [ERROR:filesystem_verifier_action.cc(441)] New 'system' partition verification failed.
[  388.215009] update_engine_sideload E 06-14 15:05:03   627   627] [ERROR:filesystem_verifier_action.cc(441)] New 'system_ext' partition verification failed.
[  565.869714] update_engine_sideload E 06-14 15:08:01   664   664] [ERROR:filesystem_verifier_action.cc(441)] New 'vendor' partition verification failed.
[  905.002235] update_engine_sideload E 06-14 15:13:40   716   716] [ERROR:filesystem_verifier_action.cc(441)] New 'system_ext' partition verification failed.
[ 1151.291018] update_engine_sideload E 06-14 15:17:46   765   765] [ERROR:filesystem_verifier_action.cc(441)] New 'product' partition verification failed.
```

**Comment by archandanime** [comment]
I re-installed patched LineageOS several times more, this the error is:
```
Error applying update: 7 (ErrorCode:kInstallDeviceOpenError)
```
which `recovery.log` shows:
```
[  632.806078] update_engine_sideload I 06-14 17:27:02   754   754 fs_mgr.cpp:838] [libfs_mgr]__mount(source=/dev/block/by-name/metadata,target=/metadata,type=ext4)=0: Success
[  632.806259] libc: Unable to set property "ro.boottime.init.mount.metadata" to "1": error code: 0xb
[  632.806498] update_engine_sideload I 06-14 17:27:02   754   754] [INFO:dynamic_partition_control_android.cc(781)] Erasing AVB footer of system_other partition before update.
[  632.806546] update_engine_sideload E 06-14 17:27:02   754   754 fs_mgr_fstab.cpp:706] [libfs_mgr]ReadFstabFromFile(): failed to read file: '/product/etc/fstab.postinstall': No such file or directory
[  632.806579] update_engine_sideload W 06-14 17:27:02   754   754] [WARNING:dynamic_partition_control_android.cc(655)] Cannot read fstab from /product/etc/fstab.postinstall: No such file or directory (2)
[  632.806604] update_engine_sideload I 06-14 17:27:02   754   754] [INFO:dynamic_partition_control_android.cc(682)] AVB is not enabled on system_other. Skip erasing.
[  632.807672] update_engine_sideload I 06-14 17:27:02   754   754] [INFO:dynamic_partition_control_android.cc(347)] Loaded metadata from slot B in /dev/block/bootdevice/by-name/super
[  632.807960] update_engine_sideload I 06-14 17:27:02   754   754 snapshot.cpp:177] Wait for merge (if any) before beginning a new update.
[  632.808000] update_engine_sideload I 06-14 17:27:02   754   754 snapshot.cpp:1047] CheckMergeState for snapshots returned: 5
[  632.809216] update_engine_sideload I 06-14 17:27:02   754   754 snapshot.cpp:1019] ProcessUpdateState handling state: 5
[  632.809240] update_engine_sideload I 06-14 17:27:02   754   754 snapshot.cpp:179] Merged with state = 5
[  632.809422] update_engine_sideload E 06-14 17:27:02   754   754 snapshot.cpp:197] An update is already in progress, cannot begin a new update
[  632.809452] update_engine_sideload E 06-14 17:27:02   754   754] [ERROR:dynamic_partition_control_android.cc(966)] Cannot begin new update.
[  632.809480] update_engine_sideload I 06-14 17:27:02   754   754] [INFO:dynamic_partition_control_android.cc(522)] PrepareSnapshotPartitionsForUpdate failed in recovery. Attempt to overwrite existing partitions if possible
[  632.809518] update_engine_sideload E 06-14 17:27:02   754   754 snapshot.cpp:209] Cannot cancel update after it has completed or started merging
[  632.809543] update_engine_sideload E 06-14 17:27:02   754   754] [ERROR:dynamic_partition_control_android.cc(538)] snapshot_->CancelUpdate() failed.
[  632.809568] update_engine_sideload E 06-14 17:27:02   754   754] [ERROR:delta_performer.cc(747)] Unable to initialize partition metadata for slot A
[  632.809600] update_engine_sideload E 06-14 17:27:02   754   754] [ERROR:download_action.cc(227)] Error ErrorCode::kInstallDeviceOpenError (7) in DeltaPerformer's Write method when processing the received payload -- Terminating processing
```
Reboots don't help with this issue
You could be very right that the flash chip is a bit corrupted. But I can't explain why stock boot recovery and KernelSU boot recovery succeeded either :((

**Comment by pascallj** [comment]
It might be a long shot, but on my old phone I have had flashing errors and corrupted OS's when using the front USB ports on my desktop. I am not sure if there are checksums or error correction in place to catch these things nowadays, but it might be worth trying with a different USB port or cable if corruption is the concern.

**Comment by archandanime** [comment]
Thank you for the suggestion.
I re-attempted various flashing/sideloading with another cable on another USB port and kept my finger crossed but the results were the same. It only took a bit more time on a 2.0 USB cable sadly.

**Comment by archandanime** [comment]
In my final attempt, I flashed factory image then flashed LineageOS with MicroG [lineage-20.0-20230703-microG-coral.zip ](https://download.lineage.microg.org/coral/)
I tried sideloading 5 times, it all succeeded :))
```
> adb sideload output/lineage-20.0-20230703-microG-coral_Magisk-v26.1_PATCHED.zip
Total xfer: 1.00x        
```
Then I rebooted to the opposite slot and sideloaded 5 times, there was no error at all!
I speculate it was all LineageOS's recovery issues.
So I guess I'm sticking with LineageOS with MicroG for now and I'm happy with the result.

**Comment by chenxiaolong** [comment]
Thanks for the extensive testing. Really wonder what's wrong with regular LineageOS...

I compared the official `20230709` boot image with the MicroG `20230703` boot image using diffoscope and found the following differences ([boot_diff.html.gz](https://github.com/chenxiaolong/avbroot/files/12062821/boot_diff.html.gz)):

* Kernel is different
* [Doesn't matter] Different version numbers and timestamps in `.prop` files
* [Doesn't matter] Minor compression differences in `.png` images
* [Doesn't matter] Different original signing certs in `<ramdisk>/system/etc/security/otacerts.zip`
* [Doesn't matter] `<ramdisk>/system/lib64/librecovery_ui.so` contains [a change to support screen rotation](https://github.com/LineageOS/android_bootable_recovery/commit/3a726d506c3d5e1e77f9ff242428384f035887aa). This library isn't loaded by `update_engine_sideload`.

Everything else is identical.

If you don't mind testing more, could you try using official LineageOS with the MicroG kernel?

```bash
mkdir boot_microg boot_official

pushd boot_microg
python /path/to/avbroot/extra/bootimagetool.py unpack <microg boot.img file>
popd

pushd boot_official
python /path/to/avbroot/extra/bootimagetool.py unpack <official boot.img file>
mv ../boot_microg/kernel.img .
python /path/to/avbroot/extra/bootimagetool.py pack boot_modified.img
popd

python avbroot.py patch <...> --replace boot boot_official/boot_modified.img
```

If that works, then I guess there must be a bug in the official 20230709 lineageos kernel. The only changes I saw between 20230703 and 20230709 in the kernel are related to wifi and bluetooth drivers. I can't imagine those impacting the flashing process...

---

> the percentage went up gradually to and ended at 94% as it finished,

I frequently encounter this as well, though it's usually 97% for my device (Pixel 7 Pro). No difference if I use Arch's `34.0.1`, Fedora's `33.0.3p1`, or Google Android SDK's `34.0.1`. The progress counter display is likely just buggy. I don't think there's any risk of data not being sent. Otherwise, signature verification (which applies to the entire file) would fail.

**Comment by archandanime** [comment]
> If you don't mind testing more, could you try using official LineageOS with the MicroG kernel?

```
> fastboot flash boot_a lineage-20.0-20230709-nightly-coral-signed_microG-kernel_Magisk-v26.1_PATCHED.extracted/boot.img 
> adb sideload lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip
```
This all failed in 5 sideload attempts. It rebooted to same slot recovery 3 times, failed with `kNewRootfsVerificationError` twice, which my terminal showed:
```
> adb sideload lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip
serving: 'lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip'  (~47%)    adb: failed to read command: Success
> adb sideload lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip
Total xfer: 1.00x                                                                                   
> adb sideload lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip
Total xfer: 1.00x                                                                                   
> adb sideload lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip
serving: 'lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip'  (~47%)    adb: failed to read command: Success
> adb sideload lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip
serving: 'lineage-20.0-20230703-microG-coral_Magisk-v26.1_microG-kernel_PATCHED.zip'  (~47%)    adb: failed to read command: Success
```

> This makes me wonder if the official 20230703 release would work too.

I tried with unpatched `lineage-20.0-20230702-nightly-coral-signed.zip` and it failed the same way.

---------------
It really looks like flash memory issue but when I flashed LineageOS MicroG 20230703 recovery again the results were the same as before:

> In my final attempt, I flashed factory image then flashed LineageOS with MicroG [lineage-20.0-20230703-microG-coral.zip ](https://download.lineage.microg.org/coral/) I tried sideloading 5 times, it all succeeded :))
> 
> ```
> > adb sideload output/lineage-20.0-20230703-microG-coral_Magisk-v26.1_PATCHED.zip
> Total xfer: 1.00x        
> ```
> 
> Then I rebooted to the opposite slot and sideloaded 5 times, there was no error at all! I speculate it was all LineageOS's recovery issues. So I guess I'm sticking with LineageOS with MicroG for now and I'm happy with the result.
> 
> I tried digging into the difference between LineageOS and LineageOS for MicroG recovery sideload difference but hit a dead end as they are the same:
> 
> ```
> 82b4b30410d7acabb0dac0a79bd716e99205ebdf90f271800d06bce911ae761ea1f2f54de03f64283736379e13e7097f765d8f1662c2b3ac69e53a976a754916  update_engine_sideload_LineageOS
> 82b4b30410d7acabb0dac0a79bd716e99205ebdf90f271800d06bce911ae761ea1f2f54de03f64283736379e13e7097f765d8f1662c2b3ac69e53a976a754916  update_engine_sideload_LineageOS-MicroG
> ```
![LineageOS MicroG 20230702](https://github.com/chenxiaolong/avbroot/assets/36922812/d115036c-0493-4332-b873-543be4a2946c)

![LineageOS 20230809](https://github.com/chenxiaolong/avbroot/assets/36922812/d97d3067-f011-473d-a0b2-84a47e425014)

**Comment by chenxiaolong** [comment]
Thanks again for the extensive testing, including the unpatched LineageOS. At this point, I'm out of ideas. I have no idea what might be causing this.

**Comment by archandanime** [comment]
Thank you for the suggestions and experience! The source of the issue is unknown but I still learned a lot!
I'm keeping the the bootloader unlocked in case there is a real hardware issue that can suddenly make the phone unbootable, and I'll buy a new phone soon.
Closing the issue.
