### ISSUE TITLE
Android 14 support

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/avbroot#121]
I'm planning on day 1 support for Android 14 in both avbroot and Custota. It's very likely the current code will just work as-is. Unlike the Java parts of Android, Google doesn't withhold changes to AOSP repos for the OTA-related components. I haven't seen anything in the `master` branches that would cause trouble.

But I'll open this issue to keep track of problems in case any come up.

**Comment by archandanime** [comment]
On my Pixel 7a(lynx) I installed Android 14 Beta 5.2 with [OTA zip](lynx_beta-upb5.230623.006-factory-de16f61a.zip) from [Google](https://developer.android.com/about/versions/14/download) with KernelSU's [android13-5.10.177_2023-06-boot.img](https://github.com/tiann/KernelSU/releases/tag/v0.6.7). The update took 45 minutes with no issue, after that everything worked fine, Custota app failed to start several times but a reboot fixed it(no logcat unfortunately)

**Comment by chenxiaolong** [comment]
Just finished looking through the AOSP commits. There's nothing new for AVB, boot images, FEC, payloads, or OTA zips. All versions of avbroot (including the old python version) should work as-is.

(Although it's interesting that AOSP is now running into similar problems as the python avbroot version did where it's hacky/annoying to use certain components as libraries. They're starting to refactor some of the code to make it more modular :slightly_smiling_face:)
