### ISSUE TITLE
Feature request: oemunlockonboot as a pre-built Magsik module

### ISSUE THREAD

**Issue by jschbrt** [chenxiaolong/avbroot#123]
Hey, since I don't currently have AndroidSDK installed on my machine, I wanted to ask if you could provide a pre-built magisk module for it like you did for the clearotacerts module which I am currently using.
Thanks for considering!

**Comment by chenxiaolong** [comment]
Sure! I've added a GitHub Actions workflow in #124 to automatically build and archive the modules on every commit.

You can find the download link in the documentation at: . Unfortunately, GitHub only allows downloading while logged in, but hopefully it's better than nothing.

**Comment by jschbrt** [comment]
Wow, thanks for the quick reply and thank you for this commit. So kind of you! 🙂
