### ISSUE TITLE
Suggestion: Mention Custota on avbroot README.md description

### ISSUE THREAD

**Issue by archandanime** [chenxiaolong/avbroot#131]
Thank you for recent huge improvements in avbroot code to make it so much faster.
I suggesting mentioning [Custota](https://github.com/chenxiaolong/Custota) on avbroot README.md like Custota does on its README.md to gain more attention. They are supposed to be a pair ;) I think.

**Comment by xabolcs** [comment]
There was a commit, exactly for that: bbd547e5e4a2e6502a270510889d595ec7f38c64

**Comment by archandanime** [comment]
Oh I didn't see that. Thank you for mentioning!
