### ISSUE TITLE
Unknown issue with the Rust variant

### ISSUE THREAD

**Issue by FR46M3N7-P4R71CL3** [chenxiaolong/avbroot#151]
Hi,

I tried signing an OTA and got the below error. The older Python version seems to work just fine though, with the same command and with the same ota.

avbroot ota patch --input ota.zip --privkey-avb avb.key --privkey-ota ota.key --cert-ota ota.crt --prepatched kernelsu.img --boot-partition @gki_kernel
Enter passphrase for "avb.key":
Enter passphrase for "ota.key":
[*] Replacing zip entry: META-INF/com/android/otacert
[*] Copying zip entry: apex_info.pb
[*] Copying zip entry: care_map.pb
[*] Patching zip entry: payload.bin
[*] Extracting from original payload: vbmeta
[*] Extracting from original payload: vbmeta_vendor
[*] Extracting from original payload: vendor_boot
[*] Extracting from original payload: vbmeta_system
[*] Extracting from original payload: boot
[*] Patching boot images: boot, vendor_boot
Error: Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to patch boot image: boot
    2: I/O error
    3: The system cannot find the file specified. (os error 2)

**On the older Python version:**

python avbroot\avbroot.py patch --input ota.zip --privkey-avb avb.key --privkey-ota ota.key --cert-ota ota.crt --prepatched kernelsu.img --boot-partition @gki_kernel
Passphrase for avb.key:
Passphrase for ota.key:
***** Copying apex_info.pb *****
***** Copying care_map.pb *****
***** Patching payload.bin *****
***** Extracting boot, vbmeta, vbmeta_system, vbmeta_vendor, vendor_boot from the payload *****
***** Patching boot, vendor_boot *****
***** Building vbmeta *****
***** Updating OTA payload to reference new boot, vbmeta, vendor_boot *****
***** Patching payload_properties.txt *****
***** Replacing META-INF/com/android/otacert *****
***** Generating META-INF/com/android/metadata and META-INF/com/android/metadata.pb *****
***** Verifying metadata offsets *****
***** Completed after 88.3s *****

Not sure what's causing the error. Both are on a Windows machine.

**Update:** I tried flashing the Python variant signed ROM and now the device is hard-bricked! Tried on a Google Pixel with a September 2023 Patched Factory Image. I used to flash other OTA updates in the past without issues. The update was adb sideloaded post signing via factory recovery and went without errors.
**Update 2:** The brick is unlikely to do anything with the tool, maybe I flashed the wrong version of kernelsu. The original issue still exists.

**Comment by chenxiaolong** [comment]
Thanks for the report. Could you post a link to the exact OTA and KernelSU image you're using? I can't seem to reproduce this with the Pixel 7 Pro's September OTA and KernelSU's `android13-5.10.157_2023-03-boot-lz4.img` image.

**Comment by FR46M3N7-P4R71CL3** [comment]
Thanks for the revert. It looks like I'm unable to reproduce the issue now, and everything seems to work. Earlier, when copy-pasting commands from the readme, even the --boot-partition command throws an error, likely something may have been miscopied or altered.

You may close this issue, once it is reproducible, I'll try to identify the root cause. Thank you.

**Comment by chenxiaolong** [comment]
Sounds good. If you run into this again, definitely feel free to reopen the issue.
