### ISSUE TITLE
Inconsistent Application Command

### ISSUE THREAD

**Issue by FR46M3N7-P4R71CL3** [chenxiaolong/avbroot#180]
Hi there,

With the application re-write to rust, the following command works:
`avbroot ota extract --input ota.zip --directory ./ --boot-only`

whereas, the following doesn't seem to work:
`avbroot ota magisk-info --image magisk_patched.img`

The issue lies with the syntax, and not with any paths or filenames. The correct equivalent of the command appears to be:
`avbroot magisk-info --image magisk_patched.img` (without the 'ota')

The readme refers to the use of the command with the 'ota'.

Either the readme must be changed to omit the syntax that includes 'ota' or the program must be updated to follow the generic 'avbroot ota' structure.

Thank you.

**Comment by chenxiaolong** [comment]
Thanks, that was a typo in the README (fixed in ca0e80521f32e42e70191a193f986eed7d8b7a68). The new command is `avbroot boot magisk-info`, but for compatibility, the old `avbroot magisk-info` will probably be kept around forever.
