### ISSUE TITLE
Problems signing/recovery Pixel Experience for Oneplus Nord

### ISSUE THREAD

**Issue by MrDuartePT** [chenxiaolong/avbroot#186]
I having problems signing the PE OTA image for Oneplus Nord this means i will need to use another custom rom our i can solve it by build the rom and enable vbmeta headers (if possible)

➜  Oneplus ./avbroot ota patch \
    --input PixelExperience_Plus_avicii-13.0-20231003-1348-OFFICIAL.zip \
    --privkey-avb ./custom-keys/avb.key \
    --privkey-ota ./custom-keys/ota.key \
    --cert-ota ./custom-keys/ota.crt --rootless
[*] Replacing zip entry: META-INF/com/android/otacert
[*] Copying zip entry: apex_info.pb
[*] Copying zip entry: care_map.pb
[*] Patching zip entry: payload.bin
[*] Extracting from original payload: vbmeta
[*] Extracting from original payload: vbmeta_system
[*] Extracting from original payload: recovery
[*] Patching boot images: recovery
[*] Patching vbmeta images: vbmeta
Error: Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: vbmeta header flags disable AVB 0x3

**Comment by pascallj** [comment]
Hi, please have a look at #60 and [Clearing vbmeta flags](https://github.com/chenxiaolong/avbroot#clearing-vbmeta-flags).

This might work for you as well.

**Comment by MrDuartePT** [comment]
Ok I will test later and let you know.
Thanks for the fast reponse👍

**Comment by MrDuartePT** [comment]
Can confirm that it works, thanks.

**Comment by MrDuartePT** [comment]
@pascallj this is kinda of topic but i also need to patch my twrp/OrangeFox Recovery

**Comment by chenxiaolong** [comment]
I wouldn't recommend using a custom recovery if possible. Almost anything you flash from a custom recovery would make the partition signatures invalid.

However, if you would like to do so anyway, you can add `--replace recovery /path/to/custom/recovery.img` to the patch command.

**Comment by MrDuartePT** [comment]
Well i will always sign my ota but i would like to still use OrangeFox

**Comment by MrDuartePT** [comment]
I getting a strange behaviour if a flash the extracted files the device boot fine but the recovery give me a black screen

**Comment by MrDuartePT** [comment]
@chenxiaolong I getting a strange behaviour if a flash the extracted files the device boot fine on PE but the recovery give me a black screen.
Both OrangeFox as the Pixel Experience recovery didnt try twrp but if a flash the unsigned recovery image it boots in to recovery fine

**Comment by MrDuartePT** [comment]
This output is expected? (using unsign recovery and everthing else sign):
```Nord:/ # dmesg | grep libfs_avb
[    2.449171] (1)[1:init][    2.449167]@1 init: [libfs_avb]Returning avb_handle with status: Success
[    2.450299] (1)[1:init][    2.450295]@1 init: [libfs_avb]: Error verifying vbmeta image: OK_NOT_SIGNED
[    2.450335] (1)[1:init][    2.450332]@1 init: [libfs_avb]Found unknown public key used to sign /system
[    2.450351] (1)[1:init][    2.450348]@1 init: [libfs_avb]Returning avb_handle for '/system' with status: VerificationError
[    2.451536] (1)[1:init][    2.451530]@1 init: [libfs_avb]Built verity table: '1 /dev/block/dm-7 /dev/block/dm-7 4096 4096 234780 234780 sha1 92f8d04b6b85b99c10ad1784381cb974896206d1 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-7 fec_roots 2 fec_blocks 236631 fec_start 236631 restart_on_corruption ignore_zero_blocks'
[    2.465337] (3)[1:init][    2.465330]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-8 /dev/block/dm-8 4096 4096 86750 86750 sha1 19daf5cd7bb360889c3c72b9bb6f4ba0d23ce0fb e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-8 fec_roots 2 fec_blocks 87435 fec_start 87435 restart_on_corruption ignore_zero_blocks'
[    2.470639] (3)[1:init][    2.470632]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-6 /dev/block/dm-6 4096 4096 407562 407562 sha1 74905fd3c824dbbca500138f68a615ddd0365ee4 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-6 fec_roots 2 fec_blocks 410773 fec_start 410773 restart_on_corruption ignore_zero_blocks'
[    2.475746] (3)[1:init][    2.475740]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-9 /dev/block/dm-9 4096 4096 209646 209646 sha1 3d97cb5d9f16a3d9ce2c2056ab8b3a2050646e5f e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-9 fec_roots 2 fec_blocks 211298 fec_start 211298 restart_on_corruption ignore_zero_blocks'
[    2.481295] (3)[1:init][    2.481288]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-5 /dev/block/dm-5 4096 4096 15444 15444 sha1 7a8c095c71489e62b242b7b137d099d1f36a4f68 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-5 fec_roots 2 fec_blocks 15566 fec_start 15566 restart_on_corruption ignore_zero_blocks'```

**Comment by chenxiaolong** [comment]
> I getting a strange behaviour if a flash the extracted files the device boot fine on PE but the recovery give me a black screen.
> Both OrangeFox as the Pixel Experience recovery didnt try twrp but if a flash the unsigned recovery image it boots in to recovery fine

Hmm, that's weird. Can you post the command you're running to patch the ROM + recovery? I'll test it on my end and compare the signed and unsigned recovery images to see if there's something weird going on. I can't really think of anything obvious--the only change avbroot does to that partition is update the certificate inside the recovery ramdisk's `system/etc/security/otacerts.zip` and then sign it.

> This output is expected [the frist line is equal to the Readme just worry about the /system]? (using unsign recovery and everthing else sign):

Is there any chance that the recovery might be modifying `/system`? Even mounting it as `rw` once will break the signatures. I've also seen some ROMs before that modify `/system` during boot. Hopefully that's not the case here because that'd be fundamentally incompatible with avbroot.

The signatures for all partitions seem to be valid when running:

```
avbroot ota verify -i PixelExperience_Plus_avicii-13.0-20231003-1348-OFFICIAL.zip
```

(If you want to run this command against a Pixel Experience OTA, you'll need #190 ([download](https://github.com/chenxiaolong/avbroot/actions/runs/6513311316?pr=190)), which isn't in a stable avbroot release yet.)

**Comment by MrDuartePT** [comment]
> > I getting a strange behaviour if a flash the extracted files the device boot fine on PE but the recovery give me a black screen.
> > Both OrangeFox as the Pixel Experience recovery didnt try twrp but if a flash the unsigned recovery image it boots in to recovery fine
> 
> Hmm, that's weird. Can you post the command you're running to patch the ROM + recovery? I'll test it on my end and compare the signed and unsigned recovery images to see if there's something weird going on. I can't really think of anything obvious--the only change avbroot does to that partition is update the certificate inside the recovery ramdisk's `system/etc/security/otacerts.zip` and then sign it.
> 
> > This output is expected [the frist line is equal to the Readme just worry about the /system]? (using unsign recovery and everthing else sign):
> 
> Is there any chance that the recovery might be modifying `/system`? Even mounting it as `rw` once will break the signatures. I've also seen some ROMs before that modify `/system` during boot. Hopefully that's not the case here because that'd be fundamentally incompatible with avbroot.
> 
> The signatures for all partitions seem to be valid when running:
> 
> ```
> avbroot ota verify -i PixelExperience_Plus_avicii-13.0-20231003-1348-OFFICIAL.zip
> ```
> 
> (If you want to run this command against a Pixel Experience OTA, you'll need #190 ([download](https://github.com/chenxiaolong/avbroot/actions/runs/6513311316?pr=190)), which isn't in a stable avbroot release yet.)

For flash I just using the same script of the readme I unpackaged the file using avbroot and then flash everything I will try again tomorrow but this time flash both particion a and b

**Comment by MrDuartePT** [comment]
I using the new version of avbroot you seen i gonna recreate the patched zips

**Comment by MrDuartePT** [comment]
I can also verify with new release the new patched zips have valid signatures:
```➜  Oneplus ./avbroot ota verify --input PixelExperience_Plus_avicii-13.0-Orangefox-noroot.zip --cert-ota custom-keys/ota.crt --public-key-avb custom-keys/avb_pkmd.bin
[*] Verifying whole-file signature
[*] Verifying payload
[*] Extracting partition images to temporary directory
[*] Extracting from the payload: abl, aop, bluetooth, boot, devcfg, dsp, dtbo, featenabler, hyp, imagefv, keymaster, logo, modem, odm, product, qupfw, recovery, storsec, system, system_ext, tz, uefisecapp, vbmeta, vbmeta_system, vendor, xbl, xbl_config
[*] Checking ramdisk's otacerts.zip
[*] Verifying AVB signatures
[*] vbmeta has a signed vbmeta header
[*] vbmeta_system has a signed vbmeta header
[*] Verifying hash tree descriptor for: odm
[*] Verifying hash tree descriptor for: system
[*] Verifying hash descriptor for: dtbo
[*] Verifying hash tree descriptor for: system_ext
[*] Verifying hash descriptor for: recovery
[*] Verifying hash tree descriptor for: vendor
[*] Verifying hash descriptor for: boot
[*] Verifying hash tree descriptor for: product
[*] Signatures are all valid!
➜  Oneplus ./avbroot ota verify --input PixelExperience_Plus_avicii-13.0-OrangeFox.zip --cert-ota custom-keys/ota.crt --public-key-avb custom-keys/avb_pkmd.bin
[*] Verifying whole-file signature
[*] Verifying payload
[*] Extracting partition images to temporary directory
[*] Extracting from the payload: abl, aop, bluetooth, boot, devcfg, dsp, dtbo, featenabler, hyp, imagefv, keymaster, logo, modem, odm, product, qupfw, recovery, storsec, system, system_ext, tz, uefisecapp, vbmeta, vbmeta_system, vendor, xbl, xbl_config
[*] Checking ramdisk's otacerts.zip
[*] Verifying AVB signatures
[*] vbmeta has a signed vbmeta header
[*] vbmeta_system has a signed vbmeta header
[*] Verifying hash tree descriptor for: vendor
[*] Verifying hash tree descriptor for: system
[*] Verifying hash descriptor for: dtbo
[*] Verifying hash tree descriptor for: system_ext
[*] Verifying hash tree descriptor for: odm
[*] Verifying hash descriptor for: recovery
[*] Verifying hash descriptor for: boot
[*] Verifying hash tree descriptor for: product
[*] Signatures are all valid!
➜  Oneplus```

**Comment by MrDuartePT** [comment]
Tomorrow I will flash and see if reports success and the recovery works.
Well probably if this go well I think I will try make a unofficial graphene os build for the Oneplus I have the vendor files from Pixel Experience that should work.

**Comment by chenxiaolong** [comment]
When you try again tomorrow, can you use #191 ([download](https://github.com/chenxiaolong/avbroot/actions/runs/6513768233?pr=191))? It might potentially fix the signed recovery black screen issue.

**Comment by MrDuartePT** [comment]
Ok I will use.

**Comment by MrDuartePT** [comment]
well i getting black screen if i flash recovery using the script but using fastboot it work i gonna flash the recovery seperate via fastboot and see if stop getting black screen.

**Comment by MrDuartePT** [comment]
dmesg produce with OrangeFox/PE recovery:
```
Nord:/ # dmesg | grep libfs_avb
[    2.105147] (3)[1:init][    2.105142]@3 init: [libfs_avb]Returning avb_handle with status: Success
[    2.106293] (3)[1:init][    2.106289]@3 init: [libfs_avb]: Error verifying vbmeta image: OK_NOT_SIGNED
[    2.106329] (3)[1:init][    2.106326]@3 init: [libfs_avb]Found unknown public key used to sign /system
[    2.106344] (3)[1:init][    2.106342]@3 init: [libfs_avb]Returning avb_handle for '/system' with status: VerificationError
[    2.107533] (3)[1:init][    2.107526]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-7 /dev/block/dm-7 4096 4096 234780 234780 sha1 92f8d04b6b85b99c10ad1784381cb974896206d1 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-7 fec_roots 2 fec_blocks 236631 fec_start 236631 restart_on_corruption ignore_zero_blocks'
[    2.120063] (3)[1:init][    2.120057]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-8 /dev/block/dm-8 4096 4096 86750 86750 sha1 19daf5cd7bb360889c3c72b9bb6f4ba0d23ce0fb e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-8 fec_roots 2 fec_blocks 87435 fec_start 87435 restart_on_corruption ignore_zero_blocks'
[    2.125275] (3)[1:init][    2.125269]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-6 /dev/block/dm-6 4096 4096 407562 407562 sha1 74905fd3c824dbbca500138f68a615ddd0365ee4 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-6 fec_roots 2 fec_blocks 410773 fec_start 410773 restart_on_corruption ignore_zero_blocks'
[    2.130372] (3)[1:init][    2.130366]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-9 /dev/block/dm-9 4096 4096 209646 209646 sha1 3d97cb5d9f16a3d9ce2c2056ab8b3a2050646e5f e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-9 fec_roots 2 fec_blocks 211298 fec_start 211298 restart_on_corruption ignore_zero_blocks'
[    2.135838] (3)[1:init][    2.135832]@3 init: [libfs_avb]Built verity table: '1 /dev/block/dm-5 /dev/block/dm-5 4096 4096 15444 15444 sha1 7a8c095c71489e62b242b7b137d099d1f36a4f68 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-5 fec_roots 2 fec_blocks 15566 fec_start 15566 restart_on_corruption ignore_zero_blocks'
```
dmesg produce with LineageOS recovery:
```
Nord:/ # dmesg | grep libfs_avb
[    1.977591] (5)[1:init][    1.977587]@5 init: [libfs_avb]Returning avb_handle with status: Success
[    1.978731] (5)[1:init][    1.978727]@5 init: [libfs_avb]: Error verifying vbmeta image: OK_NOT_SIGNED
[    1.978767] (5)[1:init][    1.978764]@5 init: [libfs_avb]Found unknown public key used to sign /system
[    1.978783] (5)[1:init][    1.978780]@5 init: [libfs_avb]Returning avb_handle for '/system' with status: VerificationError
[    1.979964] (5)[1:init][    1.979958]@5 init: [libfs_avb]Built verity table: '1 /dev/block/dm-7 /dev/block/dm-7 4096 4096 234780 234780 sha1 92f8d04b6b85b99c10ad1784381cb974896206d1 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-7 fec_roots 2 fec_blocks 236631 fec_start 236631 restart_on_corruption ignore_zero_blocks'
[    1.992533] (5)[1:init][    1.992526]@5 init: [libfs_avb]Built verity table: '1 /dev/block/dm-8 /dev/block/dm-8 4096 4096 86750 86750 sha1 19daf5cd7bb360889c3c72b9bb6f4ba0d23ce0fb e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-8 fec_roots 2 fec_blocks 87435 fec_start 87435 restart_on_corruption ignore_zero_blocks'
[    1.997677] (5)[1:init][    1.997671]@5 init: [libfs_avb]Built verity table: '1 /dev/block/dm-6 /dev/block/dm-6 4096 4096 407562 407562 sha1 74905fd3c824dbbca500138f68a615ddd0365ee4 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-6 fec_roots 2 fec_blocks 410773 fec_start 410773 restart_on_corruption ignore_zero_blocks'
[    2.002824] (5)[1:init][    2.002818]@5 init: [libfs_avb]Built verity table: '1 /dev/block/dm-9 /dev/block/dm-9 4096 4096 209646 209646 sha1 3d97cb5d9f16a3d9ce2c2056ab8b3a2050646e5f e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-9 fec_roots 2 fec_blocks 211298 fec_start 211298 restart_on_corruption ignore_zero_blocks'
[    2.008406] (5)[1:init][    2.008399]@5 init: [libfs_avb]Built verity table: '1 /dev/block/dm-5 /dev/block/dm-5 4096 4096 15444 15444 sha1 7a8c095c71489e62b242b7b137d099d1f36a4f68 e663c83cb79b4c815f3391f136b313ab1de19cbe9ffbd971fe88a2a86882ed0d 10 use_fec_from_device /dev/block/dm-5 fec_roots 2 fec_blocks 15566 fec_start 15566 restart_on_corruption ignore_zero_blocks
```

**Comment by MrDuartePT** [comment]
I forget to send the command i use to sign.
OrangeFox recovery:
```
./avbroot ota patch \
    --input PixelExperience_Plus_avicii-13.0-20231003-1348-OFFICIAL.zip \
    --privkey-avb ./custom-keys/avb.key \
    --privkey-ota ./custom-keys/ota.key \
    --cert-ota ./custom-keys/ota.crt --clear-vbmeta-flags --magisk Magisk.v26.3.apk --magisk-preinit-device metadata --replace recovery OrangeFox-R12.1_1-Unofficial-avicii.img -o PixelExperience_Plus_avicii-13.0-OrangeFox.zip
```
[link for recovery](https://github.com/MrDuartePT/OrangeFox-Avicii-builder/releases/tag/6516956879)
Lineage Os Recovery:
```
./avbroot ota patch \
    --input PixelExperience_Plus_avicii-13.0-20231003-1348-OFFICIAL.zip \
    --privkey-avb ./custom-keys/avb.key \
    --privkey-ota ./custom-keys/ota.key \
    --cert-ota ./custom-keys/ota.crt --clear-vbmeta-flags --magisk Magisk.v26.3.apk --magisk-preinit-device metadata --replace recovery recovery-lineageos.img -o PixelExperience_Plus_avicii-13.0-LineageOS.zip
```
[link for recovery](https://mirrorbits.lineageos.org/full/avicii/20231012/recovery.img)

**Comment by chenxiaolong** [comment]
Does adb shell work when it's sitting at the black screen or is the device just completely frozen? I have no idea why it would work via `fastboot boot`, but not when it's flashed.

Can you post exactly how you're flashing everything? Are you just sideloading the OTA zip or is there anything else you're doing besides that?

If you haven't already tried this, I suggest:

1. Boot any recovery with `fastboot boot`.
2. Sideload either `PixelExperience_Plus_avicii-13.0-OrangeFox.zip` or `PixelExperience_Plus_avicii-13.0-LineageOS.zip`. Don't extract or flash anything else manually.
3. See if rebooting into recovery still results in a black screen.

**Comment by MrDuartePT** [comment]
For flashing I using this script:
```# Flash the boot images that were extracted
for image in extracted-PE-root/*.img; do
	partition=$(basename "${image}")
	partition=${partition%.img}

	fastboot flash "${partition}" "${image}"
done

# Flash the AVB signing public key
fastboot erase avb_custom_key
fastboot flash avb_custom_key custom-keys/avb_pkmd.bin```

I only have acess to adb on OrangeFox Recovery.
I gonna try adb sideload the zip and see what happen

**Comment by MrDuartePT** [comment]
Well after a busy week. I will try this week doing the adb fastboot

**Comment by MrDuartePT** [comment]
I gonna close the issue since oneplus broke the functionality on android 12 bootloader.
Let see if devices with android 13 bootloader have that fix (also oneplus fix Windevine in android 13 bootloader when using custom roms)
