### ISSUE TITLE
Investigate Pixel 8 / Pixel 8 Pro to see if there's anything new

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/avbroot#187]
Stock OTA images are now available:

* https://dl.google.com/dl/android/aosp/shiba-ota-ud1a.230803.041-6bbb528c.zip
* https://dl.google.com/dl/android/aosp/husky-ota-ud1a.230803.041-cca7e111.zip

I doubt there's anything new this generation that would impact avbroot, but I'll double check.

**Comment by chenxiaolong** [comment]
The Pixel 8 Pro's stock OTA structure is basically identical to the Pixel 7 Pro's. Same AVB setup, same boot image header versions, same dm-verity/FEC configuration. I'd expect everything to work out of the box.

Some things I found while looking at the firmware:

* 32 bit support has been completely removed instead of just being software disabled (eg. in the Pixel 7 series). The new firmware is not any smaller because the newly added things are about the same size as the deleted 32-bit libraries and odex files.
* The new SoC supports hardware AV1 encoding (`/vendor/lib64/libgc2_bw_av1_enc.so`).
* Common kernel modules are now in `system_dlkm` instead of shoving all of them into `vendor_dlkm`.
* New kernel, but still an ancient version :(
   * Pixel 7 Pro: `5.10.157-android13-4-00001-g5c7ff5dc7aac-ab10381520`
   * Pixel 8 Pro: `5.15.110-android14-11-ga6d7915820a0-ab10726252`
* New fastboot HAL
    * Pixel 7 Pro: `android.hardware.boot@1.0-impl-1.2-impl-gs201.so`
    * Pixel 8 Pro: `android.hardware.fastboot@1.1-impl.pixel.so`
* `init_boot` does not contain `dev/urandom`. I guess that's no longer needed for early boot.

**Comment by chenxiaolong** [comment]
Tested on a real device: it works! But you know what also works? Pixel Watch 2 + avbroot :slightly_smiling_face: 

The only weird thing about the PW2 is that it runs a 32 bit build of Android (including the kernel) on ARMv8 hardware. Aside from that, the boot process is identical to all the recent Pixel phones.

The new non-wireless charger has 4 pins and it turns out they carry a plain old USB signal. Plug that into a computer and you get adb and fastboot access. The bootloader is easily unlocked (at least on the non-cellular version). I tested with `--rootless` because Magisk app likely won't work correctly on the small screen.

**Comment by endri24** [comment]
> Tested on a real device: it works! But you know what also works? Pixel Watch 2 + avbroot 🙂
> 
> The only weird thing about the PW2 is that it runs a 32 bit build of Android (including the kernel) on ARMv8 hardware. Aside from that, the boot process is identical to all the recent Pixel phones.
> 
> The new non-wireless charger has 4 pins and it turns out they carry a plain old USB signal. Plug that into a computer and you get adb and fastboot access. The bootloader is easily unlocked (at least on the non-cellular version). I tested with `--rootless` because Magisk app likely won't work correctly on the small screen.

HI @chenxiaolong i saw this post that you had from last year and wanted to see if you can help me point in the right direction. I bought an use pixel watch 2 on an auction and unfortunately it was locked, i contacted google and they said there is nothing they can do to reset it, do you think there is a way to root it through the USB charger?

**Comment by endri24** [comment]
i think it is, but every time i try to connect it it keeps asking for the 4 digit passcode, i guess i will have to either guess or use it as a paper weight :P

**Comment by chenxiaolong** [comment]
Ah, that sucks. Sounds like the previous owner didn't properly reset the device.

**Comment by endri24** [comment]
Thanks again  :)
