### ISSUE TITLE
[Question] step 8 in Usage unclear

### ISSUE THREAD

**Issue by jemail99** [chenxiaolong/avbroot#198]
`8. [Initial setup only] Run dmesg | grep libfs_avb as root to verify that AVB is working properly.`

Where is this command to be run?
On the host PC?
On the host PC using a terminal with a fastboot connected device (if that's even possible)?
On the device in a terminal after rebooting it?

I have tried running this command on a current updated OpenSUSE PC and there is no output.
I have tried running this command on a current updated Debian Bookworm PC and there is no output.
Both OpenSUSE and Bookworm show no packages for libfs_avb, what am I missing?

**Comment by pascallj** [comment]
You have to run this as root on a terminal on your device (or via adb root).

See also #97.

But maybe it is a good idea to clarify this a bit in the readme.

**Comment by chenxiaolong** [comment]
Thanks, I've updated the README in 0a4dda14cddb08d2d3930bb4436eba2580b1f93c. The command should be run on the device while booted into Android (either with adb or via an app like Termux).
