### ISSUE TITLE
error when patching..

### ISSUE THREAD

**Issue by maanz79** [chenxiaolong/avbroot#20]
Maanz79@DESKTOP-A8ONTUU MINGW64 ~/avbroot (master)
$ **python avbroot.py \
    patch \
    --input C:/Users/Maanz79/Downloads/ota.zip \
    --privkey-avb C:/Users/Maanz79/avbroot/avb.key \
    --privkey-ota C:/Users/Maanz79/avbroot/ota.key \
    --cert-ota C:/Users/Maanz79/avbroot/ota.crt \
    --magisk C:/Users/Maanz79/Downloads/magisk.apk**
Traceback (most recent call last):
  File "C:\Users\Maanz79\avbroot\avbroot.py", line 316, in <module>
    main()
  File "C:\Users\Maanz79\avbroot\avbroot.py", line 308, in main
    patch_subcommand(args)
  File "C:\Users\Maanz79\avbroot\avbroot.py", line 217, in patch_subcommand
    with tempfile.TemporaryDirectory(dir=util.tmpfs_path()) as key_dir:
                                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Maanz79\avbroot\avbroot\util.py", line 38, in tmpfs_path
    if os.uname().sysname == 'Linux':
       ^^^^^^^^
AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?

------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------

Hi. I received this some kind of error when patching. Do you know how can i solve this?
Thanks..

**Comment by maanz79** [comment]
I'm using windows10.

**Comment by chenxiaolong** [comment]
This should be fixed by #21 from @pascallj.

**Comment by chenxiaolong** [comment]
Shoot, I was just reminded by another issue that magiskboot is Linux-only. Even if avbroot's own issues are fixed, the Magisk patch won't be able to run. Your only option might be WSL right now.

**Comment by chenxiaolong** [comment]
As of #37, avbroot now works on Windows.
