### ISSUE TITLE
Magisk preinit device determination

### ISSUE THREAD

**Issue by probablypablito** [chenxiaolong/avbroot#200]
Hello! I'm in the process of (hopefully) writing my own OTA server to automatically download and patch the latest releases of GOS with Magisk. 

I would ideally like for anyone to be able to use this in a plug-and-play way, but ran into an issue with the preinit device step. The README mentions:
>  This MUST be done on the target device! The partition name will be incorrect if patched from Magisk on a different device.

When it says "target device," is that referring to that specific physical device or just the same device model (Pixel 6, Pixel 7, etc.)?
My Pixel 6 gave the output of `metadata` which seems rather generic.

P.S. Thank you for this project! Has been incredibly convenient :)

**Comment by chenxiaolong** [comment]
Glad you're liking the project!

> When it says "target device," is that referring to that specific physical device or just the same device model (Pixel 6, Pixel 7, etc.)?
> My Pixel 6 gave the output of metadata which seems rather generic.

Just the same device model. It will never be different across multiple devices of the same model.

In practice, it's almost always going to be the `metadata` partition for modern Pixel devices, but I don't want to state that in the documentation. If the user picks the wrong thing, the Magisk app might prompt to repatch/reflash an unsigned boot image with the correct value. Tapping OK on that prompt would make the device unbootable until the bootloader is unlocked and the signed images are manually reflashed again.

**Comment by kaduvert** [comment]
Google Pixel 3a, sargo: mmcblk0p66
Google Pixel 4a (5G), bramble: sda25

let's build the documentation together!
