### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by chiteroman** [chenxiaolong/avbroot#209]
I get this errors:

```
[*] Copying zip entry: META-INF/CERT.RSA
[*] Copying zip entry: META-INF/CERT.SF
[*] Copying zip entry: META-INF/MANIFEST.MF
[*] Replacing zip entry: META-INF/com/android/otacert
[*] Copying zip entry: care_map.pb
[*] Copying zip entry: compatibility.zip
[*] Patching zip entry: payload.bin
[*] Extracting from original payload: boot
[*] Patching boot images: boot
Error: Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to patch boot image: boot
    2: AVB error
    3: Invalid VBMeta header magic: [65, 78, 68, 82]
```

**Comment by chenxiaolong** [comment]
In case you're still interested in this, can you post a link to the OTA you're patching? I'm curious if Xiaomi is doing something custom in their boot images (or maybe they don't use AVB 2.0 at all?)

**Comment by chiteroman** [comment]
> In case you're still interested in this, can you post a link to the OTA you're patching? I'm curious if Xiaomi is doing something custom in their boot images (or maybe they don't use AVB 2.0 at all?)

This phone has his KeyMaster in debug mode so always will report a locked bootloader even if bootloader is unlocked so I don't need to lock it, that's why I closed this.
The OTA is this: https://xiaomifirmwareupdater.com/miui/daisy/stable/V11.0.21.0.QDLMIXM/

**Comment by chenxiaolong** [comment]
Thanks for the link. Looks like despite `daisy` launching with Android 8.1, Xiaomi stuck with AVB 1.0. Not sure why since Google introduced AVB 2.0 in Android 8.0. I currently don't plan on adding AVB 1.0 support to avbroot.
