### ISSUE TITLE
Recovery image not sign/boot correctly

### ISSUE THREAD

**Issue by tienthanh2509** [chenxiaolong/avbroot#212]
Dear @chenxiaolong 
Thanks your good tool, but could you help me check the below problem
Device: Oneplus 8T
Custom rom: LineageOS

When I using the avbroot cli to patch and verify the OTA zip, all thing seem good

```
thanh@DESKTOP-F9VN9KV:/mnt/e/Kebab$ ./avbroot ota patch \
    --input lineage-20.0-20231124-nightly-kebab-signed.zip \
    --key-avb avb.key \
    --key-ota ota.key \
    --cert-ota ota.crt \
    --magisk Magisk-v26.4.apk \
    --magisk-preinit-device boot \
    --clear-vbmeta-flags \
    --replace recovery \
    recovery.img
[*] Replacing zip entry: META-INF/com/android/otacert
[*] Copying zip entry: apex_info.pb
[*] Copying zip entry: care_map.pb
[*] Patching zip entry: payload.bin
[*] Opening external image: recovery: "recovery.img"
[*] Extracting from original payload: vbmeta
[*] Extracting from original payload: boot
[*] Extracting from original payload: vbmeta_system
[*] Patching boot images: boot, recovery
[*] Patching vbmeta images: vbmeta_system, vbmeta
[*] Compressing replacement images: boot, recovery, vbmeta
[*] Generating new OTA payload
[*] Patching zip entry: payload_properties.txt
[*] Generating new OTA metadata
[*] Verifying metadata offsets
[*] Completed after 41.5s
```

The OS is fine to boot up and work normally
The Lingeage OS recovery is not anble to boot, phone boot to fastboot instead
Both recovery in zip and custom recovery is not working
Try boot recovery with command ` fastboot --disable-verity --disable-verification flash recovery recovery.img`. It works normally

Since recovery not working, so phone cannot boot when re-lock bootloader

Do you have any idea?
Thank you

**Comment by chenxiaolong** [comment]
Other folks have run into a similar problem too: https://github.com/chenxiaolong/avbroot/issues/186 (OnePlus Nord) and https://github.com/chenxiaolong/avbroot/discussions/195 (OnePlus 8 Pro), but I have no idea why it happens. As far as I can tell, OnePlus uses standard AVB 2.0 just like Google Pixels, but for some reason, the bootloader refuses to boot into recovery, even with a valid signature.

I don't know what can be done to troubleshoot this. As far as I'm aware, there's no way to get the bootloader's logs to understand why it rebooted back into fastboot.

(I wonder if anyone has successfully booted into recovery with avbroot + locked bootloader on any OnePlus device.)

**Comment by tienthanh2509** [comment]
Thanks, It looks like some problem with the Onelus bootloader
I will keep exploring the Oneplus bootloader to get logs if possible

**Comment by tienthanh2509** [comment]
Oneplus seem change bootloader from android 12 and don't support custom key
For android 11 of Oneplus 8T, the tool is patching successfully and yellow screen will display instead of orange

**Comment by MrDuartePT** [comment]
@tienthanh2509 sorry for the ping.
This means for this to work in oneplus phones, frist we need to have oneplus phone that support android 11 and the we need to downgraded to that version before changing the Rom.

Strange the phone still allow to flash the keys.

**Comment by MrDuartePT** [comment]
Also pixel experience don’t supported either.
I think the better action is not to try then.
I know I can use EDL to return to stock if everything break but it a huge pain if I found out I have to update again to android 12 firmware to run custom roms
