### ISSUE TITLE
2023112600 build of GrapheneOS causes bootloop if Magisk is installed as system server crashes

### ISSUE THREAD

**Issue by pixincreate** [chenxiaolong/avbroot#213]
Posting this here to let you and everyone be aware of this.  

Once if you install `2023112600` build of GrapheneOS, **do not** flash Magisk to the other slot or whatsoever.   
The reason being, the changes done under the hood is an advance in terms of hardening memory and its allocation (I did not care much to dig in to understand what's going on at this point).

Once you install the latest version, just reboot the device (With avbroot, the procedure would a be different, but make sure you that you do not install it directly). You'll have to boot your device without root once and **Disable Hardened memory allocator** and **enable native code debugging**. Then proceed to install Magisk as usual.

Well, I was wrong. The entirety has been broken:
- Networking module does not work meaning no Signal and no WiFi.
- Storage does not work, I cannot access files through apps

**Comment by chenxiaolong** [comment]
Did you happen to have Zygisk enabled? I definitely wouldn't be surprised if the new GrapheneOS changes impacted that. Zygisk is quite invasive.

> Once you install the latest version, just reboot the device (With avbroot, the procedure would a be different, but make sure you that you do not install it directly). You'll have to boot your device without root once and Disable Hardened memory allocator and enable native code debugging. Then proceed to install Magisk as usual.

Folks using avbroot can patch the OTA once using `--rootless` instead of `--magisk <apk>` to get an unrooted system.

**Comment by pixincreate** [comment]
I was never able to get Zygisk working. It always said 'Reboot to turn on Zygisk' .

**Comment by chenxiaolong** [comment]
That's interesting and makes me even more curious about why it'd be breaking parts of the system. It's been ages since I last looked at Magisk's internals, but the changes it used to make were mostly additive. At first glance, it looks like nowadays, Magisk does make some changes that could conflict with the types of security improvements GrapheneOS makes (eg. it blocks everything besides Magisk itself from loading SELinux policies).

Does `adb logcat | grep avc:` print any `denied` messages when the network or storage components crash?

**Comment by pixincreate** [comment]
I was looking at GOS and came up with this: https://github.com/GrapheneOS/os-issue-tracker/issues/2725

**Comment by stavae** [comment]
Patching boot.img manually in magisk (didnt know avbroot existed) has the same issue :/

**Comment by pixincreate** [comment]
Yes, GrapheneOS has openly admitted that their changes will soon break KernelSU as well and I couldn't stop laughing.
https://nitter.net/pixincreate/status/1729029093168185403

AFAIK, Magisk has got more and more invasive overtime (I did not verify that by testing it with an older version) since the launch of Zygisk.

**Comment by ccoager** [comment]
Perhaps this is fixed already, I haven't tried a nightly build though.
https://github.com/topjohnwu/Magisk/issues/7489

**Comment by pixincreate** [comment]
The latest CI build did fix a lot issues except the Zygisk (it never turns on) of course

**Comment by pixincreate** [comment]
https://github.com/HuskyDG/magisk-files/commit/f3f4eff48af6ce31023e2fe7b01a84c7445a685e

Seems to have fixed it in Magisk Delta
