### ISSUE TITLE
Investigate Pixel's new repair mode feature

### ISSUE THREAD

**Issue by chenxiaolong** [chenxiaolong/avbroot#216]
The December 2023 Pixel OTA update added support for a "repair mode". I'd like to investigate to see if this has any impact to how things are signed for AVB.

The feature is not open source. There are parts of the implementation in `/system_ext/priv-app/SettingsGoogle` and `/system_ext/app/RepairMode`. At first glance, it seems to be implemented on top of Android's DSU mechanism.

**Comment by chenxiaolong** [comment]
Repair mode is fully working in an avbroot setup, but with a **big caveat** (see bottom of post).

But first, this is how the feature is implemented:

1. When repair mode is turned on, it creates a new [DSU (dynamic system update)](https://developer.android.com/topic/dsu) slot named `repairmode.lock`:

    ```kotlin
    DynamicSystemManager.startInstallation("repairmode.lock")
    ```

2. It then writes an empty `userdata` partition image in `/data/gsi/dsu/repairmode.lock/`. The minimum size of the image file is 2 GiB and the maximum size is `min(<free space> - 300 MiB, 10 GiB)` rounded down to the nearest GiB.

    ```kotlin
    DynamicSystemManager.createPartition("userdata", size, /* readOnly */ false)
    DynamicSystemManager.closePartition()
    DynamicSystemManager.finishInstallation()
    ```

    Because no other partition images are created, the original `system`/`system_ext`/`product`/`vendor`/etc. are used as-is.

3. If the DSU creation is successful, then it marks the new `repairmode.lock` slot as the default slot for all future reboots.

    ```kotlin
    DynamicSystemManager.setEnable(/* enable */ true, /* oneShot */ false)
    ```

    If you're quick, running `gsi_tool` before the device has a chance to reboot will output:

    ```
    # gsi_tool status
    installed
    enabled
    [0] repairmode.lock
    installed: userdata_gsi
    AVB public key (sha1): [NONE]
    ```

4. After rebooting, the device will mount the new `userdata` image at `/data` instead of the real `userdata` partition. Even though the image lives on the real partition, the real partiition is never mounted. This works because the image creation procedure uses Linux's fiemap API to record which sectors/blocks the image file occupies on disk. When booted into repair mode, only those specific blocks are accessed (via dm-linear).

5. The (proprietary) `RepairMode` app will set up Android's device policy mechanism to disable the initial setup wizard and gray out the factory reset and OEM unlocking options.

6. The device remains in repair mode until the user exits it via the notification. This will configure the system to boot back into the original system and the `repairmode.lock` DSU slot will be deleted after rebooting.

---

# WARNING!

There's is one big caveat with avbroot + repair mode. Repair mode will also be rooted! All it takes is installing the Magisk/KernelSU app and root access will be granted. This is problematic because with root access, it's _trivial_ for someone to manually mount the original `userdata` partition and install a malicious Magisk/KernelSU module. Emphasis on `trivial` since repair mode has no authentication (because of what the feature is intended for). A malicious module installed this way would persist after exiting repair mode.

The only way to prevent this is to ensure that root access does not work when booted into repair mode. The easiest way to do this is by building Magisk/KernelSU from source **in release mode** and signed with your own keys. Custom release builds will not trust the official Magisk/KernelSU APK. If the "repair technician" (or anyone else) installs the official APK, root access would be denied. **Do not build Magisk/KernelSU in debug mode--that will disable the signature checks.**

I'd recommend just flashing the stock OS before sending the device in for repairs, if possible.

**Comment by chenxiaolong** [comment]
> Would flashing a rootless variant of the system fix this issue?

That's brilliant! I didn't think of that at all. Yes, that completely solves the problem. Switching between avbroot-signed rootless and rooted builds is just an adb sideload away. I'll update my message above to suggest that.

**Comment by pascallj** [comment]
One downside I was later thinking of, is that the 'clearotacerts' module is not running. Therefore maybe the system might get an accidental OTA update (if that works in repair mode) which breaks the system.

**Comment by chenxiaolong** [comment]
I was wrong. I tested with Custota and it looks like OTA updates go through just fine in repair mode. It also looks like repair mode enables the OEM updater app too, which I suppose makes sense since that's the default. I don't see a good solution around this.

I was trying finding a way to do what the `clearotacerts` module does without Magisk/KernelSU, but after looking at the code for `/system/bin/init`, I highly doubt this is possible without wrapping the binary like what Magisk does. I think that's a bit too invasive and may conflict with Magisk.

I can't think of a way to use repair mode that's 100% safe against the accidental OTA update scenario at the moment.

**Comment by pascallj** [comment]
Thanks for testing! Avbroot supports repacking of images now right? What if we just replace the otacerts.zip and repack the image?

**Comment by chenxiaolong** [comment]
> In userspace, as in userspace on the device avbroot is running on?

I meant on the system that's running `avbroot ota patch`. The filesystem would have to be modified and then avbroot can recompute the dm-verity hashes and FEC.

> We can just corrupt the file 🙈 Ext4 doesn't have checksums as far as I'm aware.

:joy: I guess that is indeed theoretically possible. Still would require some sort of ext4/erofs parser to find the blocks where the file is located though.

(If there actually is a good way to find the block(s) containing `otacerts.zip`, we could do better than corrupting it. We could insert one with the user's key and pad out the file to equal the original size. avbroot's generated `otacerts.zip` is usually a few hundred bytes smaller than Google's original one.)

**Comment by chenxiaolong** [comment]
Well, it turns out recovery's copy of `otacerts.zip` is byte-for-byte identical to the copy inside `system.img`. Blindly searching for those bytes inside `system.img` and replacing them actually works: https://gist.github.com/chenxiaolong/da42491c0b7d4fb8262b6fc3c2850777.

I tested with ext4 and uncompressed erofs. fsck passes, the filesystem mounts, and the replaced `otacerts.zip` data shows up as expected.

Although this actually works well, I probably won't implement this because:

* Patching would be slow since `system.img` would need to be extracted, modified, and recompressed. Inside a temp directory, the image would need to be fully read 3 times and fully written once in order to make the modifications and regenerate the dm-verity metadata. This would probably increase the patching times by an order of magnitude.
* This doesn't work at all for compressed erofs. I wouldn't be surprised if Google switches to this in the near future. I believe Samsung's newest devices already use it.

---

It sure would be nice if we could just:

```
mount --bind <recovery's otacerts> <system's otacerts>
```

during `init`'s first stage... There's just no easy way to hook into that process.

**Comment by pascallj** [comment]
Interesting! I agree, it is not worth implementing it this way. It's a very niche use case.
