### ISSUE TITLE
fail when patching using output located at path where sendfile() syscall doesn't work

### ISSUE THREAD

**Issue by ArtemPisarenko** [chenxiaolong/avbroot#22]
avbroot calls magiskboot binary which fails with error:
`sendfile failed with 22: Invalid argument`

Issue introduced by #19 which made default temporary directory path overriden.

The problem comes from Magisk implementation which uses very specific `sendfile()` system call for implementing read'n'write operations without fallback to universal implementation with userspace i/o (as `man sendfile` prescribes). And it's a known limitation that `sendfile()` can't work on some special filesystems like network shares. (In my case it's a shared folder in VirtualBox guest (i.e. `vboxsf` type) and should work, but seems like a bug in virtualbox.). Since Magisk [isn't intended](https://github.com/topjohnwu/Magisk/issues/2859#issuecomment-638039682) to be used in a way avbroot uses it, there are no issues with such implementation, so I'm not sure Magisk developers want implement workaround. It's a rather effect of avbroot "hack".

**Comment by chenxiaolong** [comment]
Thanks. I'll update avbroot so that it respects the standard `TMPDIR` environment variable for picking a different temporary directory. Hopefully with `export TMPDIR=/tmp`, that'll be sufficient for working around `sendfile` not working with `vboxsf`.

**Comment by chenxiaolong** [comment]
This should be fixed now. #28 removed the need to create any large temp files, so #30 removed the code for setting the default temporary directory to the output directory. avbroot now uses the OS's default (`/tmp`).

**Comment by chenxiaolong** [comment]
This should be fixed for good. As of #37, avbroot does all boot image operations itself and no longer relies on magiskboot. Python's standard library also uses `sendfile` if available, but should fall back to `read`/`write` when it doesn't work.
