### ISSUE TITLE
tried new Rust version, got glibc error  `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by oddgirl** [chenxiaolong/avbroot#222]
Hi!
Basically this 

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found

Debian 11

**Comment by chenxiaolong** [comment]
Hmm, this might be because Github upgraded the machines they use for Github Actions builds to Ubuntu 22.04. I'll see if I can adjust the Linux build to be statically linked so that it works on any distro.

**Comment by chenxiaolong** [comment]
This is fixed by #224, which will be included in avbroot 2.3.4. In the meantime, you can grab the test build from: https://github.com/chenxiaolong/avbroot/actions/runs/7188578079?pr=224.
