### ISSUE TITLE
Critical Partitions

### ISSUE THREAD

**Issue by saduncan084** [chenxiaolong/avbroot#223]
C:\avbroot>avbroot ota patch --input 2937d9d6e8a03973c33443f809287435e44858b8.zip --key-avb avb.key --key-ota ota.key --cert-ota ota.crt --magisk magisk.apk --magisk-preinit-device metadata --output out.zip --replace abl abl.img --otacerts-partition boot --clear-vbmeta-flags
Enter passphrase for "avb.key":
Enter passphrase for "ota.key":
[*] Replacing zip entry: META-INF/com/android/otacert
[*] Patching zip entry: payload.bin
[*] Extracting from original payload: vbmeta_vendor
[*] Extracting from original payload: boot
[*] Opening external image: abl: "abl.img"
[*] Extracting from original payload: vbmeta
[*] Extracting from original payload: vbmeta_system
[*] Patching boot images: boot
Error: Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Found critical partitions that are not protected by AVB: odm

**Comment by chenxiaolong** [comment]
Can you post a link to the OTA?

**Comment by saduncan084** [comment]
https://android.googleapis.com/packages/ota-api/package/2937d9d6e8a03973c33443f809287435e44858b8.zip

**Comment by chenxiaolong** [comment]
This has been addressed by #226, which will be in avbroot 2.3.4. In the meantime, you can use the test build at: https://github.com/chenxiaolong/avbroot/actions/runs/7189964194?pr=226
