### ISSUE TITLE
Custom kernel (ideally AnyKernel 3) support

### ISSUE THREAD

**Issue by danielphan2003** [chenxiaolong/avbroot#238]
#13 and #102 were made before the rust rewrite, and now I can't find where to use custom kernel anywhere, specifically AnyKernel 3. I tried following https://kernelsu.org/guide/installation.html#patch-boot-img-manually and patched the repacked image via the Magisk app, but when I specify that image via `--prepatched`, it said that my new image isn't compatible with the old one. My command were:
```
avbroot ota patch \
    --input ./ota.zip \
    --key-avb ./avb.key \
    --key-ota ./ota.key \
    --cert-ota ./ota.crt \
    --prepatched magisk_patched-*.img
```

The complete logs were:
```
[*] Replacing zip entry: META-INF/com/android/otacert
[*] Copying zip entry: apex_info.pb
[*] Copying zip entry: care_map.pb
[*] Patching zip entry: payload.bin
[*] Extracting from original payload: vbmeta_system
[*] Extracting from original payload: vbmeta_vendor
[*] Extracting from original payload: init_boot
[*] Extracting from original payload: vbmeta
[*] Extracting from original payload: vendor_boot
[*] Patching boot images: init_boot, vendor_boot
Error: Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to patch boot image: init_boot
    2: Validation error: The prepatched boot image is not compatible with the original:
       - Field differs: old.kernel.is_empty() (true) -> new.kernel.is_empty() (false)
```

EDIT: My device is Pixel 7, and after extracting partitions from the patched OTA I'm left with init_boot.img. Do I need to patch OTA again?

**Comment by chenxiaolong** [comment]
Could you explain a bit more about what you're trying to do? It looks like you want to use KernelSU, but I don't understand why Magisk is involved at all.

**Comment by danielphan2003** [comment]
I'm actually trying to use Sultan kernel (https://xdaforums.com/t/kernel-a13-a14-sultan-kernel-for-pixel-7-pro-a-october-20-2023.4623789/). Their kernel zip is a AnyKernel3 zip file that has `Image.lz4` and `dtbo.img`. I also want to use Magisk, so what I have tried was:

1. Patch the Sultan image (after extracting `Image.lz4` into `Image`) with the boot image that I have from my original OTA file:
```
cd /data/local/tmp/
chmod +x magiskboot
./magiskboot unpack boot.img
mv -f ./Image kernel
./magiskboot repack boot.img
```

For this I followed the KernelSU guide for patching boot image manually. This returns a `new-boot.img` that I then copied and put into `kernel/boot.img` on my working dir. The `dtbo.img` I mentioned before is also put into the `kernel` folder.

2. Patch the kernel `boot` in Magisk Manager to get a patched Magisk `boot` file that I can use to get the preinit device (I save this to a file named `get-magisk-preinit-device.sh`):
```
avbroot boot magisk-info --image magisk_patched-*.img
```
![avbroot magisk info](https://github.com/chenxiaolong/avbroot/assets/34669737/f90d455d-1050-4868-a5e7-9f1babda2b9e)


3. Extract the OTA file into `original`, so I can add hash footer for the kernel's `boot` and `dtbo`:
```
avbroot ota extract --input ./ota.zip --directory ./original --all
```
![original ota files](https://github.com/chenxiaolong/avbroot/assets/34669737/5fbef3f2-e5cd-4a92-8d16-7ac341cf441b)


and adding hash footer by running:
```
avbtool add_hash_footer --image kernel/dtbo.img --partition_name dtbo --partition_size $(stat --format=%s original/dtbo.img)
avbtool add_hash_footer --image kernel/boot.img --partition_name boot --partition_size $(stat --format=%s original/boot.img)
```

4. Patch the OTA file:
```
source ./get-magisk-preinit-device.sh

avbroot ota patch \
    --input ./ota.zip \
    --key-avb ./avb.key \
    --key-ota ./ota.key \
    --cert-ota ./ota.crt \
    --replace dtbo ./kernel/dtbo.img \
    --replace boot ./kernel/boot.img \
    --magisk ./magisk.apk \
    --magisk-preinit-device "$PREINITDEVICE"
```

By which I got this error:
```
Error: Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: boot descriptor (Hash) does not match entry in vbmeta (ChainPartition)
```

I thought adding hash footer to each image was good enough for vbmeta to not complain, but it seems I have to modify vbmeta somehow to accept my custom boot hash?

**Comment by chenxiaolong** [comment]
Thanks for explaining! Everything you're doing is right, except for the hash footer. The mismatch is because Google's original `boot.img` has a signed footer, but your `avbtool add_hash_footer` is adding an unsigned footer. If you add `--key` to the avbtool command and pass it your `avb.key`, that should do the trick.

(You can check if an image has a signed footer by running either `avbroot avb info -i <partition>.img` or `avbtool info_image --image <partition>.img`. It is signed if the "public key" field exists and is not empty.)

However, with that said, when adding new footers from scratch with `avbtool`, you'll be missing some other metadata like the rollback index (for downgrade protection). If you ever switch back to the stock kernel, which does have this metadata, the bootloader will not allow the userdata partition to be decrypted and you'd be forced to factory reset.

avbroot has builtin tools for unpacking and packing boot images and AVB headers/footers. I would suggest doing the following instead. The modified `boot.img` and `dtbo.img` will preserve all the necessary AVB metadata from the original images.

```
# Extract the original OTA to get boot.img and dtbo.img
avbroot ota extract -i original_ota.zip -d extracted --all

# Unpack boot.img
mkdir extracted/boot
cd extracted/boot
avbroot avb unpack -i ../boot.img
avbroot boot unpack -i raw.img

# Replace the kernel component
cp /path/to/sultan/Image.lz4 kernel.img

# Repack boot.img
avbroot boot pack -o raw.img
avbroot avb pack -o ../boot.modified.img -k /path/to/avb.key

# Unpack dtbo.img
mkdir ../dtbo
cd ../dtbo
avbroot avb unpack -i ../dtbo.img

# Replace the dtbo image
cp /path/to/sultan/dtbo.img raw.img

# Repack dtbo.img
avbroot avb pack -o ../dtbo.modified.img -k /path/to/avb.key

# Patch the OTA
cd ../..
avbroot ota patch \
    --input ./ota.zip \
    --key-avb ./avb.key \
    --key-ota ./ota.key \
    --cert-ota ./ota.crt \
    --replace boot extracted/boot.modified.img \
    --replace dtbo extracted/dtbo.modified.img \
    --magisk ./magisk.apk \
    --magisk-preinit-device "$PREINITDEVICE"
```

---

(Also, first time seeing nushell in the wild. Nice!)

**Comment by danielphan2003** [comment]
Hmm, I guess replacing boot and dtbo doesn't work for my device's boot layout, since extracting the patched OTA only shows `init_boot`, `vbmeta*` and `vendor_boot`, but not the modified `boot` and `dtbo` which has the Sultan kernel though I still have access to Magisk.

I had to manually flash those, but other than that I can confirm that it works! Thank you so much for helping. I hope to make a PR to better reflect this use case in the readme.

---
Using Rust-written tools really is nicer than other tools I used before ;)

**Comment by danielphan2003** [comment]
Oops, after locking bootloader I found out that Magisk requires me to do Additional setup, which I thought was gonna be like #116, and it shows me the direct install page which I assumes was going to clean out `/data/adb/magisk`, but then breaks my boot. I guess manually flashing modified `boot` and `dtbo` is wrong, and I had to somehow make the patched OTA returns them in the first place.

**Comment by chenxiaolong** [comment]
No problem!

> since extracting the patched OTA only shows `init_boot`, `vbmeta*` and `vendor_boot`, but not the modified `boot` and `dtbo` which has the Sultan kernel though I still have access to Magisk.

Try extracting with the `--all` option. By default, avbroot only extracts a minimal number of partitions for a standard (non custom kernel) setup.

> it shows me the direct install page which I assumes was going to clean out `/data/adb/magisk`, but then breaks my boot

Yep, the direct install is what broke the boot here. During direct install, Magisk will flash an unsigned boot image.

I _think_ this might be because of the preinit device. Can you share how your `get-magisk-preinit-device.sh` works? I noticed in your screenshot, it shows `PREINITDEVICE=persist`, but Magisk is supposed to be setting it to `metadata` for modern Pixel devices. When Magisk detects the mismatch, it offers the direct install option to try and "fix" it.

**Comment by danielphan2003** [comment]
The `get-magisk-preinit-device.sh` was basically a oneliner of `avbroot boot magisk-info --image magisk_patched-*.img`. I patched the original `boot` using Magisk Delta or also named as Magisk Kitsune (sorry for being unclear about this), and when I used `get-magisk-preinit-device.sh` to show the `PREINITDEVICE` it shows `persist`. I guess Delta/Kitsune wrongly assumed that my device uses `persist`. Here is the image showing that:

![preinit device variable of a magisk boot image](https://github.com/chenxiaolong/avbroot/assets/34669737/e1da6fd3-8d95-40d0-88c1-337bd6cf785e)

I also attached the original boot image (https://litter.catbox.moe/hfagvb.img) and the Magisk Delta/Kitsune patched one (https://litter.catbox.moe/kpof8o.img). I'm using https://github.com/HuskyDG/magisk-files/releases/tag/R6583F3E5-kitsune

**Comment by danielphan2003** [comment]
Can confirm that extracting with `--all` fixes the Additional setup, but I'm not sure if this is also because I changed `PREINITDEVICE` to `metadata` as you said. Perhaps Kitsune can handle whatever is thrown at it, and only gets angry if I were to flash modified `boot` and `dtbo`.

**Comment by chenxiaolong** [comment]
Huh, that's interesting. I gave https://github.com/HuskyDG/magisk-files/releases/tag/R6583F3E5-kitsune a try and it's printing out `metadata`. I'm on a Pixel 8 Pro, but it has the exact same partition structure as Pixel 7. I'm really not sure why it would be detecting `persist`.

I took a look at Magisk and it seems they added a new command relatively recently for showing the preinit device without going through the app's patching process. Out of curiosity, does this also show `persist` for you?

```bash
unzip magisk.apk lib/arm64-v8a/libmagisk64.so
adb push lib/arm64-v8a/libmagisk64.so /data/local/tmp/magisk
adb shell chmod +x /data/local/tmp/magisk
adb shell /data/local/tmp/magisk --preinit-device
```

**Comment by danielphan2003** [comment]
It shows `metadata` in Termux:
![magisk preinit termux](https://github.com/chenxiaolong/avbroot/assets/34669737/67234059-915a-44fa-a698-e1365d93b4c1)

I suspect something went wrong during the patching process, so I will try again to see if this `persist`s 😉

**Comment by vbooka1** [comment]
> avbroot avb pack -o ../boot.modified.img -k /path/to/avb.key

this commands fails for me, avbroot says `Leaving AVB header unsigned`:

```
...
$ ../../avbroot avb pack -o ../boot.modified.img -k ../../avb.key 
[*] Leaving AVB header unsigned
AvbInfo {
    header: Header {
        required_libavb_version_major: 1,
        required_libavb_version_minor: 0,
        algorithm_type: None,
        hash: "",
        signature: "",
        public_key: "",
        public_key_metadata: "",
        descriptors: [
            Hash(
                HashDescriptor {
                    image_size: 38809600,
                    hash_algorithm: "sha256",
                    partition_name: "boot",
                    salt: "192c9898ee9dcace785a0d7c4f46f37c1a788c3e47d475bc6bc4b4792d49db76",
                    root_digest: "b9cf81e5ba6b4eaa90e08a7f8f5703a9d08056f4767f1ab81b615a9525de1841",
                    flags: 0,
                    reserved: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                },
            ),
            Property(
                PropertyDescriptor {
                    key: "com.android.build.boot.os_version",
                    value: "13",
                },
            ),
            Property(
                PropertyDescriptor {
                    key: "com.android.build.boot.fingerprint",
                    value: "google/sunfish/sunfish:13/TQ3A.230805.001.S1/2023122200:user/release-keys",
                },
            ),
            Property(
                PropertyDescriptor {
                    key: "com.android.build.boot.security_patch",
                    value: "2023-09-01",
                },
            ),
        ],
        rollback_index: 0,
        flags: 0,
        rollback_index_location: 0,
        release_string: "avbtool 1.2.0",
        reserved: "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    },
    footer: Some(
        Footer {
            version_major: 1,
            version_minor: 0,
            original_image_size: 38809600,
            vbmeta_offset: 38809600,
            vbmeta_size: 768,
            reserved: "00000000000000000000000000000000000000000000000000000000",
        },
    ),
    image_size: 67108864,
}
```

The boot image is really not signed because the file sizes are identical:

```
-rw-r--r-- 1 user user   67108864 Dec 27 12:35 boot.img
-rw-r--r-- 1 user user   67108864 Dec 27 12:45 boot.modified.img
```

I have tried to use both `avb.pem` and `avb.key` without success: both the cert and the key results in "Leaving AVB header unsigned".

I think this is a bug in `avbroot avb pack` command because `avbroot ota patch` command works well and creates a correctly patched OTA image with my avb.pem and avb.key.

**Comment by vbooka1** [comment]
> The boot image is really not signed because the file sizes are identical:

or maybe signed... the `avb.toml` files from the original `boot.img` and `boot.modified.img` are different and `raw.img` file sizes are different too.
But the `dtbo.img` is not getting signed for sure, because the md5 checksum stays the same:

```
$ mkdir ../dtbo

$ cd ../dtbo

$ ../../avbroot avb unpack -i ../dtbo.img

# I do not change the dtbo but just try to resign it with my AVB key:

$ ../../avbroot avb pack -o ../dtbo.modified.img -k ../../avb.key
[*] Leaving AVB header unsigned
AvbInfo {
    header: Header {
        required_libavb_version_major: 1,
        required_libavb_version_minor: 0,
        algorithm_type: None,
        hash: "",
        signature: "",
        public_key: "",
        public_key_metadata: "",
        descriptors: [
            Hash(
                HashDescriptor {
                    image_size: 2003048,
                    hash_algorithm: "sha256",
                    partition_name: "dtbo",
                    salt: "2276ee52a179a12f88f5e34df09a539cc1682fddf52402c1017d4d8353806bc3",
                    root_digest: "34835fe33c4a2e013bae6d91de81e574cdcf59ea24f55f28c16a99c4b0715ced",
                    flags: 0,
                    reserved: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                },
            ),
            Property(
                PropertyDescriptor {
                    key: "com.android.build.dtbo.fingerprint",
                    value: "google/sunfish/sunfish:13/TQ3A.230805.001.S1/2023122200:user/release-keys",
                },
            ),
        ],
        rollback_index: 0,
        flags: 0,
        rollback_index_location: 0,
        release_string: "avbtool 1.2.0",
        reserved: "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    },
    footer: Some(
        Footer {
            version_major: 1,
            version_minor: 0,
            original_image_size: 2003048,
            vbmeta_offset: 2007040,
            vbmeta_size: 640,
            reserved: "00000000000000000000000000000000000000000000000000000000",
        },
    ),
    image_size: 8388608,
}

# and the resulting file is the same as the original:

$ md5sum ../dtbo.img 
005d1258eb1b389c14772cc1c6fdebfd  ../dtbo.img
$ md5sum ../dtbo.modified.img 
005d1258eb1b389c14772cc1c6fdebfd  ../dtbo.modified.img
```

So the files are not getting signed with my AVB key.
Am I doing something wrong or is it really a bug?

**Comment by vbooka1** [comment]
I've checked the avbroot source code and found out that the OTA update does not have an AVB signature?!

```
...

    let mut sign_action = if originally_signed && &info.header != orig_header {
        SignAction::Sign
    } else {
        // If the original image was signed, we can preserve the existing
        // signature since no changes were made. If the original image was not
        // signed, then there's nothing to do anyway.
        SignAction::None
    };
        
...

    match sign_action {
        SignAction::None => {
            if originally_signed {
                status!("Preserving original AVB header signature");
            } else {
                status!("Leaving AVB header unsigned");
            }
        }
```
Also I've found a `--force` option and tried to do this:

```
$ avbroot avb pack -o ../boot.modified.img -k ../avb.pem  --force
```

Which supposedly have added my AVB signature, but trying to create a new OTA with the resulting boot image failed with error "boot descriptor (Hash) in vbmeta must be a chain descriptor"

```
$ ./avbroot ota patch  --input sunfish-ota_update-2023122200.zip --key-avb ./avb.pem --key-ota ./avb.pem --cert-ota ./ota.crt  --replace boot ./boot.lz4.img --rootless
Enter passphrase for "./avb.pem": 
Enter passphrase for "./avb.pem": 
[*] Replacing zip entry: META-INF/com/android/otacert
[*] Copying zip entry: apex_info.pb
[*] Copying zip entry: care_map.pb
[*] Patching zip entry: payload.bin
[*] Opening external image: boot: "./boot.lz4.img"
[*] Extracting from original payload: vbmeta
[*] Patching boot images: boot
[*] Patching vbmeta images: vbmeta
Error: Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: boot descriptor (Hash) in vbmeta must be a chain descriptor
```

Is it because the original OTA really was not signed? 

I still feel that I'm doing something wrong, please help me to create an AVB signed boot image with a custom kernel (KernelSU).

**Comment by vbooka1** [comment]
> $ ./avbroot ota patch  --input sunfish-ota_update-2023122200.zip --key-avb ./avb.pem --key-ota ./avb.pem --cert-ota ./ota.crt  --replace boot ./boot.lz4.img --rootless

Sorry, I really did it wrong: it must be `--prepatched ./boot.lz4.img` not `--replace boot ./boot.lz4.img --rootless`

A fixed command `$ ./avbroot ota patch --input sunfish-ota_update-2023122200.zip  --key-avb avb.pem --key-ota avb.pem --cert-ota ota.crt --prepatched boot.lz4.img` produced an OTA image correctly. 
Trying to flash the new boot.img and vbmeta.img...

**Comment by vbooka1** [comment]
>  Trying to flash the new boot.img and vbmeta.img...

Well, seems that I have built the kernel wrong.
The phone did not boot with the modified boot image: flashing the modified `boot.img` to both `boot_a` and `boot_b` slots resulted in bootloop. Phone reboots several seconds after showing Google logo on the white background, and after 3 reboots phone loads fastboot with "Enter reason: no valid slot to boot".
Flashing the stock `boot.img` returns the phone to life, so I have decided to try a "clean" kernel from Google without KernelSU.
After I compiled the kernel and run 'fastboot boot Image.lz4-dtb' the phone rebooted several seconds after showing Google logo on the black background, and then booted from the different boot slot (with a stock, working boot image).

I'm sorry for an offtopic, but could anyone point me to a **working** manual on how to build a kernel for Pixel 4a please? 
A manual from https://source.android.com/docs/setup/build/building-pixel-kernels did not work for me:
```
repo init -u https://android.googlesource.com/kernel/manifest -b  android-msm-sunfish-4.14-android13-qpr3
repo sync -j4
KBUILD_BUILD_VERSION=1 KBUILD_BUILD_USER=build-user KBUILD_BUILD_HOST=build-host KBUILD_BUILD_TIMESTAMP="Thu 01 Jan 1970 12:00:00 AM UTC" BUILD_CONFIG=private/msm-google/build.config.sunfish build/build.sh
```
produced an unbootable `Image.lz4-dtb` file.

**Comment by chenxiaolong** [comment]
I think you've already discovered most of this yourself, but to answer some of the points that you brought up:

> this commands fails for me, avbroot says `Leaving AVB header unsigned`:

There are two ways that the boot image is verified:

* `boot.img` is unsigned
    * This causes a hash descriptor for `boot` to be added to `vbmeta`. The hash descriptor contains a checksum of the data.
    * Since `vbmeta` is always signed and `boot`'s checksum is stored inside of it, there is no loss of security.
* `boot.img` is signed
    * This causes a chain descriptor for `boot` to be added to `vbmeta`. The chain descriptor contains the public key for verifying `boot`'s signature.
    * Google uses this in the stock OS so that `boot` can be updated separately without needing to also update `vbmeta`.

When packing an image, avbroot tries to preserve whether an image is signed. If the original file was signed, then the newly packed file is signed. If the original file was unsigned, then the newly packed file is unsigned.

> The boot image is really not signed because the file sizes are identical:

The file size is always equal to the partition size on the device. The actual data is at the beginning of the file, the AVB information at the end of the file, and a bunch of `0`s fill the "empty" space in between.

> ```
> # I do not change the dtbo but just try to resign it with my AVB key:
>
> $ ../../avbroot avb pack -o ../dtbo.modified.img -k ../../avb.key
> ```

avbroot is "smart" about this. If you didn't change the contents, it reuses the original signature. As you discovered, you can force avbroot to resign it with `--force`.

> I'm sorry for an offtopic

No worries. I've opened a new discussion here to discuss it: https://github.com/chenxiaolong/avbroot/discussions/242.
