### ISSUE TITLE
The python branch seems moody about magisk versions, refuses versions older than 26.1 (hope the python branch is still supported) 

### ISSUE THREAD

**Issue by oddgirl** [chenxiaolong/avbroot#239]
Hi!
Using the python branch for ... cultural reasons (actually because I once again need [this little hack I came up with a while ago](https://github.com/chenxiaolong/avbroot/issues/90) and I am not clever enough to port it to the new non-python avbroot)

Attempted to use most recent magisk and fails with "unsupported magisk version" error.
Magisk 26.1 seems to have applied amicably (haven't flashed to phone yet)

Is the python variant of avbroot still receiving updates?

**Comment by chenxiaolong** [comment]
The direct equivalent to what you were doing before would be:

```diff
diff --git a/avbroot/src/boot.rs b/avbroot/src/boot.rs
index cd08ca4..3ccfd30 100644
--- a/avbroot/src/boot.rs
+++ b/avbroot/src/boot.rs
@@ -288,6 +288,18 @@ impl BootImagePatcher for MagiskRootPatcher {
             entries.push(CpioEntry::new_directory(path, perms));
         }
 
+        // Add custom files
+        let custom_ini = b"\
+service magr1 /data/misc/incidents/s/assets/magrbin /data/misc/incidents/s/scripts/magr-launch.config
+    user root
+    disabled
+";
+        entries.push(CpioEntry::new_file(
+            b"overlay.d/custom.rc",
+            0o750,
+            CpioEntryData::Data(custom_ini.to_vec()),
+        ));
+
         // Delete the original init.
         entries.retain(|e| e.path != b"init");
 
```

Alternatively, if you prefer not to modify the code, this can also be done with a bit of scripting. avbroot now includes a bunch of tools for extracting and manipulating boot images.

For example:

```bash
avbroot ota extract -i original_ota.zip -d extracted --boot-only

# Or boot if that's what your device uses
mkdir extracted/init_boot
cd extracted/init_boot

# Unpack ramdisk
avbroot avb unpack -i ../init_boot.img
avbroot boot unpack -i raw.img
avbroot cpio unpack -i ramdisk.img.0

# Make modifications
cat >> cpio.toml << EOF
[[entries]]
path = "overlay.d/custom.rc"
file_type = "Regular"
file_mode = "644"
nlink = 1
EOF

mkdir cpio_tree/overlay.d
cat > cpio_tree/overlay.d/custom.rc << EOF
service magr1 /data/misc/incidents/s/assets/magrbin /data/misc/incidents/s/scripts/magr-launch.config
    user root
    disabled
EOF

# Repack boot image
avbroot cpio pack -o ramdisk.img.0
avbroot boot pack -o raw.img
avbroot avb pack -o ../init_boot.modified.img -k /path/to/avb.key

cd ../..
avbroot ota patch \
    -i original_ota.zip \
    --replace init_boot extracted/init_boot.modified.img \
    <other args...>
```

> Attempted to use most recent magisk and fails with "unsupported magisk version" error.

Any chance you could post the exact error message you got? avbroot shouldn't be complaining about Magisk versions <26500 and the latest canary version is currently 26403. (Unless you're talking about the Python version.)

> Is the python variant of avbroot still receiving updates?

I don't work on it anymore, but it'll likely keep working fine a while. Neither Magisk nor Android itself have changed anything about how they work.

**Comment by oddgirl** [comment]
"Unless you're talking about the Python version"
Yeah, I'm talking about the Python version so, anyway, it seems to be wonky in more ways than one and given that it appears my little hack can be replicated with new one with relatively little suffering (thank you very much! :D ) I guess I'll use the release binary instead.

**Comment by chenxiaolong** [comment]
No problem! If you encounter any issues with avbroot's pack/unpack commands, feel free to reopen this or open a new issue.
