### ISSUE TITLE
Invalid VBMeta header magic: [0, 0, 0, 0]

### ISSUE THREAD

**Issue by toilatoiok** [chenxiaolong/avbroot#258]
Hello friends !
I got the error : Invalid VBMeta header magic: [0, 0, 0, 0] , while trying to replace the system.img partition.
- Have you ever encountered this error? Can you tell me how to fix it?
- Thank you very much

**Comment by chenxiaolong** [comment]
Can you describe how you created your custom `system.img`? It sounds like the AVB metadata is missing.

If you didn't add the AVB metadata, you can do so either with `avbtool add_hashtree_footer` (harder if you don't already know the proper parameters for your device) or with avbroot:

```bash
# Extract original system.img
avbroot ota extract -i ota.zip

# Unpack AVB metadata from original system.img
avbroot avb unpack -i system.img

# Replace raw.img with your custom image

# Repack system.img using your custom image + the original AVB metadata
avbroot avb pack -i system.img
```

**Comment by toilatoiok** [comment]
- I did it your way and successfully replaced the system.img partition.
- But the problem is that after updating ota.zip, I get an error of invalid signature recognition.
- Maybe I missed another step, right?
- I hope you can guide me, thank you very much!

**Comment by chenxiaolong** [comment]
> I get an error of invalid signature recognition.

Can you post the exact error message or output you're getting? There shouldn't be any other steps needed.

**Comment by toilatoiok** [comment]
![photo_2024-02-08_02-37-13](https://github.com/chenxiaolong/avbroot/assets/51963834/3d5a02ad-a044-410d-afe2-1615e9d4484c)
You see an error image like this

**Comment by chenxiaolong** [comment]
Hmm, just to confirm, have you already followed the [initial setup](https://github.com/chenxiaolong/avbroot#initial-setup) steps? It seems like recovery mode is not using your custom key for validation.

**Comment by toilatoiok** [comment]
- Steps that I took:
- I am processing ota.zip for android box device.
- I unacked system.img then repacked it again.
- Re-pact ota.zip and install it and get a signature error.

**Comment by chenxiaolong** [comment]
Ah OK. For the initial install, you must flash with fastboot from the instructions I linked. Without that, recovery mode is using the OEM key to verify the signatures instead of your own key.

After the initial install with fastboot, you should be able to sideload further OTAs without a problem.

**Comment by toilatoiok** [comment]
That means only devices that have flashed the .img file can flash the ota.zip, right?
- Is there any other way to get the digital signature from the original ota.zip file to make a new valid ota.zip version?

**Comment by chenxiaolong** [comment]
> That means only devices that have flashed the .img file can flash the ota.zip, right?

That's correct. There is no way to work around that.

**Comment by toilatoiok** [comment]
Ah, but I saw someone edit the OTA and patch it using your avbroot tool and I successfully flashed that OTA on many other devices.

**Comment by chenxiaolong** [comment]
Hmm, if the other devices were able to flash modified OTAs without the fastboot step, then those devices likely have broken signature checks. That isn't supposed to work.

**Comment by toilatoiok** [comment]
> Hmm, if the other devices were able to flash modified OTAs without the fastboot step, then those devices likely have broken signature checks. That isn't supposed to work.

- Tôi đã nhìn thấy họ flash các tập tin .img ( dtb.img, boot.img ) thông qua "adnl" chip Amlogic.
- Liệu điều này có liên quan đến bước flash fastboot như bạn đã đề cập không ?
- Các flsh thông qua adnl phân tích cùng họ có thể được ký bằng công cụ avbroot của bạn ?
- Nếu bạn có thể chọn tôi xin cách liên lạc với bạn thông qua telegram được hay không ?

**Comment by chenxiaolong** [comment]
> I've seen them flash .img files ( dtb.img, boot.img ) through the Amlogic "adnl" chip.

Oh, as long as there's a way to flash `.img` files directly, that's fine. It doesn't need to be fastboot specifically.

In that case, for the initial setup:

1. Extract the patched OTA:

    ```bash
    avbroot ota extract \
        --input /path/to/ota.zip.patched \
        --directory extracted
    ```

2. Use the amlogic tool you mentioned to flash each `.img` file. (Sorry, I'm not familiar with the tool so I don't know how it's done.)

After that, you should be able to sideload your patched OTAs.

**Comment by toilatoiok** [comment]
One difficulty that occurs is that when I flash img files other than "boot.img, dtb.img", the remaining partitions all report errors because the bootloader has not been unlocked.
- If possible, I can send you those command lines

**Comment by chenxiaolong** [comment]
If that's the case, I think you're out of luck :slightly_frowning_face: I don't have any more suggestions for what else to try.

**Comment by toilatoiok** [comment]
- I saw in the other party's code that they loaded the file (boot.img, dtb.img), then they updated the ota.zip file that was patched with your avbroot tool!
- So is there any direction for me?

**Comment by chenxiaolong** [comment]
> I saw in the other party's code that they loaded the file (boot.img, dtb.img), then they updated the ota.zip file that was patched with your avbroot tool!

It might work on those devices if the OTA certificates are stored inside `boot.img`. (Most devices are not like this--they usually store the certificates in `recovery.img` or `vendor_boot.img`.)

You can check if your device is like this by extracting the ramdisk from `boot.img`:

```
avbroot boot unpack -i boot.img
avbroot cpio unpack -i ramdisk.img.0
```

If `cpio_tree/system/etc/security/otacerts.zip` exists, then the OTA certificate is stored in `boot.img`.

**Comment by toilatoiok** [comment]
> > I saw in the other party's code that they loaded the file (boot.img, dtb.img), then they updated the ota.zip file that was patched with your avbroot tool!
> 
> It might work on those devices if the OTA certificates are stored inside `boot.img`. (Most devices are not like this--they usually store the certificates in `recovery.img` or `vendor_boot.img`.)
> 
> You can check if your device is like this by extracting the ramdisk from `boot.img`:
> 
> ```
> avbroot boot unpack -i boot.img
> avbroot cpio unpack -i ramdisk.img.0
> ```
> 
> If `cpio_tree/system/etc/security/otacerts.zip` exists, then the OTA certificate is stored in `boot.img`.
I found the otacerts.zip certificate in cpio_tree/system/etc/security/

**Comment by chenxiaolong** [comment]
Nice, if that's the case, you might be able to try the approach you described (flashing patched `boot.img` via the amlogic tool and then sideloading the OTA). I can't guarantee it'll work--it's very unusual--but I guess it's worth trying.

**Comment by toilatoiok** [comment]
> Nice, if that's the case, you might be able to try the approach you described (flashing patched `boot.img` via the amlogic tool and then sideloading the OTA). I can't guarantee it'll work--it's very unusual--but I guess it's worth trying.

- I'm talking about my friend's boot.img file, which they flashed before updating their ota.zip.
- But now after unpacking the ota.zip and repacking it, how do I sign the boot.img file to make it valid? I still don't really understand that issue with the avbroot tool. Could you please guide me to understand better? Thank you !

**Comment by chenxiaolong** [comment]
You can use `avbroot ota extract -i ota.zip.patched` to extract the `boot.img` from the patched OTA. (avbroot automatically signs `boot.img` with your key during `avbroot ota patch`.)

**Comment by toilatoiok** [comment]
> You can use `avbroot ota extract -i ota.zip.patched` to extract the `boot.img` from the patched OTA. (avbroot automatically signs `boot.img` with your key during `avbroot ota patch`.)

- I want to ask again, is the order like this?
1. Unpack ota.zip
2. Replace what you want in " system.img, or product.img...".
3. Then patch again with avb.key, ota.key , ota.crt.

- If it's in that order, it has nothing to do with the signature we found in the boot.img file - the file that will be flashed before updating the ota.zip.patch in recovery (otacerts.zip).

**Comment by chenxiaolong** [comment]
I think it should be like this:

1. Unpack ota.zip.
2. Make modifications to `system.img`/`product.img`/whatever.
3. Patch with `avbroot ota patch`. Both `boot.img` and the whole OTA zip will be signed with your own key.
4. Extract `boot.img` from the patched OTA. This `boot.img` contains a modified `system/etc/security/otacerts.zip` with your key, so that your patched OTAs can be sideloaded.
5. Flash `boot.img`.
6. Reboot to recovery mode to sideload patched OTA.

**Comment by toilatoiok** [comment]
Thank you very much, I did it your way! Thank you again!
