### ISSUE TITLE
avb root not patching lineage os zip file for redfin pixel 5

### ISSUE THREAD

**Issue by kullanici32** [chenxiaolong/avbroot#262]
for redfin Pixel 5 
 6.762s  INFO Replacing zip entry: META-INF/com/android/otacert
  6.762s  INFO Copying zip entry: apex_info.pb
  6.762s  INFO Copying zip entry: care_map.pb
  6.762s  INFO Patching zip entry: payload.bin
  6.762s  INFO Extracting from original payload: vendor_boot
  6.995s  INFO Extracting from original payload: boot
  7.159s  INFO Extracting from original payload: system
 10.045s  INFO Extracting from original payload: vbmeta_system
 10.045s  INFO Extracting from original payload: vbmeta
 10.045s  INFO Patching boot images: boot, vendor_boot
 11.091s  INFO Patching system image: system
 12.438s  INFO Patched otacerts.zip offsets in system: [331485184..331486720]
 12.438s  INFO Patching vbmeta images: vbmeta_system, vbmeta
 12.534s ERROR Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Verified boot is disabled by vbmeta's header flags: 0x3

**Comment by chenxiaolong** [comment]
The OTA you're patching has AVB's checks disabled. Please see https://github.com/chenxiaolong/avbroot#clearing-vbmeta-flags for documentation on what to do.
