### ISSUE TITLE
HashTree stays disabled after clearing vbmeta flags.

### ISSUE THREAD

**Issue by woshiahmedc** [chenxiaolong/avbroot#270]
I've patched Project Elixir ROM with avbroot for Pixel 6. I've forcly enabled AVB by using `--clear-vbmeta-flags` When I  check dmesg it returns me :
```
[    1.222762] init: [libfs_avb] Returning avb_handle with status: HashtreeDisabled
[    1.222772] init: [libfs_avb] AVB  HASHTREE disabled on: /system
[    1.225869] init: [libfs_avb] AVB HASHTREE disabled on: /system_ext
[    1.227604] init: [libfs_avb] AVB HASHTREE disabled on: /product
[    1.229367] init: [libfs_avb] AVB HASHTREE disabled on: /vendor
[    1.231079] init: [libfs_avb] AVB HASHTREE disabled on: /vendor_dlkm
``` 

I saw Issue #60  but the problem seems a little bit different from that. Thank you for your help

**Comment by chenxiaolong** [comment]
Can you post a link to the OTA? I can take a look after work today.

**Comment by Zahid-C** [comment]
Of course, That is the [OTA](https://private.projectelixiros.com/fourteen/oriole/ProjectElixir_4.1_oriole-14.0-20240312-1235-OFFICIAL.zip)

**Comment by chenxiaolong** [comment]
Thanks for the link. It looks like this is intended behavior with Project Elixir ROMs. They intentionally disable hashtree verification whenever the bootloader is unlocked (https://github.com/Project-Elixir/android_system_core/commit/b8534d3d691e7322f84b24cdc9032a5b7025aec0).

I would suggest proceeding with setting up avbroot and checking `dmesg` again once the bootloader is locked.

**Comment by Zahid-C** [comment]
Thank you for clarification and your help. Now libfs works without problems. It successfully returned `init: [libfs_avb] Returning avb_handle with status: Success`
