### ISSUE TITLE
[Request] docs: add alternative localizations

### ISSUE THREAD

**Issue by bugreportion** [chenxiaolong/avbroot#271]
Would be great to see description and instructions in different languages, so writing to you with a desire to find out if you are interested. If so, I am ready to translate your repo into Russian, but I have a question: where should I put the translated readme file (for example create a separate folder with the translated file?).

**Comment by chenxiaolong** [comment]
Thanks for offering to translate! Based on the conventions I've seen in other repos, I would suggest `README.<language>.md` (eg. `README.ru.md`).
