### ISSUE TITLE
Build universal binary for macOS

### ISSUE THREAD

**Issue by UjuiUjuMandan** [chenxiaolong/avbroot#278]
The [latest release](https://github.com/chenxiaolong/avbroot/releases/tag/v3.1.2) is missing x86_64 apple darwin binary.

We should build an universal binary for macOS using lipo like in [james58899/hath-rust](https://github.com/james58899/hath-rust/blob/main/.github/workflows/build.yml).

**Comment by chenxiaolong** [comment]
Thanks for the info. It looks like the switch happened due to Github upgrading the Mac machines they use for running the Actions workflows.

I'll look into the workflow you linked.
