### ISSUE TITLE
How to replace the partition when rooting a device with init_boot

### ISSUE THREAD

**Issue by dumet12138** [chenxiaolong/avbroot#281]
For devices shipped with Android 13 or higher, the ramdisk is in init_boot. If I manually patch init_boot, how do I need to replace the partition? Should I use --prepatched or --replace to replace a partition

**Comment by chenxiaolong** [comment]
If your patches are for enabling root access, use `--prepatched`. If you're editing other files in the ramdisk that are unrelated to root access, use `--replace` (avbroot will apply the root patches for you in this scenario.)
