### ISSUE TITLE
brick

### ISSUE THREAD

**Issue by joyX3** [chenxiaolong/avbroot#290]
Hello 1+ 11
I got the working system crDroid using avbroot. When I locked the bootloader i got:

The current image(boot/recovery) have been destroyed and can not boot 
Please flash the correct image or contact customer seevice to fix it 

Is it possible to unbrick device?

**Comment by chenxiaolong** [comment]
You'll have to unlock the bootloader again. OnePlus devices generally don't work unless it's an old device where you're able to downgrade the bootloader to the Android 11 version. They removed support for using custom signing keys in newer bootloader versions.

**Comment by joyX3** [comment]
How can I open bootloader if I dont have fastboot? Wich new decices works well?

**Comment by chenxiaolong** [comment]
As far as I'm aware (from other folks with OnePlus devices), you should be able to reboot back into fastboot mode by holding down the proper buttons when turning on the device.

> Wich new decices works well, exept pixel? It will be very nice to get list of supported devices

There's no way to know which devices work unless somebody tries it. No company besides Google documents whether their devices support custom keys.

If you're looking for new devices, I don't know of any device besides Pixels that properly support custom AVB keys.

**Comment by joyX3** [comment]
1+ 11 doesnt have fastboot mode, so to make avbroot is to make it brick. Edl doesnt work correctly. Let it know to the guys wont try it

**Comment by chenxiaolong** [comment]
How was the bootloader unlocked initially? Does OnePlus use something besides fastboot for that now?

**Comment by chenxiaolong** [comment]
I've created a new pinned issue (#299) to track supported devices. I've linked to this report there so that other folks know that OnePlus devices could unfortunately become bricked.

**Comment by joyX3** [comment]
> How was the bootloader unlocked initially? Does OnePlus use something besides fastboot for that now?

It has fastbootd mode. It original recovery mode. After singing custom keys and locking bootloader this mode doesnt appear. In some time I will check all possible EDL flashes if something will work I will update. For now I tried some and it doesn't work

**Comment by EraserCN** [comment]
If abl doesn't match or updated to A14-based Vendor, you won't be able to boot into fastboot on 1+ 11

**Comment by zx-ecco** [comment]
has anyone checked if EDL won't work?

**Comment by Vojtak42** [comment]
> has anyone checked if EDL won't work?

Currently none free method works (at least for Nord 4), though I got it flashed for free in the official service as a part of warranty.

But I didn't try to flash avbroot, from what I read and understood there are different types of hard bricks. Eg, some might blow ARB fuse, so it might depend.
