### ISSUE TITLE
[Enhancement] Ability to bake custom priv-apps directly into the ota package

### ISSUE THREAD

**Issue by radioaddition** [chenxiaolong/avbroot#315]
I think it'd be useful for things like preinstalling custota without relying on a root solution (or having to manually add it with afsr). It also makes things simpler for those wishing to include os modifications, but not a root solution.

Original suggestion was adding magisk modules directly to the ota, followed by my realization that someone would try to install something like lsposed without a root solution and brick their device. I do think that full module support would be cool though if used with discretion (for example imagine a working v4a installation or ACC on an unrooted device)

**Comment by chenxiaolong** [comment]
Thanks for the suggestion! As cool as it would be to have module support without root, I likely won't implement support for making OS modifications directly in avbroot beyond what is necessary to securely boot the OS. I prefer to keep avbroot as simple as possible, but (hopefully) flexible enough that others can build scripts on top of it to make whatever modifications they like.
