### ISSUE TITLE
Hard bricked Pixel 7? "No valid operating system could be found. The device will not boot"

### ISSUE THREAD

**Issue by jordanss1** [chenxiaolong/avbroot#318]
Phone is Pixel 7 using GrapheneOS.

Hello I'm back again unfortunately. I was playing around with Magisk on another user profile and I believe my admin magisk on root profile was somehow connected to this profile. I decided to uninstall Magisk on the this user profile and this led to my current situation. The device is stuck with the message of the title of this issue. I thought the additional user had a totally different setup than the main profile. Guess I was wrong.

I am aware the custom AVB public key needs to be wiped before I can even proceed but if I'm honest I think I just hard bricked my phone :(

Tried to reboot into bootloader 
   `error: no devices/emulators found`

The device keeps bootlooping with the same message on the screen. I think I'm screwed.

**Comment by chenxiaolong** [comment]
As long as you didn't disable the `Allow OEM unlocking` option in Android's settings, this should be recoverable.

When you say it keeps bootlooping, is that during normal boot? Are you able to get into bootloader mode with power + volume down?

**Comment by pascallj** [comment]
> As long as you didn't disable the `Allow OEM unlocking` option in Android's settings, this should be recoverable.

About that: as you have used CalyxOS before, have you followed the notes in the Readme about CalyxOS and re-enabled OEM unlocking?

**Comment by bugreportion** [comment]
> I decided to uninstall Magisk on the this user profile and this led to my current situation. 

It looks like you "deleted Magisk" via a button in the Magisk Manager directly, which means that this priveleged app replaced your kernel with modified one. This was stated in the [warnings section.](https://github.com/chenxiaolong/avbroot#warnings-and-caveats)

By the way, @chenxiaolong, maybe we should also mention about the prohibition of Magisk/other root solutions removal through its Manager just for clarity, since the update process was described?

> `error: no devices/emulators found`

Look into this: [Google USB Driver](https://developer.android.com/studio/run/win-usb)

> The device keeps bootlooping with the same message on the screen.

This is expected behavior when using an incorrectly signed kernel, which doesn't mean that you hardbricked. But the data now have to be erased because you need to unlock the bootloader.

**Comment by chenxiaolong** [comment]
> By the way, @chenxiaolong, maybe we should also mention about the prohibition of Magisk/other root solutions removal through its Manager just for clarity, since the update process was described?

Yeah, that's a good idea. I actually wasn't aware that this removal functionality existed.

**Comment by jordanss1** [comment]
> As long as you didn't disable the Allow OEM unlocking option in Android's settings, this should be recoverable.

Yes I used the OEMUnlockOnBoot module so that was always ok. Sorry guys, I kind of freaked when it happened from the research I did it seemed hard-bricked and I wanted help immediately. Everything is ok but I really appreciate everyone who tried to help!

**Comment by jordanss1** [comment]
Hi @chenxiaolong am I able to ask that all my issues are removed including this one?

**Comment by jordanss1** [comment]
Thanks for doing what I asked. I hate to be picky but can you fully delete the whole issue?

**Comment by chenxiaolong** [comment]
Sorry, I'm happy to delete individual comments and the edit history from them, but without a good reason, I'm not going to delete the entire issue when there are things that link to it or when other folks have commented too.
