### ISSUE TITLE
graphenos pixel 7pro

### ISSUE THREAD

**Issue by joyX3** [chenxiaolong/avbroot#320]
When I trying make patch graphene I get error Missing entries in OTA zip: META-INF/com/android/otacert, payload.bin, payload_properties.txt

**Comment by chenxiaolong** [comment]
It sounds like you might've accidentally downloaded the factory image instead of the OTA.

**Comment by secretmango** [comment]
I can confirm that the entire image building process works for a GrapheneOS OTA image.

Flashing that image... is a different topic. This might be difficult
