### ISSUE TITLE
Magisk app install

### ISSUE THREAD

**Issue by RickMarijn** [chenxiaolong/avbroot#326]
I just finished installing Magisk using your program, but the app is prompting me to finalize the installation. Is this safe to do? Should I ignore this popup? I REALLY don't want to brick this phone I just got it

**Comment by chenxiaolong** [comment]
Was this the message?
> Your device needs additional setup for Magisk to work properly. Do you want to proceed and reboot?

If so, then that's safe. In general, as long as the OEM unlocking checkbox remains checked, you can't hard brick and it'll always be possible to unlock the bootloader again and start fresh.

**Comment by RickMarijn** [comment]
Alright, great. Just want to say that this project is absolutely amazing and I'm really grateful for not only the software but also the support 😁
