### ISSUE TITLE
Warning: skip copying avb_custom_key image avb footer (avb_custom_key partition size: 0, avb_custom_key image size: 1032).

### ISSUE THREAD

**Issue by alexchiu100014** [chenxiaolong/avbroot#327]
Nothing Phone (2) here.

Warning: skip copying avb_custom_key image avb footer (avb_custom_key partition size: 0, avb_custom_key image size: 1032).

"Your device has loaded a different operating system" would appear while boot.
Is this meant not supported, or I need to flash other partition?

**Comment by pixincreate** [comment]
No. The message `Your device has loaded a different operating system` means that your device is working as expected.

**Comment by alexchiu100014** [comment]
What I expected is "Bootloader Locked" in Key Attestation Demo and Pass "Strong" in Play Integrity Check.

But I didn't saw "Bootloader Locked" in Key Attestation Demo
And Play Integrity only pass "Basic"
Is this project meant or have the effect to pass these checks, or it just let me lock my bootloader with a modified or custom rom?

(Sorry, I really want to post screenshots, but my Telegram got force logout without any attention and pictures are gone.)

**Comment by pascallj** [comment]
In regards to Play Integrity. Basic is the correct verdict by default at the moment. Locking with a modified or custom rom is indeed the (only) goal. If you want to know more, you can search the (closed) issues for "play integrity".

**Comment by alexchiu100014** [comment]
> In Key Attestation Demo app, you should see `signed with custom key`. With respect to play integrity, I really have no idea on that as the device that i daily drive do not have GMS installed and most of the app that i use work without GMS. However, since you've locked the bootloader, you hardware attestation should pass (you can check that with GrapheneOS's Auditor app), and again, not sure about GMS's `STRONG` check.

![d73b8b9b7abe4b2e947c504c03f30089](https://github.com/user-attachments/assets/aa89cd18-d4bb-42d2-a82d-40e6076b4358)

**Comment by alexchiu100014** [comment]
After disabled "Attest device props" :
![0a1b7cbadb174ec48cc1c07ee543a167](https://github.com/user-attachments/assets/e9ad76db-2b3a-4d18-8840-0539f137cb2c)

**Comment by pixincreate** [comment]
`Root of trust set by user` is expected, yes.

> https://github.com/chenxiaolong/avbroot/issues/327#issuecomment-2273622978

I'm not sure.

**Comment by chenxiaolong** [comment]
Yeah, avbroot won't help at all for passing Play Integrity. Hardware attestation will report that the OS is signed by your own key, which Google does not trust for `STRONG` integrity.

**Comment by xabolcs** [comment]
#299 can be updated with `pong`!  🙏

**Comment by Rajala1404** [comment]
From where did you get a OTA.zip with a payload.bin?
