### ISSUE TITLE
Signature verification failed in recovery

### ISSUE THREAD

**Issue by rm5319** [chenxiaolong/avbroot#350]
I just patched a new update and tried to install it using adb sideload and I'm getting the following error on my phone 

```
ERROR: recovery: failed to verify whole-file signature
Update package verification took 133.6 s (result 1).
ERROR: recovery: Signature verification failed
ERROR: recovery: error: 21

Install from ADB completed with status 2.
Installation aborted.
```

I'm 100% sure I used the same keys.

**Comment by pascallj** [comment]
I am not sure if it can cause these errors, but is there any change you might have switched the ota and avb keys?

**Comment by chenxiaolong** [comment]
While booted into Android, can you make a copy of your `vendor_boot` partition?
```bash
adb shell su -c 'dd if=/dev/block/by-name/vendor_boot$(getprop ro.boot.slot_suffix) of=/sdcard/vendor_boot.img'
```
And then on a computer:
```bash
adb pull /sdcard/vendor_boot.img
avbroot boot unpack -i vendor_boot.img
avbroot cpio unpack -i ramdisk.img.0
```
You should see a `cpio_tree/system/etc/security/otacerts.zip` file in there that contains an `ota.x509.pem` file inside. Make sure that matches your `ota.crt`.

**Comment by rm5319** [comment]
It does match

**Comment by chenxiaolong** [comment]
If that's the case, I have no idea what would be going on. You'll probably need to try and find the log messages prior to `failed to verify whole-file signature`.

If recovery mode allows adb access, you can `adb pull /tmp/recovery.log` after attempting to sideload. If not, then you can only look at the logs on the device's screen with the menu option (volume buttons to scroll).

**Comment by rm5319** [comment]
I couldn't get adb in recovery to work and the logs it gave are all it spat out.

**Comment by chenxiaolong** [comment]
Hmm, under recovery mode's `View recovery logs` on-screen option, there are no additional messages?

If so, I don't really have any idea how to troubleshoot this.

**Comment by chenxiaolong** [comment]
@luxqaoa I've moved your report to #356. Although there are similar symptoms, the root cause is different (and is indeed related your device putting recovery mode stuff in `boot` instead of `vendor_boot`).

**Comment by chenxiaolong** [comment]
@rm5319 Although I don't know what originally caused the problem on your device, if you're certain that the new OTA you're flashing is good, you should be able to use the same workaround as for #356 to actually install it: https://github.com/chenxiaolong/avbroot/pull/357#issuecomment-2365343050
