### ISSUE TITLE
Failed to boot into userspace fastboot

### ISSUE THREAD

**Issue by luketeam5** [chenxiaolong/avbroot#352]
Hello,

I may be a bit confused here, but I'm encountering an issue on my Pixel 8 Pro after following the `fastboot flashall --skip-reboot` steps outlined in the [Initial setup](https://github.com/chenxiaolong/avbroot?tab=readme-ov-file#initial-setup). The phone installs everything up to `vendor_kernel_boot_a`, and then it prints `Rebooting into fastboot` before rebooting into `fastbootd`. After that, it hangs at `< waiting for any device >`, and nothing further seems to happen.

If I try to reboot back into Fastboot, I receive the message `fastboot: error: Failed to boot into userspace fastboot; one or more components might be unbootable.` I've also tried experimenting with fastbootd, but that hasn’t resolved the issue.

I'm looking to get a GrapheneOS Rooted with Magisk working, so any assistance would be greatly appreciated! Thank you!

**Comment by chenxiaolong** [comment]
Any chance you're running Windows? My understanding is that on Windows, `fastbootd` mode might require [different drivers](https://developer.android.com/studio/run/win-usb) than normal `fastboot` mode.

**Comment by luketeam5** [comment]
Yup, running on Windows 11 as I didn't want to bother with using my desktop with Linux Mint on it

11 Sept 2024 01:06:26 Andrew Gunnerson ***@***.***>:

**Comment by chenxiaolong** [comment]
Ah, yeah, if that's the case, you'll probably have to install Google's drivers I linked to above. I don't think there's any way around it.

**Comment by luketeam5** [comment]
Okay, thanks for the help.
This solved the issue.
