### ISSUE TITLE
Patching without Recovery

### ISSUE THREAD

**Issue by aaronfhamilton** [chenxiaolong/avbroot#360]
Is it possible to create an OTA without a recovery partition in the OTA package? I previously tried adding a recovery image that was read off the device using QFIL (see https://github.com/chenxiaolong/avbroot/issues/328), but the patched OTA kept bricking the device.

After further digging, I found the device's existing recovery partition is missing the OTA keys (or at least there's no `res\keys` folder in the partition ram disk).

Could this be why the original OTA/payload.bin without `recovery.img` works, but adding it bricks the device?

This is the original device recovery image: https://drive.google.com/file/d/1C5AeEGetvfSNRP2PuZd8a3NFX67EOoeb/view?usp=sharing

Another strange finding: after flashing the original OTA (twice, for both slots), I verified both recovery_a.bin and recovery_b.bin were identical, yet the vbmeta footers differs between vbmeta.img and recovery.img. 

Shouldn't these be the same?

Recovery VBMeta Footer (read from device):
```
Footer version:           1.0
Image size:               67108864 bytes
Original image size:      27770880 bytes
VBMeta offset:            27770880
VBMeta size:              640 bytes
--
Minimum libavb version:   1.0
Header Block:             256 bytes
Authentication Block:     0 bytes
Auxiliary Block:          384 bytes
Algorithm:                NONE
Rollback Index:           0
Flags:                    0
Rollback Index Location:  0
Release String:           'avbtool 1.2.0'
Descriptors:
    Hash descriptor:
      Image Size:            27770880 bytes
      Hash Algorithm:        sha256
      Partition Name:        recovery
      Salt:                  e916a187112a85969dace41a88e9d30b52df2e55b2ce0251e9cf5e3d7c3ec194
      Digest:                69005a4509e83aff8a5d2d5ecd25e2dd794f83f21f388ad1f1581405f8cad82a
      Flags:                 0
    Prop: com.android.build.recovery.fingerprint -> 'qti/sdm660_64/sdm660_64:13/S10A_123/jiangds05311612:user/release-keys'
```

vbmeta.img:
```
Minimum libavb version:   1.0
Header Block:             256 bytes
Authentication Block:     576 bytes
Auxiliary Block:          3584 bytes
Public key (sha1):        2597c218aae470a130f61162feaae70afd97f011
Algorithm:                SHA256_RSA4096
Rollback Index:           0
Flags:                    0
Rollback Index Location:  0
Release String:           'avbtool 1.2.0'
Descriptors:
    Chain Partition descriptor:
      Partition Name:          vbmeta_system
      Rollback Index Location: 2
      Public key (sha1):       cdbb77177f731920bbe0a0f94f84d9038ae0617d
    Prop: com.android.build.boot.os_version -> '13'
    Prop: com.android.build.boot.fingerprint -> 'qti/sdm660_64/sdm660_64:13/S10A_123/jiangds05071710:user/release-keys'
    Prop: com.android.build.boot.security_patch -> '2022-12-05'
    Prop: com.android.build.boot.security_patch -> '2022-12-05'
    Prop: com.android.build.recovery.fingerprint -> 'qti/sdm660_64/sdm660_64:13/S10A_123/jiangds05071710:user/release-keys'
    Prop: com.android.build.vendor.os_version -> '13'
    Prop: com.android.build.vendor.fingerprint -> 'qti/sdm660_64/sdm660_64:13/S10A_123/jiangds05071710:user/release-keys'
    Prop: com.android.build.vendor.security_patch -> '2022-12-05'
    Prop: com.android.build.vendor.security_patch -> '2022-12-05'
    Prop: com.android.build.dtbo.fingerprint -> 'qti/sdm660_64/sdm660_64:13/S10A_123/jiangds05071710:user/release-keys'
    Hash descriptor:
      Image Size:            17330176 bytes
      Hash Algorithm:        sha256
      Partition Name:        boot
      Salt:                  e5d2d24a10119e91fcbe1671bf389004576cf247ab251aa820396fff43b70591
      Digest:                adc1f724e7eb60658b46e4afbb0f8257a17461f01098591130d9c58022499305
      Flags:                 0
    Hash descriptor:
      Image Size:            53735 bytes
      Hash Algorithm:        sha256
      Partition Name:        dtbo
      Salt:                  b32314b7bd2aa89bfac21f5f0e3208fbd459d1434e0d828189cd16722fdcce89
      Digest:                f4000cc1d48c00c5a332afcfd03ed8224af75686978d481fb27320282e8fb244
      Flags:                 0
    Hash descriptor:
      Image Size:            27774976 bytes
      Hash Algorithm:        sha256
      Partition Name:        recovery
      Salt:                  8ad31065a5a845c31c11b1bb47c41d2f134403105816578af3d21ce036289a36
      Digest:                156518a41536f193ec924f67f3a17fce71afb18a5e088325bfd93280b45d34fa
      Flags:                 0
    Hashtree descriptor:
      Version of dm-verity:  1
      Image Size:            1395658752 bytes
      Tree Offset:           1395658752
      Tree Size:             10997760 bytes
      Data Block Size:       4096 bytes
      Hash Block Size:       4096 bytes
      FEC num roots:         2
      FEC offset:            1406656512
      FEC size:              11124736 bytes
      Hash Algorithm:        sha1
      Partition Name:        vendor
      Salt:                  034c3fbce14b4a2926dd82df3d7316f4554bb5e525ab9e185fd74eab190909d6
      Root Digest:           c9fbc1d0e0a1c8c9757981559e9028922a77356b
      Flags:                 0
```

**Comment by chenxiaolong** [comment]
When you say it bricks the device, do you mean it can't boot into recovery mode? (or can it not boot into Android either?)

> After further digging, I found the device's existing recovery partition is missing the OTA keys (or at least there's no `res\keys` folder in the partition ram disk).

The OTA verification certs are stored in `system/etc/security/otacerts.zip` inside the ramdisk.

> Another strange finding: after flashing the original OTA (twice, for both slots), I verified both recovery_a.bin and recovery_b.bin were identical, yet the vbmeta footers differs between vbmeta.img and recovery.img.

Yeah, I noticed this in the original #328. I have no idea how the original recovery image is able to boot at all. The footer in `vbmeta` is what the bootloader actually reads and the digest doesn't match `recovery.img`.

Although another thing that's confusing me is this: if the original OTA doesn't contain a recovery image, how did `recovery_a` and `recovery_b` get restored to the original recovery image?

> Is it possible to create an OTA without a recovery partition in the OTA package?

Not easily. There's no option for this because I don't want it to be possible to flash something that can't accept further (patched) updates.

However, if you're willing to compile avbroot from source, you can skip the recovery partition patches by commenting out or removing this line:

https://github.com/chenxiaolong/avbroot/blob/af7262a0d2c52323ad9fb33b4d829ea428f9617f/avbroot/src/cli/ota.rs#L1307

**Comment by aaronfhamilton** [comment]
Since the device uses a USB connection to a CarPlay head unit for its display, I'm not able to determine what it's doing. The outward appearance was dead looking after the reboot when it finished the update.

I just powered up the device now after reading partitions from QFIL to compare against the OTA image, and now it seems to boot up again.

Is it possible a recovery image is embedded in the system partition and installed sometime after boot? I recall some of the MTCx head units did something similar where the recovery partition hash was stored in build.prop. Some post-boot operation compared this against the recovery image and reinstalled a new one when a difference was detected.

**Comment by chenxiaolong** [comment]
Ah that sucks. I'm not sure how to troubleshoot a device without a proper display like that.

> Is it possible a recovery image is embedded in the system partition and installed sometime after boot?

I suppose something like that is possible. I don't think your device is doing that though. I extracted both `system` and `vendor` and looked for all files >10MiB. None of them are related to recovery.

**Comment by aaronfhamilton** [comment]
After recompiling with line 1307 commented out, I was able to successfully unpack, repack, and patch an OTA. Thank you 100 times over!!!
