### ISSUE TITLE
Unable to enable Zygisk in Magisk

### ISSUE THREAD

**Issue by wonder75** [chenxiaolong/avbroot#365]
I created a patched OTA with avbroot and Magisk, flashed it, worked great, but I was unable to get root with Magisk. The root popup did not appear when an app requested root.

So i manualy patched boot.img from within Magisk, rebuilt the patched OTA with it and flashed that.

Root is working now, but sadly Zygisk is not. I can set it to enabled in Magisk settings. Magisk asks me to reboot. I reboot, but it is not active afterwards.

Any insight on how to get Zygisk working? Thank you very much for avbroot. Very cool tool!

**Comment by chenxiaolong** [comment]
Any chance you're using GrapheneOS? (Zygisk doesn't work there)

If not, I'm not really sure what else would break Zygisk. It's something that loads later in the boot process and is not part of `boot.img`.

**Comment by wonder75** [comment]
Yes, I am on GOS. So that would be the problem I guess. Thank you for answering so quickly. I guess you saved a lot of my time!

**Comment by chenxiaolong** [comment]
No problem! If you're willing to use a Magisk fork, pixincreate maintains one that adds support for Zygisk (and has no other changes, as far as I'm aware): https://github.com/chenxiaolong/avbroot/discussions/266#discussioncomment-8962621

**Comment by pixincreate** [comment]
hey there!

my fork of magisk at present has only one change that adds support for zygisk. i do plan to add allowlist (opposite of denylist) in the future (deferred)
