### ISSUE TITLE
Unknown boot image format error

### ISSUE THREAD

**Issue by lkernan** [chenxiaolong/avbroot#366]
Hi, 
I'm doing some playing around with an OTA image for my cars infotainment unit.   It's running Android 9.  

avbroot had no problems extracting the boot image, but when I do a boot info command I get the error:

leon@cartman:~/Downloads/avbroot$ ./avbroot boot info -d --log-level trace --input boot.img
  0.000s DEBUG cli=Cli { command: Boot(BootCli { command: Info(InfoCli { input: "boot.img" }), quiet: false, debug: true }), log_level: Level(Trace), log_format: Short }
  0.000s ERROR Failed to read boot image: "boot.img"

Caused by:
    Unknown boot image format

I've verified it has extracted the boot image correctly. 

My plan is to use the --rootless option since I mainly want to patch a file on the system partition.   
The car manufacturer put some firewall commands in to block ADB port 5555 on all interfaces so at the moment we don't have ADB and I need to patch them out.

One thing we do know is that they signed everything with the test-keys so that part is not a concern. 

A copy of the boot.img can be found here:
https://www.dropbox.com/scl/fi/6edbvsk43gcv17j4kkh51/boot.img?rlkey=pbgktsrbnyidzm7jmh0j5tti3&st=nehlziw7&dl=0

**Comment by chenxiaolong** [comment]
Thanks for uploading the `boot.img`! It looks like it's a u-boot FIT image, not a standard Android boot image. I've never seen this combo of AVB 2.0 + non-Android boot image format before.

It's unlikely I'll add support parsing these boot images. The format is quite a bit more complex to parse than standard Android boot images and it's not very common. The best I could do is maybe add a `--skip-ota-certs` option, which in addition to `--rootless`, would make avbroot not touch the boot image at all (it would only do AVB and OTA signing).

```
❯ mkimage -l boot.img 
Image contains unit addresses @, this will break signing
FIT description: U-Boot fitImage for Android 147456/4.9/auto2712m1v1-initramfs
Created:         Mon Sep 11 03:51:55 2023
 Image 0 (kernel@1)
  Description:  Linux kernel
  Created:      Mon Sep 11 03:51:55 2023
  Type:         Kernel Image
  Compression:  lz4 compressed
  Data Size:    11582667 Bytes = 11311.20 KiB = 11.05 MiB
  Architecture: ARM
  OS:           Linux
  Load Address: 0x40008000
  Entry Point:  0x40008000
  Hash algo:    sha256
  Hash value:   dfde18fbb1d1fee962eebad7a548de59ca95e6eaea403792496edbd8ded522a7
 Image 1 (ramdisk@1)
  Description:  Ramdisk Image
  Created:      Mon Sep 11 03:51:55 2023
  Type:         RAMDisk Image
  Compression:  uncompressed
  Data Size:    7961761 Bytes = 7775.16 KiB = 7.59 MiB
  Architecture: ARM
  OS:           Linux
  Load Address: 0x4a000000
  Entry Point:  0x4a000000
  Hash algo:    sha256
  Hash value:   def3f7cee122d0951c070626c7ff1d17b6a6d36f06d959ed5aea172fde4f8019
 Image 2 (fdt@1)
  Description:  Flattened Device Tree blob
  Created:      Mon Sep 11 03:51:55 2023
  Type:         Flat Device Tree
  Compression:  uncompressed
  Data Size:    98058 Bytes = 95.76 KiB = 0.09 MiB
  Architecture: ARM
  Load Address: 0x44000000
  Hash algo:    sha256
  Hash value:   1bb0072041178e90ad866eeffa7f6a08b4d57c94f777bec76b44f50e95167778
 Default Configuration: 'conf@1'
 Configuration 0 (conf@1)
  Description:  Boot Linux kernel with FDT blob
  Kernel:       kernel@1
  Init Ramdisk: ramdisk@1
  FDT:          fdt@1
  Sign algo:    sha256,rsa2048:dev
  Sign value:   unavailable
  Timestamp:    unavailable
```

```bash
dumpimage -T flat_dt -p 0 -o kernel boot.img
dumpimage -T flat_dt -p 1 -o ramdisk boot.img
dumpimage -T flat_dt -p 2 -o devicetree boot.img
```

**Comment by lkernan** [comment]
Thanks, at least for my purposes not touching the boot image at all would work.  As long as I can patch the file in /system/bin and put the payload.bin back together.

The whole system has been confusing the heck out of me.  Probably not a surprise it's based on a Mediatek SDK.
I'm reluctant to do too much since fastboot and recovery aren't easily accessible either.  
I think the uboot console might be on a serial console but that's probably going to require opening the unit.

**Comment by chenxiaolong** [comment]
Car infotainment systems definitely seem to be quite a bit more... interesting than phones.

I totally get the reluctance to try stuff. I haven't messed with my car's infotainment system because it can only boot into recovery or fastboot with `adb reboot`. There's no other physical way to do so, even if disassembled. People who've flashed an unbootable `boot.img` have had to manually reflash a working image with a NAND programmer to get things going again.

---

Please give #367 a try, which adds a new `--skip-recovery-ota-cert` option. Prebuilt binaries can be found at the bottom of this page: https://github.com/chenxiaolong/avbroot/actions/runs/11674513228?pr=367

**Comment by lkernan** [comment]
I've given it a try and it looks like it's still trying to do something with the boot.img

leon@cartman:~/Downloads/avbroot$ ./avbroot ota patch --input usb_ota_update.zip --key-ota testkey.x509.key --key-avb testkey.x509.key --cert-ota testkey.x509.crt --rootless --skip-recovery-ota-cert  --log-level trace
  0.000s DEBUG cli=Cli { command: Ota(OtaCli { command: Patch(PatchCli { input: "usb_ota_update.zip", output: None, key_avb: "testkey.x509.key", key_ota: "testkey.x509.key", cert_ota: "testkey.x509.crt", pass_avb_env_var: None, pass_avb_file: None, pass_ota_env_var: None, pass_ota_file: None, signing_helper: None, replace: [], root: RootGroup { magisk: None, prepatched: None, rootless: true }, magisk_preinit_device: None, magisk_random_seed: None, ignore_magisk_warnings: false, ignore_prepatched_compat: 0, skip_recovery_ota_cert: true, dsu: false, clear_vbmeta_flags: false, zip_mode: Streaming, boot_partition: None }) }), log_level: Level(Trace), log_format: Short }
  0.000s  WARN Not inserting OTA cert into recovery image; sideloading further updates may fail
  0.001s  INFO zip{entry="META-INF/com/android/otacert"}: Replacing zip entry: META-INF/com/android/otacert
  0.001s  INFO zip{entry="care_map.txt"}: Copying zip entry: care_map.txt
  0.001s  INFO zip{entry="checksoc.txt"}: Copying zip entry: checksoc.txt
  0.001s  INFO zip{entry="compatibility.zip"}: Copying zip entry: compatibility.zip
  0.001s  INFO zip{entry="payload.bin"}: Patching zip entry: payload.bin
  0.002s  INFO zip{entry="payload.bin"}:image{name="system"}: Extracting from original payload: system
  1.952s  INFO zip{entry="payload.bin"}:image{name="boot"}: Extracting from original payload: boot
  1.999s  INFO zip{entry="payload.bin"}:image{name="vbmeta"}: Extracting from original payload: vbmeta
  2.000s  INFO zip{entry="payload.bin"}: Candidate boot images: boot
  2.337s ERROR Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to patch boot images: boot
    2: Boot image error
    3: Unknown boot image format
leon@cartman:~/Downloads/avbroot$

**Comment by chenxiaolong** [comment]
Ah shoot, yeah, it was still loading boot images even when there was nothing to patch. ce87757fd1041fc4af8facee235e6211424241dd should fix that. New test build: https://github.com/chenxiaolong/avbroot/actions/runs/11686270136?pr=367

**Comment by lkernan** [comment]
Thanks, that got a lot further.   
Does that error mean I messed up the keys somewhere? 

leon@cartman:~/Downloads/avbroot$ ./avbroot ota patch --input usb_ota_update.zip --key-ota testkey.x509.key --key-avb testkey.x509.key --cert-ota testkey.x509.crt --rootless --skip-recovery-ota-cert
  0.000s  WARN Not inserting OTA cert into recovery image; sideloading further updates may fail
  0.001s  INFO Replacing zip entry: META-INF/com/android/otacert
  0.001s  INFO Copying zip entry: care_map.txt
  0.001s  INFO Copying zip entry: checksoc.txt
  0.001s  INFO Copying zip entry: compatibility.zip
  0.001s  INFO Patching zip entry: payload.bin
  0.001s  INFO Extracting from original payload: vbmeta
  0.002s  INFO Extracting from original payload: system
  1.880s  INFO Extracting from original payload: boot
  1.926s  INFO Candidate boot images: boot
  1.930s  INFO Patching system image: system
  4.566s  INFO Patched otacerts.zip offsets in system: [1474662400..1474663473]
  4.566s  INFO Patching vbmeta images: vbmeta
  4.900s ERROR Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: RSA public key exponent not supported: 3

**Comment by lkernan** [comment]
Thanks, it took a bit of figuring out but I got there in the end.   
I'm not the sharpest when it comes to public/private keys sometimes.

Comparing:
openssl rsa -pubin -in avb_public.key -noout -text
openssl rsa -in testkey_rsa2048.pem -noout -text
Didn't work since the testkey_rsa2048.pem was giving a private key result 

I finally realized I could do:
ssh-keygen -f testkey_rsa2048.pem -y -e -m pkcs8

And compare that to the avb_public.key which matched.   So yes, they are using testkey_rsa2048 for the AVB key.

**Comment by lkernan** [comment]
Well I haven't tried using the result yet, but looking good!

avbroot ota patch --input usb_ota_update.zip --key-ota testkey.x509.key --key-avb testkey_rsa2048.key --cert-ota ota.cert --rootless --skip-recovery-ota-cert

←[2m  0.003s←[0m ←[33m WARN←[0m Not inserting OTA cert into recovery image; sideloading further updates may fail
←[2m  0.035s←[0m ←[32m INFO←[0m Replacing zip entry: META-INF/com/android/otacert
←[2m  0.036s←[0m ←[32m INFO←[0m Copying zip entry: care_map.txt
←[2m  0.036s←[0m ←[32m INFO←[0m Copying zip entry: checksoc.txt
←[2m  0.036s←[0m ←[32m INFO←[0m Copying zip entry: compatibility.zip
←[2m  0.037s←[0m ←[32m INFO←[0m Patching zip entry: payload.bin
←[2m  0.039s←[0m ←[32m INFO←[0m Extracting from original payload: system
←[2m 30.722s←[0m ←[32m INFO←[0m Extracting from original payload: boot
←[2m 31.199s←[0m ←[32m INFO←[0m Extracting from original payload: vbmeta
←[2m 31.202s←[0m ←[32m INFO←[0m Candidate boot images: boot
←[2m 31.208s←[0m ←[32m INFO←[0m Patching system image: system
←[2m 49.066s←[0m ←[32m INFO←[0m Patched otacerts.zip offsets in system: [1474662400..1474663473]
←[2m 49.066s←[0m ←[32m INFO←[0m Patching vbmeta images: vbmeta
←[2m 49.073s←[0m ←[32m INFO←[0m Compressing partial image: system: [1474662400..1474663473, 2641915904..2683782144, 2684354496..2684354560]
←[2m 56.079s←[0m ←[32m INFO←[0m Compressing full image: vbmeta
←[2m 56.081s←[0m ←[32m INFO←[0m Generating new OTA payload
←[2m 58.961s←[0m ←[32m INFO←[0m Patching zip entry: payload_properties.txt
←[2m 58.961s←[0m ←[32m INFO←[0m Generating new OTA metadata
←[2m 58.965s←[0m ←[32m INFO←[0m Verifying metadata offsets
←[2m 58.970s←[0m ←[32m INFO←[0m Successfully patched OTA

**Comment by lkernan** [comment]
I'm not sure if I've made another mistake but the system doesn't like the update I generated.  
I'm getting the error:  Bad payload format -- invalid delta magic.

That was after generating an image like above, except I'd extracted system.img and modified it first.

avbroot ota patch --input usb_ota_update.zip --key-ota testkey.x509.key --key-avb testkey_rsa2048.key --cert-ota testkey.x509.cert --rootless --skip-recovery-ota-cert --replace system system.img

←[2m  0.000s←[0m ←[33m WARN←[0m Not inserting OTA cert into recovery image; sideloading further updates may fail
←[2m  0.004s←[0m ←[32m INFO←[0m Replacing zip entry: META-INF/com/android/otacert
←[2m  0.005s←[0m ←[32m INFO←[0m Copying zip entry: care_map.txt
←[2m  0.005s←[0m ←[32m INFO←[0m Copying zip entry: checksoc.txt
←[2m  0.005s←[0m ←[32m INFO←[0m Copying zip entry: compatibility.zip
←[2m  0.006s←[0m ←[32m INFO←[0m Patching zip entry: payload.bin
←[2m  0.007s←[0m ←[32m INFO←[0m Extracting from original payload: vbmeta
←[2m  0.011s←[0m ←[32m INFO←[0m Opening external image: system: "system.img"
←[2m  0.011s←[0m ←[32m INFO←[0m Extracting from original payload: boot
←[2m  0.331s←[0m ←[32m INFO←[0m Candidate boot images: boot
←[2m  0.337s←[0m ←[32m INFO←[0m Patching system image: system
←[2m 33.200s←[0m ←[32m INFO←[0m Patched otacerts.zip offsets in system: [1474662400..1474663473]
←[2m 33.200s←[0m ←[32m INFO←[0m Patching vbmeta images: vbmeta
←[2m 33.208s←[0m ←[32m INFO←[0m Compressing full image: vbmeta
←[2m 33.210s←[0m ←[32m INFO←[0m Compressing full image: system
←[2m121.090s←[0m ←[32m INFO←[0m Generating new OTA payload
←[2m125.008s←[0m ←[32m INFO←[0m Patching zip entry: payload_properties.txt
←[2m125.009s←[0m ←[32m INFO←[0m Generating new OTA metadata
←[2m125.015s←[0m ←[32m INFO←[0m Verifying metadata offsets
←[2m125.020s←[0m ←[32m INFO←[0m Successfully patched OTA

**Comment by lkernan** [comment]
Nevermind, I just saw issue #328 which had the same problem.
Added the --zip-mode seekable and the car accepted the update.

It still didn't work, looks like the AB update did it's job and booted the old one. Will have to dig into that a little more now.

**Comment by chenxiaolong** [comment]
Just to double check: when `system.img` was edited, was it re-signed? (eg. doing `avbroot avb unpack -i system.img` -> edit `raw.img` -> `avbroot avb pack -o system.img -k testkey_rsa2048.key`)

You can also verify with `avbroot ota verify -i <name>.patched`.

**Comment by lkernan** [comment]
I did the unpack / edit raw.img / repack but I didn't add the -k testkey_rsa2048.key
Gave it a try now and it didn't make any difference.

avbroot ota verify doesn't work, it stops as soon as it hits the unknown boot image format.

**Comment by chenxiaolong** [comment]
Ah okay, if `avbroot avb pack` didn't fail without `-k testkey_rsa2048.key`, it means `system.img` isn't signed (instead, its checksum is stored in `vbmeta.img`, which is signed).

> avbroot ota verify doesn't work, it stops as soon as it hits the unknown boot image format.

Crap, yeah, I'll need to add a flag to skip the otacerts check there.

**Comment by lkernan** [comment]
I did a test with the new version:
avbroot ota verify --skip-recovery-ota-cert --input usb_ota_update.zip
←[2m  0.000s←[0m ←[32m INFO←[0m Verifying whole-file signature
←[2m  2.012s←[0m ←[31mERROR←[0m Zip error

Caused by:
    specified file not found in archive

the file contains the same as usual:
`META-INF folder
care_map.txt
checksoc.txt
compatibility.zip
payload.bin
payload_properties.txt`

If it helps, you can get a copy of the ota zip file on Google Drive:
https://drive.google.com/file/d/1b8cZUbDz7s_AiolRdLy5s5GEpyAaRG4X/view

**Comment by chenxiaolong** [comment]
> avbroot ota verify --skip-recovery-ota-cert --input usb_ota_update.zip

I think there might've been a small typo there. Is that running against the unpatched zip? It should accept a patched one just fine.

---

Thanks for uploading the original OTA. I can reproduce the error and it looks like this original OTA has a couple of oddities:

* `META-INF/com/android/metadata.pb` is missing. This is likely just due to the Android version being old. I can work around this pretty easily (`avbroot ota patch` already does).
* `payload.bin`'s signature data structure has the `unpadded_signature_size` field unset. I'll need to poke around and see what that means and figure out how to handle it.

I'll look into it more after work today.

**Comment by chenxiaolong** [comment]
With #373 and #374 (https://github.com/chenxiaolong/avbroot/actions/runs/11750595450?pr=374), `avbroot ota verify` can now verify the original `usb_ota_update.zip`.

**Comment by lkernan** [comment]
Thanks, I've been able to verify both unpatched and patched OTAs now.

I can install these and Update_Engine has no problem with them.  But when it reboots, the system hasn't changed at all.
I've simplified things right down and I'm not even trying to replace anything.   

I can take a known good OTA, run it through avbroot, it passes all the checks and installs, but after a restart, no change and the boot slot is the same as before in the kernel.log.   
If I take the same OTA zip without patching, it applies fine and the system boots from the other slot. 

`avbroot ota patch --input usb_ota_update.zip --key-ota .\keys\testkey.x509.key --key-avb .\keys\testkey_rsa2048.key --cert-ota .\keys\testkey.x509.cert --rootless --skip-recovery-ota-cert --zip-mode seekable`
Runs and generates a file that's a few MB larger than before but looks ok.

The logcat doesn't show anything out of the ordinary.   I'd like to get some more specific logs but I haven't found any.  

Starts out with 
`11-09 11:41:09.419  2438  2438 I update_engine: [1109/114109.419095:INFO:update_attempter_android.cc(246)] Using this install plan:`
`11-09 11:41:09.419  2438  2438 I update_engine: [1109/114109.419314:INFO:install_plan.cc(83)] InstallPlan: new_update, version: , source_slot: B, target_slot: A, url: file:///storage/E68C-27EF/usb_ota_update.zip, payload: (size: 958623196, metadata_size: 87786, metadata signature: , hash: ACDF4067F17FA645706BC2013C03615568D35C416C45901C3B6E33031D2EAD35, payload type: unknown), hash_checks_mandatory: true, powerwash_required: false, switch_slot_on_reboot: true, run_post_install: true`

The logcat contains this at the end just prior to the reboot.  Everything seemed happy.

`11-09 11:44:39.768  2115  2115 I bootctrlHAL: emmc_set_active_boot_part`
`11-09 11:44:39.769  2115  2115 E bootctrlHAL: Current boot part is boot2, need switch to 1`
`11-09 11:44:39.774  2438  2438 I update_engine: [1109/114439.774262:INFO:postinstall_runner_action.cc(363)] All post-install commands succeeded`
`11-09 11:44:39.774  2438  2438 I update_engine: [1109/114439.774684:INFO:action_processor.cc(116)] ActionProcessor: finished last action PostinstallRunnerAction with code ErrorCode::kSuccess`
`11-09 11:44:39.774  2438  2438 I update_engine: [1109/114439.774745:INFO:update_attempter_android.cc(428)] Processing Done.`
`11-09 11:44:39.775  2438  2438 I update_engine: [1109/114439.775220:INFO:update_attempter_android.cc(436)] Update successfully applied, waiting to reboot.`


One thing I have found, was comparing the vbmeta.img files in a hex editor.   
The entry for the boot.img is identical (as it should be since we haven't touched it) but instead of ending in sha1 like the original, the patched version says sha256.  (screenshot attached)
Since the file hasn't been touched, why did that change?

I'm wondering if that's causing the system to reject that boot.img?
![vbmeta compare](https://github.com/user-attachments/assets/bed64e32-1409-467e-9441-d755ac314827)

**Comment by chenxiaolong** [comment]
In this case, the `sha256` you're seeing is actually for `system.img`. The hash algorithm field comes before the partition name in the binary format. It might be easier to diff the output of `avbroot avb info -i vbmeta.img`. This is what I get when I compare the original and patched ones:

```diff
--- /dev/fd/63	2024-11-08 21:16:46.877554882 -0500
+++ /dev/fd/62	2024-11-08 21:16:46.878554882 -0500
@@ -49,10 +49,10 @@
                     fec_num_roots: 2,
                     fec_offset: 2662727680,
                     fec_size: 21053440,
-                    hash_algorithm: "sha1",
+                    hash_algorithm: "sha256",
                     partition_name: "system",
                     salt: "672557b0f0cf32cdcb6841c9fbb4a9486118dc430d0487dddce9c9c8e186a053",
-                    root_digest: "ab06ffa1e35e9e6f5102948135820bb193bebb1b",
+                    root_digest: "c42f777d5ca8f32b032f105acb9f960aa10724ab9a1c0bcec2d7e6572d10d9c6",
                     flags: 0,
                     reserved: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                 },
```

I need to go eat dinner first, but afterwards, I'll see if I can make a test build that keeps sha1 instead of upgrading to sha256 (for `system.img`).

**Comment by chenxiaolong** [comment]
Please give #375 a try (https://github.com/chenxiaolong/avbroot/actions/runs/11752839174?pr=375).

**Comment by lkernan** [comment]
I gave it a try, still didn't want to boot off it.   
We seem to be getting closer though as the file sizes without replacing partitions are now within a 500KB of each other instead of 50MB.  

Looking at the info for patched and unpatched vbmeta files the difference now seems to be in the headers.  
I'm going to check the keys against the certificate again just in case.  

[orig-vbmeta.txt](https://github.com/user-attachments/files/17686249/orig-vbmeta.txt)
[patch-vbmeta.txt](https://github.com/user-attachments/files/17686250/patch-vbmeta.txt)

**Comment by chenxiaolong** [comment]
Yeah, looks like the `public_key` in your two files is different, so it's not being signed with the same key.

**Comment by lkernan** [comment]
Well I'm afraid unless the key turns up somewhere I'm out of ideas.   

It seems very odd to me that they didn't worry about security anywhere else, released test builds to production and sign everything else with AOSP keys.  Then go and do something different with the AVB key.  
I guess it's possible it's a key that's in the Mediatek SDK that I don't have access to at this point.   

Thanks for all the assistance anyway.  
At the least we might have helped other crappy Chinese Android products trying to do the same thing in some way!

**Comment by chenxiaolong** [comment]
That sucks...

I suspect they just took the path of least resistance. AOSP's build system automatically uses the test keys for signing OTAs by default, whereas avbtool doesn't default to a test key and requires it to be explicitly specified.

> At the least we might have helped other crappy Chinese Android products trying to do the same thing in some way!

Agreed!
