### ISSUE TITLE
AVB Root kernelsu

### ISSUE THREAD

**Issue by Mikras77** [chenxiaolong/avbroot#381]
Trying to follow the guide to prepatch grapheneOS ota with kernelSU and get this error when trying to flash the avb key:-

Warning: skip copying avb_custom_key image avb footer (avb_custom_key partition size: 0, avb_custom_key image size: 1032)

Can anyone help/advise?

(oh my phone is pixel 9 pro XL)

**Comment by chenxiaolong** [comment]
That is normal and expected on Pixel devices. You can safely ignore that warning.
