### ISSUE TITLE
Unpacking error payload.bin

### ISSUE THREAD

**Issue by kory-vadim** [chenxiaolong/avbroot#382]
0.006s ERROR Failed to read payload header: "payload.bin"

Caused by:
    0: Failed to decode protobuf message
    1: failed to decode Protobuf message: DeltaArchiveManifest.partial_update: invalid wire type: LengthDelimited (expected Varint)

**Comment by chenxiaolong** [comment]
Please post a link to the OTA.

**Comment by kory-vadim** [comment]
https://mega.nz/file/Bp8SySaI#n8cydP1ezejzdZxDzrxyPkjBFHPtwTfpiHJ5ROIKtRo

**Comment by chenxiaolong** [comment]
Thanks for uploading the file. Unfortunately, this is not something I can support in avbroot.

ASUS made changes to the `payload.bin` header that are completely incompatible with and conflict with the standard AOSP header format.

---

<details>
<summary>Details:</summary>

The `payload.bin` header is a `DeltaArchiveManifest` protobuf message that looks like this:

```protobuf
message DeltaArchiveManifest {
  // ...
  optional bool partial_update = 16;
  repeated ApexInfo apex_info = 17;
  optional string security_patch_level = 18;
}
```

ASUS removed fields 16 and 18, renumbered 17 to 26, and added a bunch of custom fields in between. That's absolutely not how protobuf is meant to be extended. With the way that they broke compatibility, they can't really fix it and will forever have to maintain their custom header format (at least for this device).
</details>
