### ISSUE TITLE
Fails on Google Pixel 9 Pro XL

### ISSUE THREAD

**Issue by sepruko** [chenxiaolong/avbroot#383]
After following the instructions from the `README.md` twice from a factory device (reflashed via booting into fastboot using the hardware key combination and using `flash-all.bat` provided with the OEM factory image), and verifying that the patched OTA is validated with `avbroot ota verify`, the phone will not boot into the self-signed patched OS.

'Your device is corrupt. It can't be trusted and may not work properly.' Attempting to boot from here gets indefinitely stuck on the Google 'G'.

I don't feel as if I've missed anything, but it just doesn't want to work and I have to keep erasing the custom avb key and flashing stock to get the phone back to a bootable state.

**Comment by chenxiaolong** [comment]
Hmm, would you mind trying again, but for step 4 in the [initial setup steps](https://github.com/chenxiaolong/avbroot?tab=readme-ov-file#initial-setup), pass in `--all`? (Assuming you haven't tried that already) 

Please also post the full output of all the fastboot commands. I'm hoping there will be something in there that points to what the problem might be.

**Comment by sepruko** [comment]
I ran `flash-all.bat` again just to be safe, recreated the patched OTA and re-verified it with `avbroot ota verify`, and then went through the process again.

```
[REDACTED] ~\[REDACTED]\komodo\ota λ fastboot --version
fastboot version 35.0.2-12147458
Installed as C:\Users\[REDACTED]\AppData\Local\Android\SDK\platform-tools\fastboot.exe
[REDACTED] ~\[REDACTED]\komodo\ota λ adb reboot bootloader
[REDACTED] ~\[REDACTED]\komodo\ota λ fastboot flashing unlock
(bootloader) device already unlocked
OKAY [  0.014s]
Finished. Total time: 0.014s
[REDACTED] ~\[REDACTED]\komodo\ota λ avbroot ota extract --input .\komodo-ota-ap3a.241105.008-9be9eed2.patched.zip --directory extracted --fastboot --all
  0.008s  INFO Extracting from the payload: abl, bl1, bl2, bl31, boot, dtbo, gcf, gsa, gsa_bl1, init_boot, ldfw, modem, pbl, product, pvmfw, system, system_dlkm, system_ext, tzsw, vbmeta, vbmeta_system, vbmeta_vendor, vendor, vendor_boot, vendor_dlkm, vendor_kernel_boot
 58.012s  INFO Successfully extracted OTA
[REDACTED] ~\[REDACTED]\komodo\ota λ $env:ANDROID_PRODUCT_OUT = "extracted"
[REDACTED] ~\[REDACTED]\komodo\ota λ fastboot flashall --skip-reboot
--------------------------------------------
Bootloader Version...: ripcurrentpro-15.0-12164710
Baseband Version.....: g5400c-240718-240719-B-12112834
Serial Number........: 46161FDAS000GB
--------------------------------------------
Checking 'product'                                 OKAY [  0.000s]
Setting current slot to 'b'                        OKAY [  0.136s]
Sending 'boot_b' (65536 KB)                        OKAY [  1.588s]
Writing 'boot_b'                                   OKAY [  0.176s]
Sending 'dtbo_b' (16384 KB)                        OKAY [  0.401s]
Writing 'dtbo_b'                                   OKAY [  0.040s]
Sending 'init_boot_b' (8192 KB)                    OKAY [  0.193s]
Writing 'init_boot_b'                              OKAY [  0.026s]
Sending 'pvmfw_b' (1024 KB)                        OKAY [  0.025s]
Writing 'pvmfw_b'                                  OKAY [  0.011s]
Sending 'vbmeta_b' (12 KB)                         OKAY [  0.001s]
Writing 'vbmeta_b'                                 OKAY [  0.008s]
Sending 'vbmeta_system_b' (4 KB)                   OKAY [  0.001s]
Writing 'vbmeta_system_b'                          OKAY [  0.008s]
Sending 'vbmeta_vendor_b' (4 KB)                   OKAY [  0.001s]
Writing 'vbmeta_vendor_b'                          OKAY [  0.008s]
Sending 'vendor_boot_b' (65536 KB)                 OKAY [  1.464s]
Writing 'vendor_boot_b'                            OKAY [  0.171s]
Sending 'vendor_kernel_boot_b' (65536 KB)          OKAY [  1.503s]
Writing 'vendor_kernel_boot_b'                     OKAY [  0.161s]
Rebooting into fastboot                            OKAY [  0.001s]
< waiting for any device >
fastboot: error: Failed to boot into userspace fastboot; one or more components might be unbootable.
[REDACTED] ~\[REDACTED]\komodo\ota λ fastboot reboot-bootloader
Rebooting into bootloader                          OKAY [  0.000s]
Finished. Total time: 0.007s
[REDACTED] ~\[REDACTED]\komodo\ota λ fastboot erase avb_custom_key
Erasing 'avb_custom_key'                           (bootloader) avb custom key: erase done
OKAY [  0.016s]
Finished. Total time: 0.023s
[REDACTED] ~\[REDACTED]\komodo\ota λ fastboot flash avb_custom_key ..\..\avb-keyring\avb_pkmd.bin
Warning: skip copying avb_custom_key image avb footer (avb_custom_key partition size: 0, avb_custom_key image size: 1032).
Sending 'avb_custom_key' (1 KB)                    OKAY [  0.001s]
Writing 'avb_custom_key'                           (bootloader) avb custom key: flash done
OKAY [  0.039s]
Finished. Total time: 0.061s
```

This is the first time I've gotten 'fastboot: error: Failed to boot into userspace fastboot; one or more components might be unbootable.' The phone still shows the same 'Your device is corrupt. It can't be trusted and may not work properly.'

**Comment by chenxiaolong** [comment]
Thanks! Yeah, the:
```
fastboot: error: Failed to boot into userspace fastboot; one or more components might be unbootable.
```
could definitely cause what you're seeing. If it can't reboot into userspace fastboot mode (also known as `fastbootd`), then several partitions don't get flashed. The problematic one that's being omitted in your case is `system`. The patched `system` didn't get flashed, so during boot, it would be trying to verify the stock `system` (from when you used `flash-all.bat`) using your custom AVB key.

Since you're on Windows, I would suggest manually (re)installing Google's USB drivers from https://developer.android.com/studio/run/win-usb (instructions are on a [separate page](https://developer.android.com/studio/run/oem-usb#InstallingDriver)). The default drivers only work with the bootloader's fastboot mode, not the userspace fastboot mode.

---

Also, it's worth pointing out that the reason you don't encounter this issue when flashing the stock OS with `flash-all.bat` is because it uses an optimization that avoids needing to reboot into userspace fastboot mode in the first place. Unfortunately, an OTA file does not contain enough information to take advantage of this optimization, so flashing avbroot's patched files requires userspace fastboot mode to work properly.

**Comment by chenxiaolong** [comment]
If installing Google's USB drivers doesn't fix the issue when running `fastboot flashall`, you can try this:

1. Follow the `fastboot flashall` step, even if it's going to fail
2. Reboot into recovery mode
3. Sideload your patched OTA with `adb sideload`
4. Reboot into the bootloader
5. Continue with flashing `avb_custom_key` and locking the bootloader

**Comment by sepruko** [comment]
Installing the USB drivers worked a treat, thanks!

**Comment by ZeWaren** [comment]
I had the same issue and I confirm the comments of this issue works. 

"Your device is corrupt. It can't be trusted and may not work properly."
And I had an eternal useless "G" logo when trying to boot the OS.

Flashing the update with `--all` worked.
I flashed in order:
- The stock Graphene (version N-2), to initialize the device;
- A patched OTA update (version N-1) extracted with `--all`, then I locked the bootloader;
- Another OTA update (version N), with `adb sideload` to confirm everything is working correctly.

Currently running grapheneos 2025060200 on komodo (Pixel 9 Pro XL) with magisk-canary 29 and ReZyGisk.

**Comment by morganther** [comment]
i'm getting this with GrapheneOS 2026081301. starting from GrapheneOS, i did this:

```
$ avbroot ota extract --input komodo-2026081301-*-rootless.zip --directory extracted --fastboot
  0.001s  INFO Extracting from the payload: boot, init_boot, system, vbmeta, vendor_boot
  8.322s  INFO Successfully extracted images from payload
$ export ANDROID_PRODUCT_OUT=extracted
$  fastboot flashall --skip-reboot
--------------------------------------------
Bootloader Version...: ripcurrentpro-17.0-15199480
Baseband Version.....: g5400c-260317-260429-B-15308590
Serial Number........: 
--------------------------------------------
Checking 'product'                                 OKAY [  0.000s]
Setting current slot to 'a'                        OKAY [  0.101s]
Sending 'boot_a' (65536 KB)                        OKAY [  1.508s]
Writing 'boot_a'                                   OKAY [  0.086s]
Sending 'init_boot_a' (8192 KB)                    OKAY [  0.189s]
Writing 'init_boot_a'                              OKAY [  0.016s]
Sending 'vbmeta_a' (8 KB)                          OKAY [  0.001s]
Writing 'vbmeta_a'                                 OKAY [  0.005s]
Sending 'vendor_boot_a' (65536 KB)                 OKAY [  1.512s]
Writing 'vendor_boot_a'                            OKAY [  0.124s]
Rebooting into fastboot                            OKAY [  0.000s]
< waiting for any device >
Resizing 'system_a'                                OKAY [  0.014s]
Invalid sparse file format at header magic
Sending sparse 'system_a' 1/6 (262108 KB)          OKAY [  6.462s]
Writing 'system_a'                                 OKAY [  0.426s]
Sending sparse 'system_a' 2/6 (262128 KB)          OKAY [  6.440s]
Writing 'system_a'                                 OKAY [  0.394s]
Sending sparse 'system_a' 3/6 (262116 KB)          OKAY [  6.420s]
Writing 'system_a'                                 OKAY [  0.430s]
Sending sparse 'system_a' 4/6 (262120 KB)          OKAY [  6.447s]
Writing 'system_a'                                 OKAY [  0.438s]
Sending sparse 'system_a' 5/6 (252024 KB)          OKAY [  6.172s]
Writing 'system_a'                                 OKAY [  0.410s]
Sending sparse 'system_a' 6/6 (20688 KB)           OKAY [  0.517s]
Writing 'system_a'                                 OKAY [  0.083s]
Finished. Total time: 70.157s
$  fastboot reboot-bootloader
Rebooting into bootloader                          OKAY [  0.002s]
Finished. Total time: 0.152s
$ fastboot erase avb_custom_key
Erasing 'avb_custom_key'                           (bootloader) avb custom key: erase done
OKAY [  0.024s]
Finished. Total time: 0.026s
$ fastboot flash avb_custom_key avb_pkmd.bin
Warning: skip copying avb_custom_key image avb footer (avb_custom_key partition size: 0, avb_custom_key image size: 1032).
Sending 'avb_custom_key' (1 KB)                    OKAY [  0.000s]
Writing 'avb_custom_key'                           (bootloader) avb custom key: flash done
OKAY [  0.037s]
Finished. Total time: 0.039s
$  fastboot reboot recovery
Rebooting into recovery                            OKAY [  0.000s]
Finished. Total time: 0.251s
$  adb sideload komodo-2026081301-30a5d5a-magisk-v30.7.zip
Total xfer: 2.00x
```

the sideload was successful, but it booted into the "Your device is corrupt" message and just looped from there. I can flash back to stock GrapheneOS though. I'm having trouble interpreting @ZeWaren's comment
