### ISSUE TITLE
Starting with incremental OTA?

### ISSUE THREAD

**Issue by danwdart** [chenxiaolong/avbroot#387]
Hi,

I found a full OTA and two sequential incremental OTAs, but not a full OTA with it all in it. Is it necessary/worth it to merge these into the full OTA in order to generate one or will the extract from fastboot command given in the readme be enough to get the same patches?

Thanks

**Comment by chenxiaolong** [comment]
If you want to be on the latest version, then I think you have no choice but to merge them. Sadly, the only tool I'm aware of that can apply the patches from an incremental OTA is Android's OTA updater (`update_engine`) and its corresponding `delta_generator` tool. There are no prebuilt binaries for `delta_generator` and you would have to build half of Android from source to use it (~400 GiB and a whole lot of time).

The general approach would be something like this:

1. Extract all the partitions from the full OTA
2. Use `delta_generator` to apply the changes from an incremental OTA's `payload.bin`
3. Generate a new full OTA by:
   * Replacing all the partitions in the full OTA's `payload.bin` with the new ones
   * Updating the full OTA's metadata in `META-INF/com/android/metadata` and `metadata.pb` with the version numbers, etc. from the incremental OTA

After going through that twice for the 2 incremental OTAs, the resulting full OTA can be fed into avbroot.

If you're interested, I can make a small tool to do this. (I build Android from source all the time. If you don't want to build `delta_generator` yourself and don't mind using a binary I built, then I can upload one that's compiled for Linux x86_64.)

**Comment by chenxiaolong** [comment]
https://github.com/chenxiaolong/avbroot-inc-ota now supports taking a full OTA + an incremental OTA and producing a new full OTA (which can then be fed into avbroot).

It can be used like this:

```bash
avbroot-inc-ota \
    apply \
    --input-old old_full_ota.zip \
    --input-inc incremental_ota.zip \
    --output-new new_full_ota.zip \
    --key ota.key \
    --cert ota.crt \
    --delta-generator /path/to/delta_generator
```

(For the 2nd incremental OTA, use the output of the 1st run as `--input-old` in the second run.)

Here is `delta_generator` I built (for Linux x86_64) from GrapheneOS' `2024121200` tag:

* Binary: https://files.pub.chiller3.com/issues/avbroot/issue387/delta_generator.grapheneos_2024121200
* Signature: https://files.pub.chiller3.com/issues/avbroot/issue387/delta_generator.grapheneos_2024121200.sig (signed with [same key](https://github.com/chenxiaolong/avbroot?tab=readme-ov-file#verifying-digital-signatures) as avbroot)

**Comment by pixincreate** [comment]
do you think this be used with `Custota` provided I publish incremental OTAs with `avbroot-inc-ota`?
