### ISSUE TITLE
Like avbroot.

### ISSUE THREAD

**Issue by langleyasukasoryu** [chenxiaolong/avbroot#396]
We recently installed the Lineage "mod" with KernelSU from xda (we have Pixel 4(Yeah, non-gki)).
Also after that we tried Divest, it was more stable and faster than Calyx (With all settings and applications, in general divest has a lot of settings and they are good).
But for Calyx and Divest (Pixel 4) there is no ready-made solution with KernelSU, so we want to take it into our "script(?) kiddy" hands.

We really liked KernelSU.
In general we want to build KernelSU under Divest while making avbroot installation (patch).

There is already a kernel built for our device https://github.com/msnx/KernelSU-Pixel4XL.

As far as we understand, if we unpack the firmware archive, make changes and repackage it, avbroot will give an error?
There are also difficulties here, avbroot requires ota, ota structure is payload.bin and etc, we have to unpack and repack with "kernelsu.img", we also don't quite understand what tool can be used to repack to ota..

A simpler question is, can we take this "kernelsu-boot.img" and patch it separately?

**Comment by chenxiaolong** [comment]
Just to make sure I understand, you'd like to create a new `boot.img` using the ramdisk from DivestOS and kernel from https://github.com/msnx/KernelSU-Pixel4XL and then use that modified boot image when patching the OTA?

If so, it is possible, though a little tedious. Assuming that DivestOS is actually compatible with that kernel, then this should work:

1. Extract `boot.img` from the original DivestOS OTA:

    ```bash
    avbroot ota extract -i divestos.zip -d extracted
    ```

2. Unpack the DivestOS `boot.img`:

    ```bash
    mkdir boot
    cd boot
    avbroot avb unpack -i ../extracted/boot.img
    avbroot boot unpack -i raw.img
    cd ..
    ```

3. Unpack the `boot.img` from https://github.com/msnx/KernelSU-Pixel4XL:

    ```bash
    mkdir kernelsu
    cd kernelsu
    avbroot boot unpack -i ../pixel4xl_android13_4.14.276_v095.img
    cd ..
    ```

4. Copy and overwrite just the kernel portion of the boot image:

    ```bash
    cp kernelsu/kernel.img boot/kernel.img
    ```

5. Repack `boot.img` (use the same `avb.key` as for patching the OTA):

    ```bash
    cd boot
    avbroot boot pack -o raw.img
    avbroot avb pack -o ../boot.modified.img -k /path/to/avb.key
    cd ..
    ```

6. Patch the OTA as normal, but pass in the `--prepatched boot.modified.img` to use the newly modified boot image.

**Comment by langleyasukasoryu** [comment]
It's not working, 5 min google logo, before black screen.  
And.. Vibro.. It,s working screen edge. And not working screen.
Reboot to bootloader, reflash stock and reflash patched. 
Really not working. 

./fastboot flash boot boot.modified.img.
Before flash patched OTA. Not working.

Patch OTA with pixel4xl_android13_4.14.276_v095.img and kernelsu.img from xda lineage with kernelsu... 
Not working. So sad.

Give these errors.

First:
```
avbroot ota patch --input divest/divested-20.0-20241208-dos-coral.zip --key-avb avb.key --key-ota ota.key --cert-ota ota.crt --prepatched pixel4xl_android13_4.14.276_v095.img

  3.145s  INFO Replacing zip entry: META-INF/com/android/otacert
  3.145s  INFO Copying zip entry: apex_info.pb
  3.145s  INFO Copying zip entry: care_map.pb
  3.145s  INFO Patching zip entry: payload.bin
  3.145s  INFO Extracting from original payload: boot
  3.590s  INFO Extracting from original payload: system
 11.039s  INFO Extracting from original payload: vbmeta
 11.039s  INFO Candidate boot images: boot
 11.239s  WARN The prepatched boot image may not be compatible with the original:
- Field differs: old.os_version (436208012) -> new.os_version (0)
- Field differs: &old.id ([3858277810, 81736443, 1395059214, 716171165, 24153910, 0, 0, 0]) -> &new.id ([22946166, 2984370369, 98165655, 1611092176, 2100671402, 0, 0, 0])
 11.405s ERROR Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to patch boot images: boot
    2: Validation error: The prepatched boot image is not compatible with the original:
       - Field differs: &old.cmdline ("console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 printk.devkmsg=on msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 androidboot.memcg=1 cgroup.memory=nokmem usbcore.autosuspend=7 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 androidboot.boot_devices=soc/1d84000.ufshc loop.max_part=7 cgroup_disable=pressure buildvariant=user") -> &new.cmdline ("console=ttyMSM0,115200n8 androidboot.console=ttyMSM0 printk.devkmsg=on msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 androidboot.memcg=1 cgroup.memory=nokmem usbcore.autosuspend=7 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 androidboot.boot_devices=soc/1d84000.ufshc loop.max_part=7 buildvariant=user")
```

KernelSU.img from XDA:
```
- Field differs: old.os_version (436208012) -> new.os_version (436208002)
- Field differs: &old.id ([3858277810, 81736443, 1395059214, 716171165, 24153910, 0, 0, 0]) -> &new.id ([2982781628, 666598502, 1601595903, 1324146414, 1177155451, 0, 0, 0])
 12.806s ERROR Failed to patch OTA zip
```

Probably it can be solved if you find sources of patched divest kernel or take lineage kernel and patch it with divest scripts, then patch it for kernelsu then implement it into firmware using the method you described, patch, install and most likely it won't work.
We should probably apologise for our time.

**Comment by chenxiaolong** [comment]
> We should probably apologise for our time.

No worries! Yeah, sounds like patching the DivestOS sources with KernelSU and then building from source is probably the way to go.

**Comment by pixincreate** [comment]
And yeah, the same applies to GrapheneOS as well. Correct me if wrong, DivestOS does enforce signature verification for Kernel, right?

**Comment by chenxiaolong** [comment]
> Correct me if wrong, DivestOS does enforce signature verification for Kernel, right?

I took a quick look. It doesn't seem like `CONFIG_MODULE_SIG` is enabled, at least the DivestOS build for the Pixel 4. I think it's because they chose to compile all modules into the kernel instead of having separate `.ko` files, so there would be nothing to verify.
