### ISSUE TITLE
Error when using a prepatched ksu image

### ISSUE THREAD

**Issue by LucyKushinada00** [chenxiaolong/avbroot#399]
I'm getting the following error when patching and OTA with a ksu prepatched init_boot image. I'm trying to install Android 16 DP2 on my Pixel 7 Pro but the issue is also persistent with DP1. I was able to use it successfully a couple of months back but it's not working anymore. Kindly find the error below:
`0: Failed to patch payload: payload.bin
1: Failed to patch boot images: boot, init_boot, vendor_boot
2: Boot image error
3: I/O error
4: failed to fill whole buffer`

I tried both on a Windows 11 Pro machine as well as Debian 12

**Comment by chenxiaolong** [comment]
Can you please upload the prepatched `init_boot` image? (You might need to zip it for Github to allow the upload.)

**Comment by LucyKushinada00** [comment]
Yep sure, I added the init_boot prepatched files for both vanilla ksu and ksu next since both are having the same issue. I hope this helps
![avbroot.zip](https://github.com/user-attachments/files/18193225/avbroot.zip).
Please let me know if anything else is required

**Comment by chenxiaolong** [comment]
Hmm, could you provide the avbroot version and exact command you're running that gives you the error? I can't seem to reproduce it using the Pixel 7 Pro Android 16 DP2 OTA and with either init_boot file for `--prepatched`:

```
$ avbroot --version
avbroot 3.10.0
```

```
$ avbroot ota patch --key-avb avb.key --key-ota ota.key --cert-ota ota.crt --input cheetah_beta-ota-bp21.241121.009-66b278eb.zip --prepatched kernelsu_next_init.img
  0.086s  INFO Replacing zip entry: META-INF/com/android/otacert
  0.086s  INFO Copying zip entry: apex_info.pb
  0.086s  INFO Copying zip entry: care_map.pb
  0.086s  INFO Patching zip entry: payload.bin
  0.087s  INFO Extracting from original payload: system
  1.266s  INFO Extracting from original payload: vbmeta_system
  1.266s  INFO Extracting from original payload: vendor_boot
  1.344s  INFO Extracting from original payload: vbmeta_vendor
  1.344s  INFO Extracting from original payload: vbmeta
  1.344s  INFO Extracting from original payload: init_boot
  1.398s  INFO Extracting from original payload: boot
  1.472s  INFO Candidate boot images: boot, init_boot, vendor_boot
  1.739s  INFO Patching system image: system
  2.547s  INFO Patched otacerts.zip offsets in system: [426491904..426494196]
  2.547s  INFO Patching vbmeta images: vbmeta_vendor, vbmeta_system, vbmeta
  2.567s  INFO Compressing full image: vbmeta_system
  2.568s  INFO Compressing full image: init_boot
  2.818s  INFO Compressing full image: vbmeta
  2.819s  INFO Compressing full image: vendor_boot
  3.377s  INFO Compressing partial image: system: [426491904..426494196, 1061113856..1077936960, 1078214592..1078214656]
  6.073s  INFO Generating new OTA payload
 22.204s  INFO Patching zip entry: payload_properties.txt
 22.204s  INFO Generating new OTA metadata
 22.213s  INFO Verifying metadata offsets
 22.214s  INFO Successfully patched OTA
```

**Comment by LucyKushinada00** [comment]
The command I used is `.\avbroot ota patch --input cheetah_beta-ota-bp21.241121.009-66b278eb.zip --key-avb signingKey/avb.key --key-ota signingKey/ota.key --cert-ota signingKey/ota.crt --prepatched kernelsu_patched_20241218_200124.img`, I renamed the prepatched image before sending it to you to avoid confusion. And maybe the issue is related to my signing keys? I had created them quite a while back, and they seem to be the only common factor here. I'm having this issue on the latest and second latest build of avbroot (3.10.0 and 3.9.0)

**Comment by chenxiaolong** [comment]
Hmm, that's really strange. I'll try testing in a Windows VM tomorrow.

The signing key isn't the problem. Your old keys should be perfectly fine. It almost seems like part of the init_boot file is missing, but not sure yet (the error is that it reached the end of the file before it finished reading all of the expected data).

**Comment by LucyKushinada00** [comment]
I'm not really sure what changed but I tried patching the init_boot image now and it seemed to work. I checked the MD5 file hashes for both the files and they're matching. I'll close the issue for now, if you need anything to help you figure out the issue do let me know I would love to help

**Comment by LucyKushinada00** [comment]
I'm not really sure what changed but I tried patching the init_boot image now and it seemed to work. I checked the MD5 file hashes for both the files and they're matching. I'll close the issue for now, if you need anything to help you figure out the issue do let me know I would love to help
