### ISSUE TITLE
Question on integrating Magisk rooting into GrapheneOS build

### ISSUE THREAD

**Issue by SigmaBonder** [chenxiaolong/avbroot#4]
I'm sorry I'm asking for help here — I realize this is a completely unrelated repo, but you seem to have Pixel 7 Pro as well and might be able to help me, so I thought I'll try. Feel free to close this and ignore this question if you don't have any time to spare.

I'm trying to incorporate Magisk rooting into my own GrapheneOS build. I've been roughly following [this guide](https://gist.github.com/mohrezaei/69dae8c7d43c543b38ee5d33f67400b5) for CalyxOS on Android 12. I changed necessary parts to intercept signing `init_boot` partition instead of `boot`, as I understand this is the image I need to patch with Magisk. Unfortunately, when this modified signing process is run, it exits with an error:
`/home/user/grapheneos-TD1A.220804.031.2022102800/out/release-cheetah-2022110200/bin/avbtool.real: Adding hash_footer failed: Image size of 1945600 exceeds maximum image size of 1531904 in order to fit in a partition size of 1601536..`
I don't know what to do with this, as I'm very new to the internals of Android. Somewhere on the web I found suggestions of repacking the image using various tools, but these efforts to reduce the size were unsuccessful in my case.

For reference, this is the output of `boot_patch.sh`:
```
- Unpacking boot image
Parsing boot image: [/tmp/tmpfn6kwvtw/etc/fs/microdroid_init_boot.img]
HEADER_VER      [4]
KERNEL_SZ       [0]
RAMDISK_SZ      [1456182]
PAGESIZE        [4096]
CMDLINE         []
RAMDISK_FMT     [lz4_legacy]
VBMETA
- Checking ramdisk status
Loading cpio: [ramdisk.cpio]
- Stock boot image detected
- Patching ramdisk
Loading cpio: [ramdisk.cpio]
Add entry [init] (0750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add entry [overlay.d/sbin/magisk32.xz] (0644)
Add entry [overlay.d/sbin/magisk64.xz] (0644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[false]
Loading cpio: [ramdisk.cpio.orig]
Backup mismatch entry: [init] -> [.backup/init]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk32.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk64.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add entry [.backup/.magisk] (0000)
Dump cpio: [ramdisk.cpio]
- Repacking boot image
Parsing boot image: [/tmp/tmpfn6kwvtw/etc/fs/microdroid_init_boot.img]
HEADER_VER      [4]
KERNEL_SZ       [0]
RAMDISK_SZ      [1456182]
PAGESIZE        [4096]
CMDLINE         []
RAMDISK_FMT     [lz4_legacy]
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [4]
KERNEL_SZ       [0]
RAMDISK_SZ      [1940869]
PAGESIZE        [4096]
CMDLINE         []
```

Do you have any ideas about what I need to change? Thank you in advance for any suggestions.

**Comment by chenxiaolong** [comment]
Interesting. I've never seen this done by intercepting avbtool, but that does seem like a decent, albeit hacky, way to patch the boot image. Looking at the page you linked, it looks like all of the `avbtool` invocations are logged to a `avbtool-invokes.txt` file. Is there anything in there that might indicate where the `1531904` number is coming from?

I don't think you're hitting an actual size limit because it's complaining about something in the 1.5MB range which the `init_boot` image for the stock firmware is 8MB. Maybe there's a soft limit that's being set somewhere.

(I haven't personally done a GrapheneOS + Magisk build, so this is new to me as well.)

**Comment by SigmaBonder** [comment]
For me it looked like the simplest way, since Magisk isn't my onIy goal here and I wanted to build my own version of GrapheneOS anyway. I considered using avbroot, but you yourself recommend against it and it would require me to add yet another step and manage yet another set of keys, which would complicate an already barely understandable process for me even further.

Yes, `avbtool-invokes.txt` shows this, among other things:
```
%%%%%%%%%% Thu Nov 3 01:58:33 CET 2022 Running avbtool with add_hash_footer --key keys/avb.pem --algorithm SHA256_RSA4096 --partition_name init_boot --partition_size 1601536 --image /tmp/tmpfn6kwvtw/etc/fs/microdroid_init_boot.img
%%%%%%%%%% Thu Nov 3 01:58:33 CET 2022 Running avbtool with add_hash_footer --key keys/avb.pem --algorithm SHA256_RSA4096 --partition_name boot --partition_size 51589120 --image /tmp/tmpfn6kwvtw/etc/fs/microdroid_boot-5.10.img
```
So `avbtool` is already invoked with partition size of `1601536`, but that doesn't explain where this number is coming from. The GrapheneOS's release script only calls `sign_target_files_apks` binary. After some digging, I would guess that calculating partition size happens [somewhere in here](https://android.googlesource.com/platform/build/+/master/tools/releasetools/verity_utils.py#221), in `verity_utils.py`, even though I'm not really sure what the execution path really looks like. I'm completely unfamiliar with this code and process, so I can't really verify where the bug stems from.

**Comment by chenxiaolong** [comment]
It looks like `verity_utils.py` is called by the build system from here: https://cs.android.com/android/platform/superproject/+/android-13.0.0_r8:build/soong/filesystem/bootimg.go;l=222

It might be worth trying to apply Magisk to the unsigned `init_boot` at that point instead of hijacking one of the avbroot commands. That should allow the Magisk patch to run before any partition sizes are calculated. I'll give it a try this weekend.

**Comment by chenxiaolong** [comment]
Please give https://github.com/chenxiaolong/aosproot a try. I unfortunately don't have a spare device to test this on, but I was able to build GrapheneOS for `cheetah` with a rooted and signed `init_boot`. (Tested with `grep magisk init_boot.img` and `external/avb/avbtool info_image --image init_boot.img`.)

**Comment by SigmaBonder** [comment]
Thank you so much! I will definitely try it tomorrow (as I have a few different issues I'm trying to resolve in the meantime), but I have good feelings about it — and since you tested it already, everything should work as expected. I see you've taken a different approach than modifying Go code, and it seems simpler and more reliable indeed (to my untrained eye). Wish me luck, I'll get back to you tomorrow.

**Comment by chenxiaolong** [comment]
Thanks for reporting back! Glad you got it working :)
