### ISSUE TITLE
Verify Magisk APK signature

### ISSUE THREAD

**Issue by andylizi** [chenxiaolong/avbroot#400]
Thanks for the great project, it's working really well! I have a minor suggestion about security.

We don't need to think about security when update Magisk the traditional way because Android will verify its APK signature for us. But using avbroot means that we download the APK on our PC and patch it into the OTA without checking its signature, which makes this workflow a bit concerning. Currently I manually run `apksigner verify --print-certs`, but it'd be great if avbroot can have this verification step built-in.

**Comment by chenxiaolong** [comment]
Thanks for the suggestion!

I like the idea, but it's probably something I won't be able implement. There are two main concerns:

* Many of avbroot's users don't use official Magisk and either use a fork or compile it themselves.
* An APK can be signed 4 different ways and each of the signing schemes are not trivial to implement. I believe there's an unmaintained Rust library for verifying v2 signatures, but not for the rest.

I recommend continuing to use `apksigner verify --print-certs` like you're already doing.
