### ISSUE TITLE
Using this to patch CalyxOS

### ISSUE THREAD

**Issue by mizzunet** [chenxiaolong/avbroot#43]
In Readme, it said 
>  I highly recommend adding Magisk to the build process and then compiling from source instead.

May I know why is that? Any advantage for compiling over patching using this tool, I mean, the caveats applies for the compiled one as well, right?

I don't a server to build that is why I'm asking. I can't be more thankful for this tool :)

Edit:

In any case that my phone becomes unbootable (like flashed OTA of different signature and hadn't enabled OEM unlock) that means impossibly of flashing anything through fastboot, not even stock, right?

And I happened to understand that there's no EDL on Pixel. What would I do in that case?

Thanks

**Comment by chenxiaolong** [comment]
Glad you're enjoying avbroot!

> May I know why is that? Any advantage for compiling over patching using this tool
>
> I don't a server to build that is why I'm asking. I can't be more thankful for this tool :)

The main reason is that it's more reliable to patch the boot image during boot. There are less moving parts and all the signing steps happen as they normally would for an (unrooted) AOSP build. You'd also be able to do OTA updates like normal if you use your own AOSP builds.

Besides that, there isn't really a functional difference if you use avbroot compared to building AOSP with Magisk.

> I mean, the caveats applies for the compiled one as well, right?

Yep, that is correct!

> In any case that my phone becomes unbootable (like flashed OTA of different signature and hadn't enabled OEM unlock) that means impossibly of flashing anything through fastboot, not even stock, right?
>
> And I happened to understand that there's no EDL on Pixel. What would I do in that case?

That is correct. If OEM unlocking is unchecked and the system becomes unbootable, there is no known way to recover, so the device is hard bricked. EDL mode could theoretically work for Qualcomm-based Pixels if the required files were made public. I'm not aware of anything like EDL for Tensor-based Pixels.

**Comment by chenxiaolong** [comment]
> Oh wait, in case unbootable system that caused by any of reason. Won't recovery be still accessible no matter what?

It depends on the device. On the Pixel 6 and 7 series, for example, the same kernel and ramdisk are used by both the regular Android system and recovery mode.

For devices with a separate `recovery` partition (both kernel and ramdisk), recovery by flashing a new patched OTA is possible. Well, as long as the user didn't use root access to corrupt the recovery partition while booted into Android.
