### ISSUE TITLE
old Pixels do not have vendor_boot.img, use boot.img instead

### ISSUE THREAD

**Issue by vbooka1** [chenxiaolong/avbroot#5]
First of all, many thanks for your script! It is much easier than building GrapheneOS from scratch (and it does not build anyway lol if you follow instructions on their official website)

However I had to modify your script to make it work with Pixel 4a, please see a diff attached. You might consider adding some checks to determine the phone model automatically.

[avbroot_sunfish.txt](https://github.com/chenxiaolong/avbroot/files/10098407/avbroot_sunfish.txt)

**Comment by vbooka1** [comment]
hmm, something is wrong. 

I have flashed the patched boot.img and patched an **old** GrapheneOS factory image - 2022102800, then **did not** lock the flashing with `fastboot flashing lock`, booted to OS, installed Magisk manager app, but it did not see Magisk installed and offered to patch the boot.img from within the app. 
I gave the already patched boot.img to Magisk app, received a "magisk_patched_xxxxxxxx.img", flashed it with `fastboot flash boot magisk_patched_*img`, rebooted and Magisk manager app told that Magisk installed - root works.

Then I've rebooted to recovery, installed a **new version** of GrapheneOS - 2022112500 - with `adb sideload sunfish-ota_update-2022112500.zip.patched`, rebooted to fastboot, **locked** the flashing with `fastboot flashing lock`. Then I've rebooted to OS and found out that the device was wiped - I was greeted with device setup screen, and Magisk app was not installed.

After I've installed the Magisk app it showed that there is no root, again.

Do I understand correctly that I must not lock flashing in the `fastboot` and have to flash the patched `boot.img` each time I install an OTA update?

**Comment by chenxiaolong** [comment]
Interesting, I'll try out your diff and see what the patched output looks like. I suspect the Magisk boot image patch is somehow not ending up in `boot.img`.

Once you flash the patched OTA, if things are working, there's nothing you need to do besides installing the Magisk apk (which must be the same one you used during patching). The Magisk app won't be preinstalled.

> Do I understand correctly that I must not lock flashing in the fastboot and have to flash the patched boot.img each time I install an OTA update?

This should not be necessary. `adb sideload <file>.patched` is the only needed step for flashing updates and can be done while locked or unlocked.

**Comment by chenxiaolong** [comment]
Please give #6 a try. I tested it with the `cheetah` (`init_boot` + `vendor_boot`), `redfin` (`boot` + `vendor_boot`), and `sunfish` (`boot`) GrapheneOS OTAs.

Looking at the patched ramdisk, they all seem good, but I could only test `cheetah` on a real device. Hopefully it works on your `sunfish` too.

**Comment by vbooka1** [comment]
I've patched the old and new OTA update archives (20221028 and 20221125) with your new script version and this time it worked well, so something definitely was wrong with my dirty hack.

Full log of my actions:

1) flashed the original GrapheneOS release version 2022102800 with its `flash-all.sh`

2) patched the OTA archive version 2022102800 with `avbroot` and flashed the extracted `boot.img` and `vbmeta.img`:

- `fastboot flash boot_a boot.img`
- `fastboot flash boot_b boot.img`
- `fastboot flash vbmeta vbmeta.img`
- `fastboot erase avb_custom_key`
- `fastboot flash avb_custom_key avb_pkmd.bin`
- `fastboot reboot-bootloader`

3) LOCKED the flashing:

- `fastboot flashing lock`

4) booted to GrapheneOS and installed Magisk manager app. And it showed that Magisk is installed! i.e. it did not offer to patch the `boot.img` from within the app. However it said that it needs to do some extra stuff and to reboot the phone, I agreed and after the reboot root was working - I've checked it with `adb`. 

5) rebooted to recovery and tried to install the original GrapheneOS OTA update:

- `adb sideload sunfish-ota_update-2022112500.zip`

and it failed with error "Signature verification failed, error: 21", so the custom AVB key works well.

6) installed the `avbroot`-patched OTA update version 2022112500

- `adb sideload sunfish-ota_update-2022112500.zip.patched`

7) booted to GrapheneOS and discovered that the version changed from 2022102800 to 2022112500, the Magisk app was intact, and root still worked. 

So I do confirm that your commit works on `sunfish`, thank you!

Probably you should edit the README "Usage" part, paragraph 9?  Change

`fastboot flash boot extracted/boot.img`

to

`fastboot flash boot_a extracted/boot.img`
`fastboot flash boot_b extracted/boot.img`

?

**Comment by chenxiaolong** [comment]
Great, thanks for testing so thoroughly!

> Probably you should edit the README "Usage" part, paragraph 9?  Change
>
> `fastboot flash boot extracted/boot.img`
>
> to
>
> `fastboot flash boot_a extracted/boot.img`
> `fastboot flash boot_b extracted/boot.img`

Do you know if this is strictly necessary on the Pixel 4a? On my Pixel 7 Pro, just `fastboot flash boot extracted/boot.img` is enough.

**Comment by vbooka1** [comment]
> Do you know if this is strictly necessary on the Pixel 4a?

I'm not 100% sure, I've decided to flash these two partitions separately "just to make sure", and it worked.

**Comment by powellnorma** [comment]
> Do you know if this is strictly necessary on the Pixel 4a? On my Pixel 7 Pro, just fastboot flash boot extracted/boot.img is enough.

When using `fastboot flash boot`, it seems to only flash `boot_a`:

```sh
$ fastboot flash boot extracted/boot.img
Sending 'boot_a' (65536 KB)                        OKAY [  1.710s]
Writing 'boot_a'                                   OKAY [  0.305s]
Finished. Total time: 2.320s
```

**Comment by chenxiaolong** [comment]
> When using `fastboot flash boot`, it seems to only flash `boot_a`:

That should be sufficient. Only the currently active slot needs to be flashed initially. The next time a (patched) OTA is installed, all of the `b` partitions, including `boot_b`, will be flashed.

**Comment by Sleuth56** [comment]
Flashing both a and b partitions worked for me to. It wasn't working with just `fastboot flash boot`
