### ISSUE TITLE
Issues with libfs_avb

### ISSUE THREAD

**Issue by Mia-Rain** [chenxiaolong/avbroot#60]
Hi!, I'm trying to use this to patch an unofficial Lineage OS 20 build for my Pixel 3a XL, but I'm having some issues.  
Everything seems to work fine but after booting in and check dmesg with root I'm seeing this:
```
[    1.245460] init: [libfs_avb]Invalid hash size: 
[    1.245470] init: [libfs_avb]Failed to verify vbmeta digest
[    1.245480] init: [libfs_avb]Returning avb_handle with status: VerificationDisabled
[    1.245492] init: [libfs_avb]AVB HASHTREE disabled on: /system
[    1.249671] init: [libfs_avb]AVB HASHTREE disabled on: /system_ext
[    1.251388] init: [libfs_avb]AVB HASHTREE disabled on: /vendor
[    1.253754] init: [libfs_avb]AVB HASHTREE disabled on: /product
```

I tried forcing openssl 1.1 incase that was the issue but that didn't fix anything, and I can't find an existing issue abt this so I don't know where I should go from here.. could I get some guidance? thanks,,

**Comment by chenxiaolong** [comment]
Hmm, interesting. I haven't come across `[libfs_avb]Invalid hash size: ` before. I wonder if there's something weird with how LineageOS builds their vbmeta images. Can you post a link to the build you're patching?

**Comment by chenxiaolong** [comment]
Also, could you run `cat /proc/cmdline /proc/bootconfig` as root and post the output?

**Comment by Mia-Rain** [comment]
Thanks for the quick reply! So I'm right in thinking this should work fine with another rom like Pixel Experience? 

I'm using the build from here https://wiki.oddsolutions.us/devices/bonito/ & https://updater.oddsolutions.us/#/devices/bonito/builds

(original xda post)
https://forum.xda-developers.com/t/unofficial-lineageos-20-for-the-google-pixel-3a-xl.4514861/

**Comment by chenxiaolong** [comment]
No problem! Looking at that build's `vbmeta.img`, I'm seeing this:

```
❯ avbtool info_image --image vbmeta.img
Minimum libavb version:   1.0
Header Block:             256 bytes
Authentication Block:     576 bytes
Auxiliary Block:          4096 bytes
Public key (sha1):        2597c218aae470a130f61162feaae70afd97f011
Algorithm:                SHA256_RSA4096
Rollback Index:           1675555200
Flags:                    3
Rollback Index Location:  0
Release String:           'avbtool 1.2.0'
```

The `Flags: 3` is `AVB_VBMETA_IMAGE_FLAGS_HASHTREE_DISABLED` + `AVB_VBMETA_IMAGE_FLAGS_VERIFICATION_DISABLED`. That ROM seems to be intentionally completely disabling verified boot.

It's possible for avbroot to work around that and force that field to 0, but if `vbmeta.img` wasn't originally generated correctly, the ROM won't be able to boot.

**Comment by Mia-Rain** [comment]
hmm, could we give that a try? It could take me a few hours to download a new rom on with me internet so I'd like to give what I have a try, if it doesn't work I'll just use Pixel Experience p sure.

Also it might be a good idea to add a detection system to check for this imo.

**Comment by Mia-Rain** [comment]
> Also, could you run `cat /proc/cmdline /proc/bootconfig` as root and post the output?

Do you still need this by any chance? I had to reflash the rom, but I can provide it now if you'd like

**Comment by chenxiaolong** [comment]
> hmm, could we give that a try? It could take me a few hours to download a new rom on with me internet so I'd like to give what I have a try, if it doesn't work I'll just use Pixel Experience p sure.

Also it might be a good idea to add a detection system to check for this imo.

Sure, let me create a branch with that change really quick.

> Do you still need this by any chance? I had to reflash the rom, but I can provide it now if you'd like

Yes please, if you could.

**Comment by chenxiaolong** [comment]
Please give #62 (`clear_vbmeta_flags` branch) a try. You'll have to pass the new `--clear-vbmeta-flags` option to avbroot when patching to set the flags to 0.

**Comment by Mia-Rain** [comment]
> > Do you still need this by any chance? I had to reflash the rom, but I can provide it now if you'd like
> 
> Yes please, if you could.

Here ya go, 

```
rcupdate.rcu_expedited=1 rootwait ro init=/init androidboot.bootdevice=7c4000.sdhci androidboot.baseband=sdm androidboot.keymaster=1 msm_drm.dsi_display0=dsi_sofef00_sdc_1080p_cmd_display::timing0 androidboot.force_normal_boot=1 androidboot.serialno=92TAX03437 androidboot.slot_suffix=_a androidboot.slot_retry_count=0 androidboot.slot_successful=no androidboot.hardware.platform=sdm670 androidboot.hardware=bonito androidboot.revision=MP1.0 androidboot.bootloader=b4s4-0.4-8048689 androidboot.hardware.sku=G020C androidboot.hardware.radio.subtype=3 androidboot.hardware.dsds=0 androidboot.secure_boot=PRODUCTION androidboot.cdt_hwid=0x05032803 androidboot.hardware.majorid=0x03 androidboot.dtb_idx=0 androidboot.dtbo_idx=8 androidboot.bootreason=reboot androidboot.hardware.ddr=4GB,Micron,LPDDR4X androidboot.ddr_info=Micron androidboot.ddr_size=4GB androidboot.hardware.emmc=64GB,Micron androidboot.cid=00000000 androidboot.boottime=0BLE:92,1BLL:62,1BLE:320,2BLL:130,2BLE:624,SW:10020,KL:31,KD:107,ODT:117,AVB:614,AFTL:0 androidboot.ramdump=disabled androidboot.blockchain=disabled usbcfg.suzyq=disabled androidboot.hardware.pcbcfg=BPPU androidboot.hardware.devcfg=B4UP root=PARTUUID=d0263452-32ef-445d-9dca-3d78d6a86cb0 androidboot.verifiedbootstate=orange androidboot.aftlstate=8 printk.devkmsg=on msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 firmware_class.path=/vendor/firmware cgroup.memory=nokmem lpm_levels.sleep_disabled=1 loop.max_part=7 androidboot.boot_devices=soc/7c4000.sdhci androidboot.super_partition=system buildvariant=userdebug console=null
cat: /proc/bootconfig: No such file or directory
```

**Comment by Mia-Rain** [comment]
> Please give #62 (`clear_vbmeta_flags` branch) a try. You'll have to pass the new `--clear-vbmeta-flags` option to avbroot when patching to set the flags to 0.

Thanks! I'll give it a go rn

**Comment by chenxiaolong** [comment]
> Here ya go, 
>
> ```
> rcupdate.rcu_expedited=1 rootwait ro init=/init androidboot.bootdevice=7c4000.sdhci androidboot.baseband=sdm androidboot.keymaster=1 msm_drm.dsi_display0=dsi_sofef00_sdc_1080p_cmd_display::timing0 androidboot.force_normal_boot=1 androidboot.serialno=92TAX03437 androidboot.slot_suffix=_a androidboot.slot_retry_count=0 androidboot.slot_successful=no androidboot.hardware.platform=sdm670 androidboot.hardware=bonito androidboot.revision=MP1.0 androidboot.bootloader=b4s4-0.4-8048689 androidboot.hardware.sku=G020C androidboot.hardware.radio.subtype=3 androidboot.hardware.dsds=0 androidboot.secure_boot=PRODUCTION androidboot.cdt_hwid=0x05032803 androidboot.hardware.majorid=0x03 androidboot.dtb_idx=0 androidboot.dtbo_idx=8 androidboot.bootreason=reboot androidboot.hardware.ddr=4GB,Micron,LPDDR4X androidboot.ddr_info=Micron androidboot.ddr_size=4GB androidboot.hardware.emmc=64GB,Micron androidboot.cid=00000000 androidboot.boottime=0BLE:92,1BLL:62,1BLE:320,2BLL:130,2BLE:624,SW:10020,KL:31,KD:107,ODT:117,AVB:614,AFTL:0 androidboot.ramdump=disabled androidboot.blockchain=disabled usbcfg.suzyq=disabled androidboot.hardware.pcbcfg=BPPU androidboot.hardware.devcfg=B4UP root=PARTUUID=d0263452-32ef-445d-9dca-3d78d6a86cb0 androidboot.verifiedbootstate=orange androidboot.aftlstate=8 printk.devkmsg=on msm_rtb.filter=0x237 ehci-hcd.park=3 service_locator.enable=1 firmware_class.path=/vendor/firmware cgroup.memory=nokmem lpm_levels.sleep_disabled=1 loop.max_part=7 androidboot.boot_devices=soc/7c4000.sdhci androidboot.super_partition=system buildvariant=userdebug console=null
> cat: /proc/bootconfig: No such file or directory
> ```

Thanks! That's pretty weird. The bootloader isn't setting any of the AVB-related options, like `androidboot.vbmeta.avb_version` or `androidboot.vbmeta.size`.

Hopefully clearing the flags fixes that. If not, I'm not really sure what the issue might be (and the bootloader unfortunately isn't open source, so it's hard to check).

**Comment by Mia-Rain** [comment]
Huzzah! It boots! I relocked the bootloader and the rom boots just fine. Thanks a ton!

**Comment by chenxiaolong** [comment]
Awesome, glad you got it working! I'll merge #62 then.
