### ISSUE TITLE
dmesg doesn't contain "libfs_avb"

### ISSUE THREAD

**Issue by Zahid-C** [chenxiaolong/avbroot#97]
I completed first 8 step, but when I try to verify using `sudo dmesg | grep libfs_avb` , console returned nothing. My device is Pixel 6 (oriole), and I used GrapheneOS, for detailed explanation I'm uploading the output of `sudo dmesg` command in console

[dmesg.log](https://github.com/chenxiaolong/avbroot/files/11573552/dmesg.log)

**Comment by pascallj** [comment]
The `dmesg | grep libfs_avb` command should be run on the device and not on your PC. I can see where the misunderstanding is coming from.

You can run it for example using an adb shell on your PC or a terminal emulator app on your device:
```sh
> su (accept su request on device)
> dmesg | grep libfs_avb
```

**Comment by Zahid-C** [comment]
Thank you for clarification. I succesfully verified
