### ISSUE TITLE
Skip passphrase prompt

### ISSUE THREAD

**Issue by null-von-sushi** [chenxiaolong/avbroot#99]
Is it somehow possible to skip the passphrase prompt?
I am trying to make an automatic update script for my ROM of choice, and it almost works, but I have to manually press <Enter> every time once it comes to the actual patching.

**Comment by chenxiaolong** [comment]
This is a good idea. Currently, the only way to do it is by decrypting the private keys:

```bash
openssl pkcs8 -in avb.key -topk8 -out unencrypted_avb.key -nocrypt
openssl pkcs8 -in ota.key -topk8 -out unencrypted_ota.key -nocrypt
```

I just created #100, which will provide a way to pass in the passphrases via files or environment variables.

**Comment by chenxiaolong** [comment]
This is now supported. The documentation can be found at: https://github.com/chenxiaolong/avbroot#non-interactive-use
